const text=(key,label,required=false)=>({key,label,type:'text',required});
const json=(key,label,empty='{}')=>({key,label,type:'json',empty});
const tags=(key,label)=>({key,label,type:'tags'});
export const contentConfigs={
  LocationDefinition:{label:'Locations',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('location_type','Location type',true),text('parent_location_id','Parent location ID'),tags('tags','Tags'),tags('available_actions','Available actions')]},
  Connection:{label:'Connections',fields:[text('label','Label',true),text('from_location_id','From location ID',true),text('to_location_id','To location ID',true),{key:'travel_time',label:'Travel time',type:'number'},{key:'resource_cost',label:'Resource cost',type:'number'},{key:'one_way',label:'One way',type:'checkbox'},tags('required_tags','Required tags'),json('conditions','Conditions'),{key:'enabled',label:'Enabled',type:'checkbox'}]},
  NPCDefinition:{label:'NPCs',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('faction_key','Faction key'),tags('tags','Tags'),tags('actions','Actions'),tags('dialogue_graph_ids','Dialogue graph IDs'),json('visibility_conditions','Visibility conditions'),json('combat_profile','Combat profile'),json('services','Services','[]')]},
  NPCInstance:{label:'NPC instances',fields:[text('definition_id','NPC definition ID',true),{key:'availability',label:'Availability',type:'select',options:['available','hidden','departed']},json('personal_state','Personal state'),text('inventory_container_id','Inventory container ID')]},
  NPCPlacement:{label:'NPC placements',fields:[text('npc_instance_id','NPC instance ID',true),text('location_id','Location ID',true),{key:'enabled',label:'Enabled',type:'checkbox'},json('visibility_conditions','Visibility conditions'),json('interaction_conditions','Interaction conditions'),json('schedule','Schedule')]},
  DialogueGraph:{label:'Dialogue',fields:[text('key','Stable key',true),text('name','Name',true),text('start_node_key','Start node key',true),json('nodes','Dialogue nodes','[]'),tags('tags','Tags')]},
  QuestDefinition:{label:'Quests',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category'),json('availability_conditions','Availability conditions'),json('objective_graph','Objective graph'),json('completion_rules','Completion rules'),json('failure_rules','Failure rules'),json('rewards','Rewards','[]'),{key:'repeatability',label:'Repeatability',type:'select',options:['never','repeatable','scheduled']},tags('tags','Tags')]},
  ItemDefinition:{label:'Items',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category',true),tags('tags','Tags'),{key:'stack_limit',label:'Stack limit',type:'number'},{key:'weight',label:'Weight',type:'number'},{key:'value',label:'Value',type:'number'},tags('equipment_slots','Equipment slots'),tags('granted_ability_ids','Granted ability IDs'),tags('actions','Actions'),json('requirements','Requirements'),json('modifiers','Modifiers','[]'),json('use_effects','Use effects','[]')]},
  AbilityDefinition:{label:'Abilities',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},tags('tags','Tags'),json('costs','Resource costs'),json('targeting','Targeting'),json('requirements','Requirements'),json('effects','Effects','[]'),{key:'cooldown',label:'Cooldown',type:'number'}]},
  EncounterDefinition:{label:'Encounters',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},tags('location_ids','Location IDs'),{key:'turn_model',label:'Turn model',type:'select',options:['individual_initiative','side_based','simultaneous']},json('participant_templates','Participants','[]'),json('victory_conditions','Victory conditions'),json('rewards','Rewards','[]'),tags('tags','Tags')]},
  AttributeDefinition:{label:'Attributes',fields:[text('key','Stable key',true),text('name','Name',true),text('category','Category'),{key:'data_type',label:'Data type',type:'select',options:['integer','decimal','boolean']},{key:'minimum',label:'Minimum',type:'number'},{key:'maximum',label:'Maximum',type:'number'},{key:'default_value',label:'Default value',type:'number',required:true},{key:'visibility',label:'Visibility',type:'select',options:['public','player','hidden']},tags('tags','Tags')]},
  FormulaDefinition:{label:'Formulas',fields:[text('key','Stable key',true),text('name','Name',true),json('expression','Expression'),{key:'output_type',label:'Output type',type:'select',options:['integer','decimal']},tags('tags','Tags')]},
  EffectDefinition:{label:'Effects',fields:[text('key','Stable key',true),text('name','Name',true),json('effects','Effects','[]'),tags('tags','Tags')]},
  StatusDefinition:{label:'Statuses',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},{key:'stacking',label:'Stacking',type:'select',options:['replace','stack','refresh']},{key:'maximum_stacks',label:'Maximum stacks',type:'number'},{key:'duration_type',label:'Duration type',type:'select',options:['turns','time','permanent']},json('effects','Effects','[]'),tags('tags','Tags')]}
};
export const gameFields=[text('title','Game title',true),{key:'description',label:'Description',type:'textarea'},json('terminology','Terminology'),json('theme','Theme'),tags('enabled_modules','Enabled modules'),tags('header_indicators','Header indicators'),json('navigation','Navigation','[]'),json('character_defaults','Character defaults'),json('rules','Rules')];