const text=(key,label,required=false)=>({key,label,type:'text',required});
const json=(key,label,empty='{}')=>({key,label,type:'json',empty});
const tags=(key,label)=>({key,label,type:'tags'});
const reference=(key,label,referenceType,required=false)=>({key,label,type:'reference',referenceType,required});
const references=(key,label,referenceType)=>({key,label,type:'references',referenceType});
const rewards=(key,label='Rewards',rewardMode='achievement')=>({key,label,type:'rewards',referenceType:'ItemDefinition',rewardMode});
export const contentConfigs={
  TagDefinition:{label:'Tag taxonomy',fields:[text('key','Namespaced tag',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},{key:'visibility',label:'Visibility',type:'select',options:['visible','hidden']},tags('aliases','Deprecated aliases'),{key:'deprecated',label:'Deprecated',type:'checkbox'},text('replacement_tag','Replacement tag'),tags('allowed_entity_types','Allowed entity types')]},
  EnvironmentalFeatureDefinition:{label:'Environmental features',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},references('location_definition_ids','Locations','LocationDefinition'),{key:'initial_damage',label:'Initial damage',type:'number'},{key:'max_damage',label:'Maximum damage',type:'number'},{key:'initial_access',label:'Initial access',type:'select',options:['open','restricted','locked']},json('initial_owner_ref','Initial owner'),{key:'hidden',label:'Hidden until discovered',type:'checkbox'},text('discovery_attribute','Discovery attribute'),{key:'discovery_difficulty',label:'Discovery difficulty',type:'number'},json('search_outputs','Search item outputs','[]'),{key:'regeneration_minutes',label:'Resource regeneration in minutes',type:'number'},json('time_effects','World-time effects','[]'),tags('tags','Tags')]},
  ItemRecipeDefinition:{label:'Item recipes',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},json('inputs','Consumed item inputs','[]'),json('outputs','Produced item outputs','[]'),json('requirements','Requirements'),text('required_feature_key','Required feature key'),{key:'time_cost',label:'Time cost in minutes',type:'number'},{key:'enabled',label:'Enabled',type:'checkbox'},tags('tags','Tags')]},
  WeatherDefinition:{label:'Regional weather',fields:[text('key','Weather key',true),text('name','Name',true),text('region_key','Region key',true),{key:'description',label:'Description',type:'textarea'},{key:'temperature',label:'Temperature',type:'number'},{key:'weight',label:'Selection weight',type:'number'},tags('active_month_keys','Active calendar months'),tags('active_phases','Active day phases'),json('transition_weights','Transition weights'),tags('tags','Tags')]},
  WorldEventDefinition:{label:'World events',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},{key:'enabled',label:'Enabled',type:'checkbox'},{key:'priority',label:'Priority',type:'number'},{key:'trigger',label:'Trigger configuration',type:'worldEventTrigger'},{key:'conditions',label:'Conditions',type:'worldEventConditions'},{key:'effects',label:'Effects',type:'worldEventEffects'},{key:'emitted_events',label:'Events emitted',type:'worldEventEmissions'},tags('tags','Tags')]},
  FactionDefinition:{label:'Factions',fields:[text('key','Faction key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('parent_faction_key','Parent faction key'),json('relationship_defaults','Relationship vector defaults'),json('state_defaults','Faction state defaults'),json('legal_config','Legal configuration'),tags('tags','Tags')]},
  FactionOperationDefinition:{label:'Faction operations',fields:[text('key','Operation key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('faction_key','Faction key',true),{key:'duration_minutes',label:'Duration in world minutes',type:'number',required:true},{key:'repeat_interval_minutes',label:'Repeat interval',type:'number'},json('conditions','Start conditions'),json('state_changes','Faction state changes'),json('reputation_changes','Reputation changes'),tags('rumor_definition_keys','Rumors created'),{key:'enabled',label:'Enabled',type:'checkbox'},tags('tags','Tags')]},
  CrimeDefinition:{label:'Crimes and law',fields:[text('key','Crime key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('jurisdiction_key','Jurisdiction faction key',true),{key:'severity',label:'Severity',type:'number',required:true},{key:'standing_delta',label:'Legal standing delta',type:'number'},{key:'report_threshold',label:'Witness report threshold',type:'number'},{key:'expires_after_minutes',label:'Expiry in world minutes',type:'number'},tags('tags','Tags')]},
  KnowledgeDefinition:{label:'Knowledge claims',fields:[text('key','Proposition key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},json('subject_ref','Subject reference'),json('canonical_value','Canonical truth'),{key:'visibility',label:'Visibility',type:'select',options:['public','discoverable','secret']},tags('tags','Tags')]},
  RumorDefinition:{label:'Rumor profiles',fields:[text('key','Rumor key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('proposition_key','Knowledge proposition key',true),json('seed_payload','Initial claim'),{key:'base_accuracy',label:'Base accuracy',type:'number'},{key:'base_strength',label:'Base strength',type:'number'},{key:'spread_interval_minutes',label:'Spread interval',type:'number'},{key:'decay_per_spread',label:'Decay per spread',type:'number'},{key:'max_spreads',label:'Maximum spreads',type:'number'},tags('tags','Tags')]},
  InteractionRuleDefinition:{label:'Interaction rules',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('action_key','Action key',true),text('label','Player label',true),{key:'priority',label:'Priority',type:'number'},{key:'enabled',label:'Enabled',type:'checkbox'},text('exclusive_group','Exclusive group'),json('required_tags','Required tags by subject'),json('any_tag_groups','Any-of tag groups','[]'),json('excluded_tags','Excluded tags by subject'),json('conditions','Additional conditions'),text('unavailable_text','Unavailable explanation'),{key:'targeting',label:'Target selection',type:'interactionTargeting'},{key:'source',label:'Source item rules',type:'interactionSource'},{key:'skill_check',label:'Skill check',type:'interactionSkillCheck'},json('preview','Interaction preview'),json('success_effects','Success effects','[]'),json('failure_effects','Failure effects','[]'),json('success_events','Success events','[]'),json('failure_events','Failure events','[]'),tags('tags','Rule tags')]},
  LocationDefinition:{label:'Locations',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('location_type','Location type',true),text('region_key','Region key'),text('parent_location_id','Parent location ID'),tags('tags','Tags'),tags('available_actions','Available actions')]},
  Connection:{label:'Connections',fields:[text('label','Label',true),reference('from_location_id','From location','LocationDefinition',true),reference('to_location_id','To location','LocationDefinition',true),{key:'travel_time',label:'Travel time',type:'number'},{key:'resource_cost',label:'Resource cost',type:'number'},{key:'one_way',label:'One way',type:'checkbox'},tags('required_tags','Required tags'),json('conditions','Conditions'),{key:'enabled',label:'Enabled',type:'checkbox'}]},
  NPCDefinition:{label:'NPCs',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('portrait_url','Portrait URL'),text('faction_key','Faction key'),tags('tags','Tags'),tags('actions','Legacy actions'),{key:'interaction_actions',label:'Interactions and services',type:'npcInteractions',referenceTypes:['DialogueGraph','ItemDefinition','SkillDefinition']},references('dialogue_graph_ids','Dialogue graphs','DialogueGraph'),json('visibility_conditions','Visibility conditions'),json('combat_profile','Combat profile')] },
  NPCInstance:{label:'NPC instances',fields:[reference('definition_id','NPC definition','NPCDefinition',true),{key:'availability',label:'Availability',type:'select',options:['available','hidden','departed']},json('personal_state','Private state'),json('public_state','Public state'),text('inventory_container_id','Inventory container ID')]},
  NPCPlacement:{label:'NPC placements',fields:[reference('npc_instance_id','NPC instance','NPCInstance',true),reference('location_id','Location','LocationDefinition',true),{key:'enabled',label:'Enabled',type:'checkbox'},json('visibility_conditions','Visibility conditions'),json('interaction_conditions','Interaction conditions'),json('schedule','Schedule')]},
  DialogueGraph:{label:'Dialogue',fields:[text('key','Stable key',true),text('name','Name',true),{key:'start_node_key',label:'Starting node',type:'dialogueStart',required:true},{key:'nodes',label:'Dialogue nodes',type:'dialogueGraph'},tags('tags','Tags')]},
  QuestDefinition:{label:'Quests',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category'),json('availability_conditions','Availability conditions'),{key:'objective_graph',label:'Objective graph',type:'questGraph'},tags('event_triggers','Event triggers'),json('completion_rules','Completion rules'),json('failure_rules','Failure rules'),json('expiration_rules','Expiration rules'),rewards('rewards','Guaranteed rewards','quest'),json('reward_selection','Reward selection'),{key:'repeatability',label:'Repeatability',type:'select',options:['never','repeatable','scheduled']},tags('tags','Tags')]},
  AchievementDefinition:{label:'Achievements',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category'),{key:'hidden',label:'Hidden until completed',type:'checkbox'},{key:'points',label:'Achievement points',type:'number'},{key:'criteria_logic',label:'Criteria logic',type:'select',options:['all','any']},json('criteria','Criteria','[]'),rewards('rewards','Rewards','achievement'),tags('tags','Tags')]},
  ItemDefinition:{label:'Items',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category',true),tags('tags','Tags'),{key:'stack_limit',label:'Stack limit',type:'number'},{key:'weight',label:'Weight',type:'number'},{key:'value',label:'Value',type:'number'},tags('equipment_slots','Equipment slots'),references('granted_ability_ids','Granted abilities','AbilityDefinition'),tags('actions','Actions'),json('requirements','Requirements'),json('modifiers','Modifiers','[]'),json('use_effects','Use effects','[]')]},
  AbilityDefinition:{label:'Abilities',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},tags('tags','Tags'),json('costs','Resource costs'),json('targeting','Targeting'),json('requirements','Requirements'),json('effects','Effects','[]'),{key:'cooldown',label:'Cooldown',type:'number'}]},
  EncounterDefinition:{label:'Encounters',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},references('location_ids','Locations','LocationDefinition'),{key:'turn_model',label:'Turn model',type:'select',options:['individual_initiative','side_based','simultaneous']},json('participant_templates','Participants','[]'),json('ai_policy','Enemy AI policy'),json('victory_conditions','Victory conditions'),rewards('rewards','Rewards','encounter'),tags('tags','Tags')]},
  AttributeDefinition:{label:'Attributes',fields:[text('key','Stable key',true),text('name','Name',true),text('category','Category'),{key:'data_type',label:'Data type',type:'select',options:['integer','decimal','boolean']},{key:'minimum',label:'Minimum',type:'number'},{key:'maximum',label:'Maximum',type:'number'},{key:'default_value',label:'Default value',type:'number',required:true},{key:'visibility',label:'Visibility',type:'select',options:['public','player','hidden']},tags('tags','Tags')]},
  SkillDefinition:{label:'Skills',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},text('category','Category'),{key:'max_rank',label:'Maximum rank',type:'number',required:true},json('requirements','Requirements'),json('training_costs','Training costs'),references('granted_ability_ids','Granted abilities','AbilityDefinition'),tags('tags','Tags')]},
  FormulaDefinition:{label:'Formulas',fields:[text('key','Stable key',true),text('name','Name',true),json('expression','Expression'),{key:'output_type',label:'Output type',type:'select',options:['integer','decimal']},tags('tags','Tags')]},
  EffectDefinition:{label:'Effects',fields:[text('key','Stable key',true),text('name','Name',true),json('effects','Effects','[]'),tags('tags','Tags')]},
  StatusDefinition:{label:'Statuses',fields:[text('key','Stable key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},{key:'stacking',label:'Stacking',type:'select',options:['replace','stack','refresh']},{key:'maximum_stacks',label:'Maximum stacks',type:'number'},{key:'duration_type',label:'Duration type',type:'select',options:['turns','time','permanent']},json('effects','Effects','[]'),tags('tags','Tags')]},
  LocalizationEntry:{label:'Localization',fields:[text('locale','Locale',true),text('key','Translation key',true),{key:'value',label:'Translated text',type:'textarea',required:true},text('context','Translator context')]},
  RuleExtensionDefinition:{label:'Rule extensions',fields:[text('key','Rule type key',true),text('name','Name',true),{key:'description',label:'Description',type:'textarea'},{key:'kind',label:'Kind',type:'select',options:['condition','effect']},tags('parameters','Parameters'),json('condition_template','Condition template'),json('effect_templates','Effect templates','[]')]},
  RuntimeModuleDefinition:{label:'Runtime modules',fields:[text('key','Module key',true),text('name','Name',true),text('title_key','Localized title key'),{key:'description',label:'Description',type:'textarea'},text('description_key','Localized description key'),text('route_slug','Route slug',true),json('sections','Page sections','[]'),tags('tags','Tags')]}
};
export const gameFields=[text('title','Game title',true),{key:'description',label:'Description',type:'textarea'},json('terminology','Terminology'),json('theme','Theme'),tags('enabled_modules','Enabled modules'),tags('header_indicators','Header indicators'),json('navigation','Navigation','[]'),json('character_defaults','Character defaults'),json('calendar','Custom calendar'),json('simulation','Living-world simulation'),json('rules','Rules')];