const adminCommands=new Set([
  'GET_OPERATIONS','GET_ADMIN_USERS','INVITE_USER','UPDATE_USER_ROLE',
  'CREATE_CHARACTER_BACKUP','RESTORE_CHARACTER_BACKUP','ROLLBACK_MIGRATION','RETRY_DEAD_LETTER',
  'CREATE_RELEASE','VALIDATE_RELEASE','PUBLISH_RELEASE','COMPARE_RELEASES','PREVIEW_MIGRATION','MIGRATE_CHARACTER',
  'CREATE_GAME','SAVE_GAME_CONFIG','CREATE_CONTENT_PACK','EXPORT_CONTENT_PACKS','IMPORT_CONTENT_PACKS','GET_STUDIO_CONTENT','PREVIEW_BULK_STUDIO_CONTENT','IMPORT_BULK_STUDIO_CONTENT','SAVE_STUDIO_CONTENT','DELETE_STUDIO_CONTENT',
  'GET_SIMULATION','CREATE_TEST_CHARACTER','SIM_MOVE_CHARACTER','SIM_GIVE_ITEM','SIM_APPLY_STATUS','SIM_SET_QUEST_STATE','SIM_START_ENCOUNTER','SIM_REPLAY_COMBAT','SIM_REPLAY_SUITE',
  'STUDIO_OVERVIEW'
]);
export function isAdminCommand(command:string){return adminCommands.has(command);}
export function canExecuteCommand(user:any,command:string){return !isAdminCommand(command)||user?.role==='admin';}