type ValueType='string'|'number'|'boolean'|'object'|'array';
type Domain='operations'|'platform'|'dialogue'|'party'|'combat'|'achievements'|'settings'|'content'|'studio'|'capabilities'|'simulation'|'runtime'|'contracts';
type Definition={name:string,domain:Domain,required?:string[],properties?:Record<string,ValueType>,description?:string};

const common:Record<string,ValueType>={characterId:'string',characterVersion:'number',combatId:'string',combatVersion:'number',questInstanceId:'string',questVersion:'number',itemId:'string',itemVersion:'number',loadoutId:'string',loadoutVersion:'number',releaseId:'string',gameId:'string',requestId:'string'};
const define=(domain:Domain,names:string[],description:string):Definition[]=>names.map(name=>({name,domain,description}));
const definitions:Definition[]=[
  ...define('contracts',['GET_COMMAND_CONTRACTS'],'Returns the authenticated command contract catalog.'),
  ...define('operations',['GET_NOTIFICATIONS','MARK_NOTIFICATION_READ','GET_OPERATIONS','GET_ADMIN_USERS','INVITE_USER','UPDATE_USER_ROLE'],'Notifications, operational data, and platform access.'),
  ...define('platform',['GET_PRESENTATION','GET_ACCOUNT','SAVE_ACCOUNT_LOCALE','GET_WORLD','GET_JOURNAL','GET_RUNTIME_MODULE'],'Runtime presentation and platform modules.'),
  ...define('dialogue',['GET_NPC_INTERACTION','EXECUTE_NPC_ACTION','START_DIALOGUE','SELECT_DIALOGUE_OPTION'],'NPC interaction and dialogue.'),
  ...define('party',['GET_PARTY','CREATE_PARTY','ADD_PARTY_MEMBER','REMOVE_PARTY_MEMBER','DISBAND_PARTY'],'Party lifecycle.'),
  ...define('combat',['GET_COMBAT','START_ENCOUNTER','SELECT_COMBAT_ACTION','COMPLETE_COMBAT'],'Combat lifecycle.'),
  ...define('achievements',['GET_ACHIEVEMENTS','CLAIM_ACHIEVEMENT_REWARD'],'Achievement progress and rewards.'),
  ...define('settings',['GET_SETTINGS','SAVE_SETTINGS','SAVE_KEY_BINDING','RESET_KEY_BINDINGS'],'Player settings and shortcuts.'),
  ...define('content',['CREATE_RELEASE','VALIDATE_RELEASE','PUBLISH_RELEASE','PREVIEW_MIGRATION','MIGRATE_CHARACTER'],'Content release lifecycle.'),
  ...define('studio',['CREATE_GAME','SAVE_GAME_CONFIG','CREATE_CONTENT_PACK','GET_STUDIO_CONTENT','SAVE_STUDIO_CONTENT','DELETE_STUDIO_CONTENT'],'Studio authoring.'),
  ...define('capabilities',['GET_CAPABILITIES','GET_CHARACTER_PROFILE','TRAIN_SKILL','SAVE_LOADOUT','ACTIVATE_LOADOUT','DELETE_LOADOUT'],'Character capabilities and loadouts.'),
  ...define('simulation',['GET_SIMULATION','CREATE_TEST_CHARACTER','SIM_MOVE_CHARACTER','SIM_GIVE_ITEM','SIM_APPLY_STATUS','SIM_SET_QUEST_STATE','SIM_START_ENCOUNTER','SIM_REPLAY_COMBAT'],'Administrative simulation.'),
  ...define('runtime',['GET_STATE','STUDIO_OVERVIEW','CREATE_CHARACTER','GET_CONTEXTUAL_ACTIONS','EXECUTE_CONTEXTUAL_ACTION','GET_INVENTORY','SPLIT_ITEM','MERGE_ITEM','TRANSFER_ITEM','BULK_TRANSFER_ITEMS','COLLECT_LOOT','GET_QUESTS','SELECT_QUEST_BRANCH','SELECT_QUEST_REWARD','ACCEPT_QUEST','ABANDON_QUEST','EQUIP_ITEM','UNEQUIP_ITEM','USE_ITEM','MOVE_TO_LOCATION'],'Core runtime orchestration.')
];

const requirements:Record<string,string[]>={
  MARK_NOTIFICATION_READ:['notificationId'],INVITE_USER:['email','role'],UPDATE_USER_ROLE:['userId','role'],SAVE_ACCOUNT_LOCALE:['locale'],GET_RUNTIME_MODULE:['moduleKey'],GET_WORLD:['characterId'],GET_JOURNAL:['characterId'],
  GET_NPC_INTERACTION:['characterId','placementId'],EXECUTE_NPC_ACTION:['characterId','placementId','actionKey'],START_DIALOGUE:['characterId','placementId','actionKey'],SELECT_DIALOGUE_OPTION:['sessionId','sessionVersion','optionKey'],
  GET_PARTY:['characterId'],CREATE_PARTY:['characterId'],ADD_PARTY_MEMBER:['characterId'],REMOVE_PARTY_MEMBER:['characterId'],DISBAND_PARTY:['characterId'],
  GET_COMBAT:['characterId'],START_ENCOUNTER:['characterId','encounterDefinitionId'],SELECT_COMBAT_ACTION:['characterId','combatId','combatVersion','targetParticipantId','abilityId'],COMPLETE_COMBAT:['characterId','combatId'],
  GET_ACHIEVEMENTS:['characterId'],CLAIM_ACHIEVEMENT_REWARD:['characterId','progressId','progressVersion'],
  SAVE_SETTINGS:['scope','values'],SAVE_KEY_BINDING:['commandId','binding'],
  CREATE_RELEASE:['gameId','version'],VALIDATE_RELEASE:['releaseId'],PUBLISH_RELEASE:['releaseId'],PREVIEW_MIGRATION:['releaseId','characterId'],MIGRATE_CHARACTER:['releaseId','characterId'],
  CREATE_GAME:['title'],SAVE_GAME_CONFIG:['gameId','values'],CREATE_CONTENT_PACK:['gameId','values'],GET_STUDIO_CONTENT:['releaseId','contentType'],SAVE_STUDIO_CONTENT:['releaseId','contentType','values'],DELETE_STUDIO_CONTENT:['releaseId','contentType','itemId'],
  GET_CAPABILITIES:['characterId'],GET_CHARACTER_PROFILE:['characterId'],TRAIN_SKILL:['characterId','skillDefinitionId'],SAVE_LOADOUT:['characterId','values'],ACTIVATE_LOADOUT:['characterId','loadoutId','loadoutVersion'],DELETE_LOADOUT:['characterId','loadoutId','loadoutVersion'],
  CREATE_TEST_CHARACTER:['gameId'],SIM_MOVE_CHARACTER:['characterId'],SIM_GIVE_ITEM:['characterId'],SIM_APPLY_STATUS:['characterId'],SIM_SET_QUEST_STATE:['characterId'],SIM_START_ENCOUNTER:['characterId'],SIM_REPLAY_COMBAT:['characterId'],
  CREATE_CHARACTER:['gameId','name'],GET_CONTEXTUAL_ACTIONS:['characterId','targetType','targetId'],EXECUTE_CONTEXTUAL_ACTION:['characterId','characterVersion','targetType','targetId','actionKey'],GET_INVENTORY:['characterId'],SPLIT_ITEM:['characterId','itemId','itemVersion'],MERGE_ITEM:['characterId'],TRANSFER_ITEM:['characterId','itemId','itemVersion'],BULK_TRANSFER_ITEMS:['characterId','items'],COLLECT_LOOT:['characterId'],GET_QUESTS:['characterId'],SELECT_QUEST_BRANCH:['characterId','questInstanceId','questVersion'],SELECT_QUEST_REWARD:['characterId','questInstanceId','questVersion'],ACCEPT_QUEST:['characterId','questDefinitionId'],ABANDON_QUEST:['characterId','questInstanceId','questVersion'],EQUIP_ITEM:['characterId','itemId','itemVersion'],UNEQUIP_ITEM:['characterId','itemId','itemVersion'],USE_ITEM:['characterId','itemId','itemVersion'],MOVE_TO_LOCATION:['characterId','characterVersion','destinationId']
};
const fieldTypes:Record<string,ValueType>={...common,notificationId:'string',locale:'string',moduleKey:'string',encounterDefinitionId:'string',targetParticipantId:'string',abilityId:'string',scope:'string',values:'object',commandId:'string',binding:'string',version:'string',title:'string',name:'string',contentVersion:'string',entityName:'string',recordId:'string',skillDefinitionId:'string',questDefinitionId:'string',destinationId:'string',placementId:'string',targetType:'string',targetId:'string',actionKey:'string',sessionId:'string',sessionVersion:'number',optionKey:'string',progressId:'string',progressVersion:'number',items:'array',releaseId:'string',contentType:'string',itemId:'string',email:'string',role:'string',userId:'string'};
const responseProfiles:Record<string,Record<string,ValueType>>={
  catalog:{version:'number',commands:'array'},access:{users:'array'},state:{games:'array',game:'object',characters:'array',character:'object',location:'object',exits:'array',npcs:'array',activity:'array'},notifications:{notifications:'array',unread:'number'},operations:{counts:'object',executionHealth:'object',events:'array',usage:'array'},presentation:{locale:'string',locales:'array',translations:'object'},account:{account:'object',locale:'string',locales:'array',translations:'object'},module:{module:'object',locale:'string',locales:'array',translations:'object'},world:{character:'object',current_location_id:'string',locations:'array',connections:'array'},journal:{character:'object',events:'array',quests:'array'},party:{character:'object',party:'object',members:'array',availableCharacters:'array'},combat:{character:'object',combat:'object',participants:'array',abilities:'array',events:'array',encounters:'array'},achievements:{character:'object',achievements:'array',summary:'object'},settings:{settings:'object',bindings:'array'},inventory:{character:'object',containers:'array',items:'array',summary:'object'},quests:{character:'object',available:'array',quests:'array'},capabilities:{character:'object',skills:'array',abilities:'array',items:'array',loadouts:'array',activeLoadout:'object'},profile:{character:'object',attributeDefinitions:'array',derivedValues:'array',effects:'array',skills:'array',equipment:'array'},simulation:{games:'array',game:'object',release:'object',characters:'array'},studio:{games:'array',releases:'array',packs:'array',characters:'array',counts:'object'},studioContent:{items:'array'},release:{release:'object',summary:'object',preview:'object',migrated:'boolean'},contextual:{character:'object',target:'object',actions:'array',outcomes:'array'},saved:{saved:'boolean'}};
const profileCommands:Record<string,string[]>={catalog:['GET_COMMAND_CONTRACTS'],state:['GET_STATE','CREATE_CHARACTER','MOVE_TO_LOCATION'],contextual:['GET_CONTEXTUAL_ACTIONS','EXECUTE_CONTEXTUAL_ACTION'],notifications:['GET_NOTIFICATIONS','MARK_NOTIFICATION_READ'],operations:['GET_OPERATIONS'],access:['GET_ADMIN_USERS','INVITE_USER','UPDATE_USER_ROLE'],presentation:['GET_PRESENTATION'],account:['GET_ACCOUNT'],module:['GET_RUNTIME_MODULE'],world:['GET_WORLD'],journal:['GET_JOURNAL'],party:['GET_PARTY','CREATE_PARTY','ADD_PARTY_MEMBER','REMOVE_PARTY_MEMBER','DISBAND_PARTY'],combat:['GET_COMBAT','START_ENCOUNTER','SELECT_COMBAT_ACTION','COMPLETE_COMBAT'],achievements:['GET_ACHIEVEMENTS','CLAIM_ACHIEVEMENT_REWARD'],settings:['GET_SETTINGS','SAVE_SETTINGS','SAVE_KEY_BINDING','RESET_KEY_BINDINGS'],inventory:['GET_INVENTORY','SPLIT_ITEM','MERGE_ITEM','TRANSFER_ITEM','BULK_TRANSFER_ITEMS','COLLECT_LOOT','EQUIP_ITEM','UNEQUIP_ITEM','USE_ITEM'],quests:['GET_QUESTS','SELECT_QUEST_BRANCH','SELECT_QUEST_REWARD','ACCEPT_QUEST','ABANDON_QUEST'],capabilities:['GET_CAPABILITIES','TRAIN_SKILL','SAVE_LOADOUT','ACTIVATE_LOADOUT','DELETE_LOADOUT'],profile:['GET_CHARACTER_PROFILE'],simulation:['GET_SIMULATION','CREATE_TEST_CHARACTER','SIM_MOVE_CHARACTER','SIM_GIVE_ITEM','SIM_APPLY_STATUS','SIM_SET_QUEST_STATE','SIM_START_ENCOUNTER','SIM_REPLAY_COMBAT'],studio:['STUDIO_OVERVIEW'],studioContent:['GET_STUDIO_CONTENT','SAVE_STUDIO_CONTENT','DELETE_STUDIO_CONTENT'],release:['CREATE_RELEASE','VALIDATE_RELEASE','PUBLISH_RELEASE','PREVIEW_MIGRATION','MIGRATE_CHARACTER'],saved:['SAVE_ACCOUNT_LOCALE','SAVE_GAME_CONFIG']};
const responseProfile=Object.fromEntries(Object.entries(profileCommands).flatMap(([profile,names])=>names.map(name=>[name,profile])));
const responseSchema=(command:string)=>{const fields=responseProfiles[responseProfile[command]];return fields?{type:'object',properties:Object.fromEntries(Object.entries(fields).map(([key,type])=>[key,{type}])),additionalProperties:true}:{type:'object',additionalProperties:true};};

export const commandContracts=Object.fromEntries(definitions.map(definition=>{const required=requirements[definition.name]||[],properties=Object.fromEntries(['command','requestId',...required].map(key=>[key,{type:key==='command'?'string':fieldTypes[key]||'string'}]));return [definition.name,{command:definition.name,domain:definition.domain,description:definition.description,request:{type:'object',required:['command',...required],properties,additionalProperties:true},response:responseSchema(definition.name)}];}));
export function getCommandContract(command:string){return commandContracts[command]||null;}
export function publicCommandContracts(){return {version:1,commands:Object.values(commandContracts)};}
function valueMatchesType(value:any,expected:ValueType){if(value===null||value===undefined)return true;if(expected==='array')return Array.isArray(value);if(expected==='object')return typeof value==='object'&&!Array.isArray(value);return typeof value===expected;}
export function validateCommandPayload(body:any){if(!body||typeof body!=='object'||Array.isArray(body))return 'Request body must be an object.';if(typeof body.command!=='string'||!body.command)return 'Command is required.';const contract:any=getCommandContract(body.command);if(!contract)return `Unknown command: ${body.command}.`;for(const key of contract.request.required){if(body[key]===undefined||body[key]===null||body[key]==='')return `${key} is required for ${body.command}.`;const expected=contract.request.properties[key]?.type;if(expected&&!valueMatchesType(body[key],expected))return `${key} must be a ${expected}.`;}return null;}
export function validateCommandResponse(command:string,body:any){const contract:any=getCommandContract(command);if(!contract)return `Unknown command: ${command}.`;if(!body||typeof body!=='object'||Array.isArray(body))return `${command} response must be an object.`;for(const [key,property] of Object.entries(contract.response.properties||{}) as any){if(body[key]!==undefined&&body[key]!==null&&!valueMatchesType(body[key],property.type))return `${command} response field ${key} must be a ${property.type}.`;}return null;}