import { createNotification } from './operations.ts';
import { validateConditionDefinition, validateEffectDefinitions, validateFormulaDefinitions } from './rules.ts';
import { validateObjectiveGraph, validateRewardSelection } from './quests.ts';
const entities = ['LocationDefinition','Connection','QuestDefinition','ItemDefinition','AbilityDefinition','EncounterDefinition','AttributeDefinition','SkillDefinition','FormulaDefinition','EffectDefinition','StatusDefinition','NPCDefinition','NPCInstance','NPCPlacement','DialogueGraph'];
async function releaseData(base44:any, release:any) { const rows:any = {}; await Promise.all(entities.map(async name => { rows[name] = await base44.asServiceRole.entities[name].filter({game_id:release.game_id,content_version:release.version},'created_date',500); })); return rows; }
async function validate(base44:any, release:any) {
  const data=await releaseData(base44,release), errors:any[]=[], warnings:any[]=[];
  const locations=new Set(data.LocationDefinition.map((x:any)=>x.id)), abilities=new Set(data.AbilityDefinition.map((x:any)=>x.id)), items=new Set(data.ItemDefinition.map((x:any)=>x.id)), statuses=new Set(data.StatusDefinition.map((x:any)=>x.key));
  const starts=data.LocationDefinition.filter((x:any)=>(x.tags||[]).includes('start'));
  if(!starts.length) errors.push({type:'missing_start',message:'The release needs a location tagged start.'});
  for(const location of data.LocationDefinition)if(location.parent_location_id&&!locations.has(location.parent_location_id))errors.push({type:'broken_location_parent',id:location.id,message:`Location ${location.name} references a missing parent.`});
  for(const link of data.Connection) { if(!locations.has(link.from_location_id)||!locations.has(link.to_location_id)) errors.push({type:'broken_connection',id:link.id,message:`Connection ${link.label} references a missing location.`}); }
  if(starts.length){const adjacency=new Map(data.LocationDefinition.map((x:any)=>[x.id,[]]));for(const link of data.Connection.filter((x:any)=>x.enabled!==false)){adjacency.get(link.from_location_id)?.push(link.to_location_id);if(!link.one_way)adjacency.get(link.to_location_id)?.push(link.from_location_id);}const reachable=new Set(starts.map((x:any)=>x.id)),queue=[...reachable];while(queue.length){for(const next of adjacency.get(queue.shift())||[])if(!reachable.has(next)){reachable.add(next);queue.push(next);}}for(const location of data.LocationDefinition)if(!reachable.has(location.id))errors.push({type:'unreachable_location',id:location.id,message:`Location ${location.name} cannot be reached from a starting location.`});}
  for(const quest of data.QuestDefinition) for(const objective of quest.objective_graph?.objectives||[]) if(objective.type==='visitLocation'&&objective.targetId&&!locations.has(objective.targetId)) errors.push({type:'broken_quest_target',id:quest.id,message:`Quest ${quest.name} references a missing location.`});
  for(const item of data.ItemDefinition) for(const id of item.granted_ability_ids||[]) if(!abilities.has(id)) errors.push({type:'broken_item_ability',id:item.id,message:`Item ${item.name} grants a missing ability.`});
  for(const skill of data.SkillDefinition) { for(const id of skill.granted_ability_ids||[]) if(!abilities.has(id)) errors.push({type:'broken_skill_ability',id:skill.id,message:`Skill ${skill.name} grants a missing ability.`}); const issue=validateConditionDefinition(skill.requirements); if(issue)errors.push({type:'invalid_skill_condition',id:skill.id,message:issue}); }
  for(const encounter of data.EncounterDefinition) { for(const id of encounter.location_ids||[]) if(!locations.has(id)) errors.push({type:'broken_encounter_location',id:encounter.id,message:`Encounter ${encounter.name} references a missing location.`}); for(const participant of encounter.participant_templates||[]) for(const id of participant.ability_ids||[]) if(!abilities.has(id)) errors.push({type:'broken_encounter_ability',id:encounter.id,message:`Encounter ${encounter.name} references a missing ability.`}); for(const reward of encounter.rewards||[])if(reward.type==='item'&&!items.has(reward.itemDefinitionId))errors.push({type:'broken_encounter_reward',id:encounter.id,message:`Encounter ${encounter.name} references a missing item reward.`}); }
  for(const link of data.Connection){const issue=validateConditionDefinition(link.conditions);if(issue)errors.push({type:'invalid_connection_condition',id:link.id,message:issue});}
  for(const quest of data.QuestDefinition){const issues=[validateConditionDefinition(quest.availability_conditions),validateConditionDefinition(quest.completion_rules),validateConditionDefinition(quest.failure_rules)].filter(Boolean);for(const issue of issues)errors.push({type:'invalid_quest_condition',id:quest.id,message:issue});const graphIssue=validateObjectiveGraph(quest.objective_graph),rewardIssue=validateRewardSelection(quest.reward_selection);if(graphIssue)errors.push({type:'invalid_quest_graph',id:quest.id,message:graphIssue});if(rewardIssue)errors.push({type:'invalid_quest_rewards',id:quest.id,message:rewardIssue});}
  for(const ability of data.AbilityDefinition){const conditionIssue=validateConditionDefinition(ability.requirements),effectIssue=validateEffectDefinitions(ability.effects);if(conditionIssue)errors.push({type:'invalid_ability_condition',id:ability.id,message:conditionIssue});if(effectIssue)errors.push({type:'invalid_ability_effect',id:ability.id,message:effectIssue});for(const effect of ability.effects||[])if(['applyStatus','removeStatus'].includes(effect.type)&&!statuses.has(effect.statusKey))errors.push({type:'broken_ability_status',id:ability.id,message:`Ability ${ability.name} references a missing status.`});}
  for(const issue of validateFormulaDefinitions(data.FormulaDefinition,data.AttributeDefinition))errors.push({type:'invalid_formula',...issue});
  for(const definition of [...data.EffectDefinition,...data.StatusDefinition]){const issue=validateEffectDefinitions(definition.effects);if(issue)errors.push({type:'invalid_effect_definition',id:definition.id,message:issue});for(const effect of definition.effects||[])if(['applyStatus','removeStatus'].includes(effect.type)&&!statuses.has(effect.statusKey))errors.push({type:'broken_effect_status',id:definition.id,message:`${definition.name} references a missing status.`});}
  const npcDefinitions=new Set(data.NPCDefinition.map((x:any)=>x.id)),npcInstances=new Set(data.NPCInstance.map((x:any)=>x.id)),dialogueGraphs=new Set(data.DialogueGraph.map((x:any)=>x.id));
  for(const npc of data.NPCDefinition){for(const id of npc.dialogue_graph_ids||[])if(!dialogueGraphs.has(id))errors.push({type:'broken_npc_dialogue',id:npc.id,message:`NPC ${npc.name} references missing dialogue.`});const issue=validateConditionDefinition(npc.visibility_conditions);if(issue)errors.push({type:'invalid_npc_condition',id:npc.id,message:issue});}
  for(const instance of data.NPCInstance)if(!npcDefinitions.has(instance.definition_id))errors.push({type:'broken_npc_instance',id:instance.id,message:'NPC instance references a missing definition.'});
  for(const placement of data.NPCPlacement){if(!npcInstances.has(placement.npc_instance_id)||!locations.has(placement.location_id))errors.push({type:'broken_npc_placement',id:placement.id,message:'NPC placement references missing content.'});for(const condition of [placement.visibility_conditions,placement.interaction_conditions]){const issue=validateConditionDefinition(condition);if(issue)errors.push({type:'invalid_npc_placement_condition',id:placement.id,message:issue});}}
  for(const graph of data.DialogueGraph){const keys=new Set((graph.nodes||[]).map((node:any)=>node.key));if(!keys.has(graph.start_node_key))errors.push({type:'broken_dialogue_start',id:graph.id,message:`Dialogue ${graph.name} has no valid start node.`});for(const node of graph.nodes||[])for(const option of node.options||[]){if(option.nextNodeKey&&!keys.has(option.nextNodeKey))errors.push({type:'broken_dialogue_path',id:graph.id,message:`Dialogue ${graph.name} contains a broken path.`});const conditionIssue=validateConditionDefinition(option.conditions),effectIssue=validateEffectDefinitions(option.effects);if(conditionIssue)errors.push({type:'invalid_dialogue_condition',id:graph.id,message:conditionIssue});if(effectIssue)errors.push({type:'invalid_dialogue_effect',id:graph.id,message:effectIssue});}}
  if(!data.EncounterDefinition.length) warnings.push({type:'no_encounters',message:'This release contains no encounters.'});
  const previous=(await base44.asServiceRole.entities.ContentRelease.filter({game_id:release.game_id,status:'published'},'-published_at',1))[0]; let diff:any=null;
  if(previous&&previous.id!==release.id){const old=await releaseData(base44,previous);diff=Object.fromEntries(entities.map(name=>[name,{previous:old[name].length,current:data[name].length,delta:data[name].length-old[name].length}]));}
  return {valid:errors.length===0,errors,warnings,counts:Object.fromEntries(entities.map(name=>[name,data[name].length])),diff,validated_at:new Date().toISOString()};
}
async function migrationPreview(base44:any,character:any,release:any){const currentLocation=await base44.asServiceRole.entities.LocationDefinition.get(character.current_location_id);const exact=await base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:release.version,key:currentLocation.key},'created_date',1);const starts=await base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:release.version,tags:{'$in':['start']}},'created_date',1);const destination=exact[0]||starts[0]||null;const items=await base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id},'-created_date',500);const quests=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,state:'ACTIVE'},'-created_date',100);return {from_version:character.content_version,to_version:release.version,location:{current:currentLocation.name,destination:destination?.name||null,destination_id:destination?.id||null,fallback:!exact[0]},grandfathered_items:items.filter((x:any)=>x.content_version!==release.version).length,grandfathered_active_quests:quests.filter((x:any)=>x.content_version!==release.version).length,can_migrate:!!destination};}
export async function handleContentCommand(base44:any,user:any,body:any){if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  if(body.command==='CREATE_RELEASE'){const version=String(body.version||'').trim();if(!version)return Response.json({error:'Version is required.'},{status:422});const duplicate=await base44.asServiceRole.entities.ContentRelease.filter({game_id:body.gameId,version},'-created_date',1);if(duplicate.length)return Response.json({error:'That content version already exists.'},{status:409});const release=await base44.asServiceRole.entities.ContentRelease.create({game_id:body.gameId,version,status:'draft',notes:String(body.notes||''),validation_summary:{}});return Response.json({release});}
  const release=await base44.asServiceRole.entities.ContentRelease.get(body.releaseId);if(body.command==='VALIDATE_RELEASE'){if(release.status==='published')return Response.json({error:'Published releases are immutable.'},{status:409});const summary=await validate(base44,release);await base44.asServiceRole.entities.ContentRelease.update(release.id,{validation_summary:summary,status:'draft'});return Response.json({summary});}
  if(body.command==='PUBLISH_RELEASE'){if(release.status==='published')return Response.json({release});const summary=await validate(base44,release);if(!summary.valid){await base44.asServiceRole.entities.ContentRelease.update(release.id,{validation_summary:summary,status:'draft'});return Response.json({error:'Release validation failed.',summary},{status:422});}const published=await base44.asServiceRole.entities.ContentRelease.update(release.id,{status:'published',published_at:new Date().toISOString(),validation_summary:summary});await base44.asServiceRole.entities.Game.update(release.game_id,{status:'published'});await createNotification(base44,user.id,'content','Content release published',`Version ${release.version} is now immutable and available to players.`,'/studio');return Response.json({release:published});}
  const character=await base44.asServiceRole.entities.Character.get(body.characterId);if(character.game_id!==release.game_id)return Response.json({error:'Character and release belong to different games.'},{status:422});if(release.status!=='published')return Response.json({error:'Characters can migrate only to published releases.'},{status:409});if(character.content_version===release.version)return Response.json({error:'Character already uses this content version.'},{status:409});const preview=await migrationPreview(base44,character,release);if(body.command==='PREVIEW_MIGRATION'){await base44.asServiceRole.entities.ContentMigration.create({game_id:character.game_id,character_id:character.id,from_version:character.content_version,to_version:release.version,strategy:'grandfather',status:'previewed',summary:preview,executed_by_user_id:user.id});return Response.json({preview});}if(body.command==='MIGRATE_CHARACTER'){if(!preview.can_migrate)return Response.json({error:'The target release has no valid destination.'},{status:422});await base44.asServiceRole.entities.CharacterSnapshot.create({game_id:character.game_id,character_id:character.id,content_version:character.content_version,reason:`Before migration to ${release.version}`,state:character,created_by_user_id:user.id});await base44.asServiceRole.entities.Character.update(character.id,{content_version:release.version,current_location_id:preview.location.destination_id,version:character.version+1});await base44.asServiceRole.entities.ContentMigration.create({game_id:character.game_id,character_id:character.id,from_version:character.content_version,to_version:release.version,strategy:'grandfather',status:'completed',summary:preview,executed_by_user_id:user.id,executed_at:new Date().toISOString()});await createNotification(base44,character.created_by_id,'migration','Character content updated',`${character.name} migrated to content version ${release.version}.`,'/');return Response.json({preview,migrated:true});}return Response.json({error:'Unknown content command.'},{status:400});}