import { createNotification } from './operations.ts';
import { validateConditionDefinition, validateEffectDefinitions, validateFormulaExpression } from './rules.ts';
const entities = ['LocationDefinition','Connection','QuestDefinition','ItemDefinition','AbilityDefinition','EncounterDefinition','AttributeDefinition','FormulaDefinition','EffectDefinition','StatusDefinition'];
async function releaseData(base44:any, release:any) { const rows:any = {}; await Promise.all(entities.map(async name => { rows[name] = await base44.asServiceRole.entities[name].filter({game_id:release.game_id,content_version:release.version},'created_date',500); })); return rows; }
async function validate(base44:any, release:any) {
  const data=await releaseData(base44,release), errors:any[]=[], warnings:any[]=[];
  const locations=new Set(data.LocationDefinition.map((x:any)=>x.id)), abilities=new Set(data.AbilityDefinition.map((x:any)=>x.id));
  if(!data.LocationDefinition.some((x:any)=>(x.tags||[]).includes('start'))) errors.push({type:'missing_start',message:'The release needs a location tagged start.'});
  for(const link of data.Connection) { if(!locations.has(link.from_location_id)||!locations.has(link.to_location_id)) errors.push({type:'broken_connection',id:link.id,message:`Connection ${link.label} references a missing location.`}); }
  for(const quest of data.QuestDefinition) for(const objective of quest.objective_graph?.objectives||[]) if(objective.type==='visitLocation'&&objective.targetId&&!locations.has(objective.targetId)) errors.push({type:'broken_quest_target',id:quest.id,message:`Quest ${quest.name} references a missing location.`});
  for(const item of data.ItemDefinition) for(const id of item.granted_ability_ids||[]) if(!abilities.has(id)) errors.push({type:'broken_item_ability',id:item.id,message:`Item ${item.name} grants a missing ability.`});
  for(const encounter of data.EncounterDefinition) { for(const id of encounter.location_ids||[]) if(!locations.has(id)) errors.push({type:'broken_encounter_location',id:encounter.id,message:`Encounter ${encounter.name} references a missing location.`}); for(const participant of encounter.participant_templates||[]) for(const id of participant.ability_ids||[]) if(!abilities.has(id)) errors.push({type:'broken_encounter_ability',id:encounter.id,message:`Encounter ${encounter.name} references a missing ability.`}); }
  for(const link of data.Connection){const issue=validateConditionDefinition(link.conditions);if(issue)errors.push({type:'invalid_connection_condition',id:link.id,message:issue});}
  for(const quest of data.QuestDefinition){const issue=validateConditionDefinition(quest.availability_conditions);if(issue)errors.push({type:'invalid_quest_condition',id:quest.id,message:issue});}
  for(const ability of data.AbilityDefinition){const conditionIssue=validateConditionDefinition(ability.requirements),effectIssue=validateEffectDefinitions(ability.effects);if(conditionIssue)errors.push({type:'invalid_ability_condition',id:ability.id,message:conditionIssue});if(effectIssue)errors.push({type:'invalid_ability_effect',id:ability.id,message:effectIssue});}
  for(const formula of data.FormulaDefinition){const issue=validateFormulaExpression(formula.expression);if(issue)errors.push({type:'invalid_formula',id:formula.id,message:issue});}
  for(const definition of [...data.EffectDefinition,...data.StatusDefinition]){const issue=validateEffectDefinitions(definition.effects);if(issue)errors.push({type:'invalid_effect_definition',id:definition.id,message:issue});}
  if(!data.EncounterDefinition.length) warnings.push({type:'no_encounters',message:'This release contains no encounters.'});
  const previous=(await base44.asServiceRole.entities.ContentRelease.filter({game_id:release.game_id,status:'published'},'-published_at',1))[0]; let diff:any=null;
  if(previous&&previous.id!==release.id){const old=await releaseData(base44,previous);diff=Object.fromEntries(entities.map(name=>[name,{previous:old[name].length,current:data[name].length,delta:data[name].length-old[name].length}]));}
  return {valid:errors.length===0,errors,warnings,counts:Object.fromEntries(entities.map(name=>[name,data[name].length])),diff,validated_at:new Date().toISOString()};
}
async function migrationPreview(base44:any,character:any,release:any){const currentLocation=await base44.asServiceRole.entities.LocationDefinition.get(character.current_location_id);const exact=await base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:release.version,key:currentLocation.key},'created_date',1);const starts=await base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:release.version,tags:{'$in':['start']}},'created_date',1);const destination=exact[0]||starts[0]||null;const items=await base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id},'-created_date',500);const quests=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,state:'ACTIVE'},'-created_date',100);return {from_version:character.content_version,to_version:release.version,location:{current:currentLocation.name,destination:destination?.name||null,destination_id:destination?.id||null,fallback:!exact[0]},grandfathered_items:items.filter((x:any)=>x.content_version!==release.version).length,grandfathered_active_quests:quests.filter((x:any)=>x.content_version!==release.version).length,can_migrate:!!destination};}
export async function handleContentCommand(base44:any,user:any,body:any){if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  if(body.command==='CREATE_RELEASE'){const version=String(body.version||'').trim();if(!version)return Response.json({error:'Version is required.'},{status:422});const duplicate=await base44.asServiceRole.entities.ContentRelease.filter({game_id:body.gameId,version},'-created_date',1);if(duplicate.length)return Response.json({error:'That content version already exists.'},{status:409});const release=await base44.asServiceRole.entities.ContentRelease.create({game_id:body.gameId,version,status:'draft',notes:String(body.notes||''),validation_summary:{}});return Response.json({release});}
  const release=await base44.asServiceRole.entities.ContentRelease.get(body.releaseId);if(body.command==='VALIDATE_RELEASE'){if(release.status==='published')return Response.json({error:'Published releases are immutable.'},{status:409});const summary=await validate(base44,release);await base44.asServiceRole.entities.ContentRelease.update(release.id,{validation_summary:summary,status:'draft'});return Response.json({summary});}
  if(body.command==='PUBLISH_RELEASE'){if(release.status==='published')return Response.json({release});const summary=await validate(base44,release);if(!summary.valid){await base44.asServiceRole.entities.ContentRelease.update(release.id,{validation_summary:summary,status:'draft'});return Response.json({error:'Release validation failed.',summary},{status:422});}const published=await base44.asServiceRole.entities.ContentRelease.update(release.id,{status:'published',published_at:new Date().toISOString(),validation_summary:summary});await base44.asServiceRole.entities.Game.update(release.game_id,{status:'published'});await createNotification(base44,user.id,'content','Content release published',`Version ${release.version} is now immutable and available to players.`,'/studio');return Response.json({release:published});}
  const character=await base44.asServiceRole.entities.Character.get(body.characterId);if(character.game_id!==release.game_id)return Response.json({error:'Character and release belong to different games.'},{status:422});if(release.status!=='published')return Response.json({error:'Characters can migrate only to published releases.'},{status:409});if(character.content_version===release.version)return Response.json({error:'Character already uses this content version.'},{status:409});const preview=await migrationPreview(base44,character,release);if(body.command==='PREVIEW_MIGRATION'){await base44.asServiceRole.entities.ContentMigration.create({game_id:character.game_id,character_id:character.id,from_version:character.content_version,to_version:release.version,strategy:'grandfather',status:'previewed',summary:preview,executed_by_user_id:user.id});return Response.json({preview});}if(body.command==='MIGRATE_CHARACTER'){if(!preview.can_migrate)return Response.json({error:'The target release has no valid destination.'},{status:422});await base44.asServiceRole.entities.CharacterSnapshot.create({game_id:character.game_id,character_id:character.id,content_version:character.content_version,reason:`Before migration to ${release.version}`,state:character,created_by_user_id:user.id});await base44.asServiceRole.entities.Character.update(character.id,{content_version:release.version,current_location_id:preview.location.destination_id,version:character.version+1});await base44.asServiceRole.entities.ContentMigration.create({game_id:character.game_id,character_id:character.id,from_version:character.content_version,to_version:release.version,strategy:'grandfather',status:'completed',summary:preview,executed_by_user_id:user.id,executed_at:new Date().toISOString()});await createNotification(base44,character.created_by_id,'migration','Character content updated',`${character.name} migrated to content version ${release.version}.`,'/');return Response.json({preview,migrated:true});}return Response.json({error:'Unknown content command.'},{status:400});}