import { contentDefinitionTypes, resolveContentPackLayers } from './contentPacks.ts';
import { contentIdentity, makeContentRef } from './contentSchemaRegistry.ts';
import { filterAll } from './entityPagination.ts';
const reserved=new Set(['id','created_date','updated_date','created_by_id','is_sample','revision','content_ref']);
const clean=(row:any)=>Object.fromEntries(Object.entries(row||{}).filter(([key])=>!reserved.has(key)));
async function sha256(value:any){const bytes=new TextEncoder().encode(JSON.stringify(value)),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export async function assignContentPack(base44:any,release:any,type:string,row:any,requestedPackId?:string){const existing=(await base44.asServiceRole.entities.ContentPackEntry.filter({release_id:release.id,content_type:type,record_id:row.id},'-updated_date',1))[0],packId=requestedPackId||existing?.pack_id||(release.content_pack_ids||[])[0];if(!packId)throw new Error('The release has no content pack.');if(!(release.content_pack_ids||[]).includes(packId))throw new Error('The selected content pack is not part of this release.');const key=contentIdentity(type,row),ref=makeContentRef(release.game_id,type,key),values={game_id:release.game_id,release_id:release.id,pack_id:packId,content_version:release.version,content_type:type,content_key:key,record_id:row.id,content_ref:ref};return existing?await base44.asServiceRole.entities.ContentPackEntry.update(existing.id,values):await base44.asServiceRole.entities.ContentPackEntry.create(values);}
export async function recordContentChange(base44:any,user:any,release:any,operation:string,type:string,row:any,before:any,packId?:string,operationId?:string){const key=contentIdentity(type,row||before),entry={game_id:release.game_id,release_id:release.id,workspace_revision:Number(release.revision||1),operation_id:operationId||crypto.randomUUID(),actor_user_id:user.id,operation,content_type:type,content_key:key,record_id:row?.id||before?.id,pack_id:packId,before:before?clean(before):undefined,after:row?clean(row):undefined,occurred_at:new Date().toISOString()};return await base44.asServiceRole.entities.ContentChangeSet.create(entry);}
export async function effectiveContentForType(base44:any,release:any,type:string){const layers=await resolveContentPackLayers(base44,release.game_id,release.content_pack_ids||[]),rank=new Map(layers.map((pack:any,index:number)=>[pack.id,index])),[records,entries]=await Promise.all([filterAll(base44.asServiceRole.entities[type],{game_id:release.game_id,content_version:release.version},'created_date'),filterAll(base44.asServiceRole.entities.ContentPackEntry,{release_id:release.id,content_type:type},'created_date')]),entryByRecord=new Map(entries.map((entry:any)=>[entry.record_id,entry])),effective=new Map();for(const record of records){const entry:any=entryByRecord.get(record.id),packId=entry?.pack_id||layers[0]?.id,layer=rank.get(packId)??0,key=contentIdentity(type,record),current:any=effective.get(key);if(!current||layer>=current.layer)effective.set(key,{record,pack_id:packId,layer});}return [...effective.values()].sort((a:any,b:any)=>String(contentIdentity(type,a.record)).localeCompare(String(contentIdentity(type,b.record))));}
export async function compilePublishedSnapshot(base44:any,release:any){const compiledAt=new Date().toISOString(),snapshotRevision=Number(release.revision||1),rows:any[]=[];for(const type of contentDefinitionTypes){const effective=await effectiveContentForType(base44,release,type);for(const item of effective){const payload=clean(item.record),key=contentIdentity(type,item.record);rows.push({game_id:release.game_id,release_id:release.id,content_version:release.version,snapshot_revision:snapshotRevision,content_type:type,content_key:key,pack_id:item.pack_id,content_ref:makeContentRef(release.game_id,type,key),payload,payload_hash:await sha256(payload),compiled_at:compiledAt});}}await base44.asServiceRole.entities.PublishedContentSnapshot.deleteMany({release_id:release.id});for(let index=0;index<rows.length;index+=500)await base44.asServiceRole.entities.PublishedContentSnapshot.bulkCreate(rows.slice(index,index+500));return {revision:snapshotRevision,records:rows.length,compiled_at:compiledAt,hash:await sha256(rows.map(row=>row.payload_hash))};}