import { contentDefinitionTypes } from './contentPacks.ts';
import { contentIdentity, extractRegisteredReferences, makeContentRef } from './contentSchemaRegistry.ts';
import { filterAll } from './entityPagination.ts';
const knownNestedRefs:Record<string,[string,string]>={statusKey:['StatusDefinition','key'],factKey:['StoryFactDefinition','key'],itemDefinitionId:['ItemDefinition','id'],item_definition_id:['ItemDefinition','id'],abilityId:['AbilityDefinition','id'],ability_id:['AbilityDefinition','id']};
function nested(value:any,path='',out:any[]=[]){if(Array.isArray(value)){value.forEach((item,index)=>nested(item,`${path}[${index}]`,out));return out;}if(!value||typeof value!=='object')return out;for(const [key,item] of Object.entries(value)){const next=path?`${path}.${key}`:key,rule=knownNestedRefs[key];if(rule&&typeof item==='string')out.push({target_type:rule[0],storage:rule[1],raw:item,field_path:next});nested(item,next,out);}return out;}
function dynamic(type:string,row:any){const refs:any[]=[];if(type==='QuestDefinition')for(const [index,item] of (row.objective_graph?.objectives||[]).entries())if(item.type==='visitLocation'&&item.targetId)refs.push({target_type:'LocationDefinition',storage:'id',raw:item.targetId,field_path:`objective_graph.objectives[${index}].targetId`});if(type==='AchievementDefinition')for(const [index,item] of (row.criteria||[]).entries()){const target:any={quest_completed:'QuestDefinition',item_quantity:'ItemDefinition',skill_rank:'SkillDefinition'}[item.type];if(target&&item.target_key)refs.push({target_type:target,storage:'key',raw:item.target_key,field_path:`criteria[${index}].target_key`});}return refs;}
export async function rebuildContentDependencyIndex(base44:any,release:any){const data:any={};await Promise.all(contentDefinitionTypes.map(async type=>{data[type]=await filterAll(base44.asServiceRole.entities[type],{game_id:release.game_id,content_version:release.version},'created_date');}));const byId=new Map(),byKey=new Map();for(const type of contentDefinitionTypes)for(const row of data[type]){byId.set(`${type}:${row.id}`,row);const key=contentIdentity(type,row);if(key)byKey.set(`${type}:${key}`,row);}const edges:any[]=[],seen=new Set<string>();for(const type of contentDefinitionTypes)for(const row of data[type]){const sourceKey=contentIdentity(type,row);if(!sourceKey)continue;const sourceRef=makeContentRef(release.game_id,type,sourceKey),references=[...extractRegisteredReferences(type,row),...dynamic(type,row),...nested(row)];for(const reference of references){const target=reference.storage==='id'?byId.get(`${reference.target_type}:${reference.raw}`):byKey.get(`${reference.target_type}:${reference.raw}`),targetKey=target?contentIdentity(reference.target_type,target):`unresolved:${reference.raw}`,targetRef=makeContentRef(release.game_id,reference.target_type,targetKey),signature=`${sourceRef.uri}|${reference.field_path}|${targetRef.uri}`;if(seen.has(signature))continue;seen.add(signature);edges.push({game_id:release.game_id,release_id:release.id,content_version:release.version,index_revision:Number(release.revision||1),source_type:type,source_key:sourceKey,source_record_id:row.id,source_uri:sourceRef.uri,source_ref:sourceRef,target_type:reference.target_type,target_key:targetKey,target_record_id:target?.id,target_uri:targetRef.uri,target_ref:targetRef,field_path:reference.field_path,storage:reference.storage,resolved:!!target});}}
  await base44.asServiceRole.entities.ContentDependency.deleteMany({release_id:release.id,index_revision:Number(release.revision||1)});for(let index=0;index<edges.length;index+=500)await base44.asServiceRole.entities.ContentDependency.bulkCreate(edges.slice(index,index+500));await base44.asServiceRole.entities.ContentDependency.deleteMany({release_id:release.id,index_revision:{'$ne':Number(release.revision||1)}});return {revision:Number(release.revision||1),edges:edges.length,resolved:edges.filter(edge=>edge.resolved).length,unresolved:edges.filter(edge=>!edge.resolved).length};
}
export async function getContentDependencies(base44:any,release:any,ref:any=null){const base={release_id:release.id,index_revision:Number(release.dependency_index_revision||release.revision||1)};if(!ref){const edges=await filterAll(base44.asServiceRole.entities.ContentDependency,base,'source_uri');return {content_ref:null,edges,inbound:[],outbound:[],index_revision:base.index_revision};}const canonical=makeContentRef(release.game_id,ref.content_type,ref.key);const [inbound,outbound]=await Promise.all([filterAll(base44.asServiceRole.entities.ContentDependency,{...base,target_uri:canonical.uri},'source_uri'),filterAll(base44.asServiceRole.entities.ContentDependency,{...base,source_uri:canonical.uri},'target_uri')]);return {content_ref:canonical,inbound,outbound,index_revision:base.index_revision};}