import { contentDefinitionTypes } from './contentPacks.ts';
const defaults:Record<string,Record<string,any>>={TagDefinition:{visibility:'visible',deprecated:false},EnvironmentalFeatureDefinition:{initial_damage:0,max_damage:100,initial_access:'open',hidden:false,discovery_attribute:'perception',discovery_difficulty:10},ItemRecipeDefinition:{time_cost:0,enabled:true},WorldEventDefinition:{enabled:true,priority:0},FactionOperationDefinition:{enabled:true},StoryletDefinition:{trigger_type:'event',priority:0,once_per_character:false,cooldown_minutes:0,enabled:true},InteractionRuleDefinition:{priority:0,enabled:true},Connection:{travel_time:0,resource_cost:0,one_way:false,enabled:true},NPCInstance:{availability:'available'},NPCPlacement:{enabled:true},QuestDefinition:{repeatability:'never',visibility:'visible'},AchievementDefinition:{hidden:false,points:0,criteria_logic:'all'}};
const refs:Record<string,any[]>={
  TagDefinition:[['replacement_tag','TagDefinition','key']],EnvironmentalFeatureDefinition:[['location_definition_ids[]','LocationDefinition','id'],['search_outputs[].item_definition_id','ItemDefinition','id']],ItemRecipeDefinition:[['inputs[].item_definition_id','ItemDefinition','id'],['outputs[].item_definition_id','ItemDefinition','id'],['required_feature_key','EnvironmentalFeatureDefinition','key']],WeatherDefinition:[['transition_weights.$keys','WeatherDefinition','key']],FactionDefinition:[['parent_faction_key','FactionDefinition','key']],FactionOperationDefinition:[['faction_key','FactionDefinition','key'],['rumor_definition_keys[]','RumorDefinition','key']],CrimeDefinition:[['jurisdiction_key','FactionDefinition','key']],RumorDefinition:[['proposition_key','KnowledgeDefinition','key']],LocationDefinition:[['parent_location_id','LocationDefinition','id']],Connection:[['from_location_id','LocationDefinition','id'],['to_location_id','LocationDefinition','id']],ItemDefinition:[['granted_ability_ids[]','AbilityDefinition','id']],SkillDefinition:[['granted_ability_ids[]','AbilityDefinition','id']],EncounterDefinition:[['location_ids[]','LocationDefinition','id'],['participant_templates[].ability_ids[]','AbilityDefinition','id']],NPCDefinition:[['faction_key','FactionDefinition','key'],['dialogue_graph_ids[]','DialogueGraph','id'],['interaction_actions[].dialogue_graph_id','DialogueGraph','id'],['interaction_actions[].service.item_definition_id','ItemDefinition','id'],['interaction_actions[].service.skill_definition_id','SkillDefinition','id']],NPCInstance:[['definition_id','NPCDefinition','id']],NPCPlacement:[['npc_instance_id','NPCInstance','id'],['location_id','LocationDefinition','id'],['schedule.entries[].location_id','LocationDefinition','id']],DialogueGraph:[['nodes[].options[].skill_check.attribute_id','AttributeDefinition','key']]
};
export const contentSchemaRegistry=Object.fromEntries(contentDefinitionTypes.map(type=>[type,{content_type:type,identity_fields:type==='LocalizationEntry'?['locale','key']:['key'],defaults:defaults[type]||{},references:(refs[type]||[]).map(([path,target_type,storage])=>({path,target_type,storage}))}]));
export function contentIdentity(type:string,row:any){if(type==='LocalizationEntry')return row?.locale&&row?.key?`${row.locale}:${row.key}`:'';return String(row?.key||'');}
export function ensureContentIdentity(type:string,values:any,current:any=null){if(contentIdentity(type,values))return values;if(current&&contentIdentity(type,current))return {...values,key:current.key};return {...values,key:`${type.replace(/Definition$/,'').replace(/([a-z])([A-Z])/g,'$1-$2').toLowerCase()}-${crypto.randomUUID()}`};}
export function makeContentRef(gameId:string,type:string,key:string){const normalized=String(key||'').trim();return {game_id:gameId,content_type:type,key:normalized,uri:`content://${encodeURIComponent(gameId)}/${encodeURIComponent(type)}/${encodeURIComponent(normalized)}`};}
function atPath(root:any,path:string){let nodes=[{value:root,path:''}];for(const segment of path.split('.')){if(segment==='$keys'){nodes=nodes.flatMap(node=>Object.keys(node.value||{}).map(key=>({value:key,path:`${node.path}.${key}`})));continue;}const many=segment.endsWith('[]'),key=many?segment.slice(0,-2):segment;nodes=nodes.flatMap(node=>{const value=node.value?.[key],nextPath=node.path?`${node.path}.${key}`:key;return many?(Array.isArray(value)?value.map((entry,index)=>({value:entry,path:`${nextPath}[${index}]`})) :[]):[{value,path:nextPath}]});}return nodes.filter(node=>node.value!==undefined&&node.value!==null&&node.value!=='');}
export function extractRegisteredReferences(type:string,row:any){return (contentSchemaRegistry[type]?.references||[]).flatMap((rule:any)=>atPath(row,rule.path).map(node=>({target_type:rule.target_type,storage:rule.storage,raw:String(node.value),field_path:node.path})));}
export function publicContentSchemaRegistry(){return {version:1,content_ref:{fields:['game_id','content_type','key'],uri:'content://{game_id}/{content_type}/{key}',release_independent:true},schemas:contentSchemaRegistry};}