import { contentDefinitionTypes } from './contentPacks.ts';
import { rebuildContentDependencyIndex } from './contentDependencies.ts';
import { ensureContentIdentity } from './contentSchemaRegistry.ts';
import { filterAll } from './entityPagination.ts';
const reserved=new Set(['id','created_date','updated_date','created_by_id','is_sample']);
const clean=(row:any)=>Object.fromEntries(Object.entries(row||{}).filter(([key])=>!reserved.has(key)));
const unique=(value:string,used:Set<string>)=>{let candidate=value,index=2;while(used.has(candidate))candidate=`${value}-${index++}`;used.add(candidate);return candidate;};
const remap=(value:any,ids:Map<string,string>):any=>typeof value==='string'?(ids.get(value)||value):Array.isArray(value)?value.map(item=>remap(item,ids)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,remap(item,ids)])):value;
export async function exportContentBundle(base44:any,gameId:string){
  const [game,packs,releases]=await Promise.all([base44.asServiceRole.entities.Game.get(gameId),filterAll(base44.asServiceRole.entities.ContentPack,{game_id:gameId},'created_date'),filterAll(base44.asServiceRole.entities.ContentRelease,{game_id:gameId},'created_date')]),versions=[...new Set(releases.map((row:any)=>row.version))],content=[];
  for(const version of versions){const records:any={};await Promise.all(contentDefinitionTypes.map(async type=>{const rows=await filterAll(base44.asServiceRole.entities[type],{game_id:gameId,content_version:version},'created_date');records[type]=rows.map((row:any)=>({source_id:row.id,data:clean(row)}));}));content.push({source_version:version,records});}
  return {manifest:{format:'base44-rpg-content-bundle',schema_version:1,exported_at:new Date().toISOString(),source_game:{id:game.id,key:game.key,title:game.title},pack_count:packs.length,release_count:releases.length,content_types:contentDefinitionTypes},packs:packs.map((row:any)=>({source_id:row.id,data:clean(row)})),releases:releases.map((row:any)=>({source_id:row.id,data:clean(row)})),content};
}
export async function importContentBundle(base44:any,gameId:string,bundle:any){
  if(bundle?.manifest?.format!=='base44-rpg-content-bundle'||bundle.manifest.schema_version!==1||!Array.isArray(bundle.packs)||!Array.isArray(bundle.releases)||!Array.isArray(bundle.content))throw new Error('The selected file is not a supported content bundle.');
  const existingPacks=await filterAll(base44.asServiceRole.entities.ContentPack,{game_id:gameId},'created_date'),existingReleases=await filterAll(base44.asServiceRole.entities.ContentRelease,{game_id:gameId},'created_date'),usedKeys=new Set(existingPacks.map((row:any)=>row.key)),usedVersions=new Set(existingReleases.map((row:any)=>row.version)),packIds=new Map<string,string>(),createdPacks:any[]=[],createdReleases:any[]=[],createdByType:any={};
  try{
    for(const source of bundle.packs){if(!source.source_id||!source.data?.key)throw new Error('A content-pack manifest is incomplete.');const data=source.data,key=unique(String(data.key),usedKeys),version=key===data.key?String(data.version):`${data.version}-imported`;const created=await base44.asServiceRole.entities.ContentPack.create({...clean(data),game_id:gameId,key,version,status:'draft',dependency_pack_ids:[]});packIds.set(source.source_id,created.id);createdPacks.push(created);}
    for(let index=0;index<bundle.packs.length;index++){const source=bundle.packs[index],dependencies=(source.data.dependency_pack_ids||[]).map((id:string)=>packIds.get(id)).filter(Boolean);if(dependencies.length)createdPacks[index]=await base44.asServiceRole.entities.ContentPack.update(createdPacks[index].id,{dependency_pack_ids:dependencies});}
    for(const source of bundle.releases){if(!source.source_id||!source.data?.version)throw new Error('A release manifest is incomplete.');const importedVersion=unique(usedVersions.has(source.data.version)?`${source.data.version}-imported`:String(source.data.version),usedVersions),release=await base44.asServiceRole.entities.ContentRelease.create({game_id:gameId,version:importedVersion,content_pack_ids:(source.data.content_pack_ids||[]).map((id:string)=>packIds.get(id)).filter(Boolean),status:'draft',revision:1,dependency_index_revision:1,notes:`Imported draft copy of ${source.data.version}. ${source.data.notes||''}`.trim(),validation_summary:{}});createdReleases.push(release);const snapshot=bundle.content.find((entry:any)=>entry.source_version===source.data.version),ids=new Map<string,string>(),createdRows:any={};
      for(const type of contentDefinitionTypes){const rows=snapshot?.records?.[type]||[];if(!Array.isArray(rows))throw new Error(`${type} records must be an array.`);if(!rows.length)continue;const payloads=rows.map((row:any)=>({...ensureContentIdentity(type,clean(row.data)),game_id:gameId,content_version:importedVersion})),created:any[]=[];for(let offset=0;offset<payloads.length;offset+=500)created.push(...await base44.asServiceRole.entities[type].bulkCreate(payloads.slice(offset,offset+500)));createdRows[type]=created;createdByType[type]=[...(createdByType[type]||[]),...created];rows.forEach((row:any,rowIndex:number)=>ids.set(row.source_id,created[rowIndex].id));}
      for(const [type,rows] of Object.entries(createdRows) as any){if(rows.length)await base44.asServiceRole.entities[type].bulkUpdate(rows.map((row:any)=>({id:row.id,...remap(clean(row),ids),game_id:gameId,content_version:importedVersion})));}
      const index=await rebuildContentDependencyIndex(base44,release);createdReleases[createdReleases.length-1]=await base44.asServiceRole.entities.ContentRelease.update(release.id,{dependency_index_revision:index.revision});
    }
    return {packs:createdPacks,releases:createdReleases,summary:{packs:createdPacks.length,releases:createdReleases.length,records:Object.values(createdByType).reduce((sum:number,rows:any)=>sum+rows.length,0)}};
  }catch(error){for(const [type,rows] of Object.entries(createdByType) as any)if(rows.length)await base44.asServiceRole.entities[type].deleteMany({id:{'$in':rows.map((row:any)=>row.id)}});if(createdReleases.length)await base44.asServiceRole.entities.ContentRelease.deleteMany({id:{'$in':createdReleases.map(row=>row.id)}});if(createdPacks.length)await base44.asServiceRole.entities.ContentPack.deleteMany({id:{'$in':createdPacks.map(row=>row.id)}});throw error;}
}