import { evaluateCondition, resolveCharacterEffects } from './rules.ts';
import { publishQuestEvent } from './quests.ts';
import { describeNpcService, executeNpcService } from './npcServices.ts';

const legacyLabel=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
function actionDefinitions(definition:any){
  const structured=definition.interaction_actions||[];
  const legacy=(definition.actions||[]).map((type:string)=>({key:type,label:legacyLabel(type),type:type==='talk'?'talk':'inspect',dialogue_graph_id:type==='talk'?definition.dialogue_graph_ids?.[0]:undefined}));
  return [...new Map([...legacy,...structured].map((action:any)=>[action.key,action])).values()];
}
async function relationshipFor(base44:any,character:any,npcInstanceId:string){const rows=await base44.asServiceRole.entities.Relationship.filter({character_id:character.id,npc_instance_id:npcInstanceId},'-created_date',1);return rows[0]||null;}
async function availableActions(base44:any,character:any,definition:any,relationship:any){const rows:any[]=[];for(const action of actionDefinitions(definition))if(await evaluateCondition(base44,{character,relationship},action.conditions))rows.push({key:action.key,label:action.label,type:action.type,description:action.description||'',dialogue_graph_id:action.dialogue_graph_id||null,service:action.type==='service'?await describeNpcService(base44,character,action.service):null});return rows;}
async function loadNpcContext(base44:any,character:any,placementId:string){
  const placement=await base44.asServiceRole.entities.NPCPlacement.get(placementId);
  if(placement.location_id!==character.current_location_id||placement.game_id!==character.game_id||placement.content_version!==character.content_version||!placement.enabled)throw new Error('This NPC is not available at the current location.');
  const instance=await base44.asServiceRole.entities.NPCInstance.get(placement.npc_instance_id),definition=await base44.asServiceRole.entities.NPCDefinition.get(instance.definition_id),relationship=await relationshipFor(base44,character,instance.id);
  if(instance.availability!=='available'||!await evaluateCondition(base44,{character,relationship},definition.visibility_conditions)||!await evaluateCondition(base44,{character,relationship},placement.visibility_conditions))throw new Error('This NPC is not currently visible.');
  const canInteract=await evaluateCondition(base44,{character,relationship},placement.interaction_conditions),actions=canInteract?await availableActions(base44,character,definition,relationship):[];
  return {placement,instance,definition,relationship,actions,canInteract};
}
function interactionPayload(context:any,character:any){return {character_version:character.version,placement:{id:context.placement.id},npc:{instance:{id:context.instance.id,public_state:context.instance.public_state||{}},definition:{id:context.definition.id,name:context.definition.name,description:context.definition.description||'',portrait_url:context.definition.portrait_url||'',faction_key:context.definition.faction_key||'',tags:context.definition.tags||[]}},relationship:context.relationship?{values:context.relationship.values||{},tags:context.relationship.tags||[],version:context.relationship.version}:null,actions:context.actions};}
async function present(base44:any,session:any,character:any){const [graph,instance]=await Promise.all([base44.asServiceRole.entities.DialogueGraph.get(session.dialogue_graph_id),base44.asServiceRole.entities.NPCInstance.get(session.npc_instance_id)]);const definition=await base44.asServiceRole.entities.NPCDefinition.get(instance.definition_id),relationship=await relationshipFor(base44,character,instance.id);const node=(graph.nodes||[]).find((item:any)=>item.key===session.current_node_key)||null,options:any[]=[];for(const option of node?.options||[])if(await evaluateCondition(base44,{character,relationship},option.conditions))options.push({key:option.key,label:option.label});return {session,npc:{instance:{id:instance.id,public_state:instance.public_state||{}},definition},relationship,graph:{id:graph.id,name:graph.name},node:node?{key:node.key,text:node.text,type:node.type||'text'}:null,options};}
export async function loadVisibleNpcs(base44:any,character:any){const placements=await base44.asServiceRole.entities.NPCPlacement.filter({game_id:character.game_id,content_version:character.content_version,location_id:character.current_location_id,enabled:true},'created_date',100),visible:any[]=[];for(const placement of placements){try{const context=await loadNpcContext(base44,character,placement.id);visible.push({placement,instance:context.instance,definition:context.definition,can_interact:context.canInteract,actions:context.actions});}catch{continue;}}return visible;}
async function updateRelationship(base44:any,character:any,npcInstanceId:string,effects:any[]){for(const effect of effects.filter((item:any)=>item.type==='relationshipChange')){const rows=await base44.asServiceRole.entities.Relationship.filter({character_id:character.id,npc_instance_id:npcInstanceId},'-created_date',1),current=rows[0],values={...(current?.values||{})},key=effect.relationshipKey||'affinity';values[key]=(values[key]||0)+Number(effect.amount||0);if(current)await base44.asServiceRole.entities.Relationship.update(current.id,{values,version:current.version+1});else await base44.asServiceRole.entities.Relationship.create({game_id:character.game_id,content_version:character.content_version,character_id:character.id,npc_instance_id:npcInstanceId,values,tags:[],version:1});}}
export async function handleDialogueCommand(base44:any,user:any,body:any,requestId:string){
  if(body.command==='GET_NPC_INTERACTION'){const character=await base44.entities.Character.get(body.characterId),context=await loadNpcContext(base44,character,body.placementId);return Response.json({interaction:interactionPayload(context,character)});}
  if(body.command==='EXECUTE_NPC_ACTION'){
    let character=await base44.entities.Character.get(body.characterId);if(character.version!==body.characterVersion)return Response.json({error:'Character state changed. Refresh and try again.'},{status:409});const context=await loadNpcContext(base44,character,body.placementId),action=actionDefinitions(context.definition).find((item:any)=>item.key===body.actionKey);
    if(!action||!context.actions.some((item:any)=>item.key===action.key)||action.type!=='service')return Response.json({error:'That NPC action is not available.'},{status:422});const duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);
    if(!duplicate.length){const effects=action.effects||[],result=await executeNpcService(base44,character,action);if(result.error)return Response.json({error:result.error},{status:422});character=result.character;await updateRelationship(base44,character,context.instance.id,effects);await publishQuestEvent(base44,character,'npc.interaction.completed','npc',context.instance.id,requestId,{npc_definition_id:context.definition.id,npc_instance_id:context.instance.id,action_key:action.key,service_kind:action.service?.kind||'custom'});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{npc_instance_id:context.instance.id,action_key:action.key,service_kind:action.service?.kind||'custom',outcomes:result.outcomes},occurred_at:new Date().toISOString()});}
    const refreshed=await loadNpcContext(base44,character,body.placementId);return Response.json({interaction:interactionPayload(refreshed,character)});
  }
  if(body.command==='START_DIALOGUE'){
    const character=await base44.entities.Character.get(body.characterId),context=await loadNpcContext(base44,character,body.placementId),action=body.actionKey?actionDefinitions(context.definition).find((item:any)=>item.key===body.actionKey):actionDefinitions(context.definition).find((item:any)=>item.type==='talk');if(!context.canInteract||!action||action.type!=='talk'||!context.actions.some((item:any)=>item.key===action.key))return Response.json({error:'This NPC is not available for conversation.'},{status:422});const graphId=action.dialogue_graph_id||body.dialogueGraphId||context.definition.dialogue_graph_ids?.[0];if(!graphId||!(context.definition.dialogue_graph_ids||[]).includes(graphId))return Response.json({error:'No valid dialogue is configured for this NPC.'},{status:422});const graph=await base44.asServiceRole.entities.DialogueGraph.get(graphId);if(graph.game_id!==character.game_id||graph.content_version!==character.content_version)return Response.json({error:'Dialogue content is not valid for this character.'},{status:422});const session=await base44.asServiceRole.entities.DialogueSession.create({game_id:character.game_id,content_version:character.content_version,character_id:character.id,npc_instance_id:context.instance.id,dialogue_graph_id:graph.id,current_node_key:graph.start_node_key,state:'ACTIVE',variables:{},version:1});await publishQuestEvent(base44,character,'npc.interaction.started','dialogue',session.id,requestId,{npc_definition_id:context.definition.id,npc_instance_id:context.instance.id});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{dialogue_session_id:session.id,npc_instance_id:context.instance.id},occurred_at:new Date().toISOString()});return Response.json({dialogue:await present(base44,session,character)});
  }
  const original=await base44.asServiceRole.entities.DialogueSession.get(body.sessionId),character=await base44.entities.Character.get(original.character_id),duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);if(duplicate.length){const latest=await base44.asServiceRole.entities.DialogueSession.get(original.id);return Response.json({dialogue:await present(base44,latest,character)});}if(original.state!=='ACTIVE'||original.version!==body.sessionVersion)return Response.json({error:'Dialogue state changed. Refresh and try again.'},{status:409});const graph=await base44.asServiceRole.entities.DialogueGraph.get(original.dialogue_graph_id),node=(graph.nodes||[]).find((item:any)=>item.key===original.current_node_key),option=(node?.options||[]).find((item:any)=>item.key===body.optionKey),relationship=await relationshipFor(base44,character,original.npc_instance_id);if(!option||!await evaluateCondition(base44,{character,relationship},option.conditions))return Response.json({error:'That dialogue option is not available.'},{status:422});const effects=option.effects||[],characterEffects=effects.filter((item:any)=>item.type!=='relationshipChange');let currentCharacter=character;if(characterEffects.length){const resolved=await resolveCharacterEffects(base44,character,characterEffects);currentCharacter=await base44.entities.Character.update(character.id,{...resolved.patch,version:character.version+1});}await updateRelationship(base44,currentCharacter,original.npc_instance_id,effects);const completed=!option.nextNodeKey,nextKey=option.nextNodeKey||original.current_node_key,session=await base44.asServiceRole.entities.DialogueSession.update(original.id,{current_node_key:nextKey,state:completed?'COMPLETED':'ACTIVE',completed_at:completed?new Date().toISOString():undefined,version:original.version+1}),npcInstance=await base44.asServiceRole.entities.NPCInstance.get(original.npc_instance_id),npcDefinition=await base44.asServiceRole.entities.NPCDefinition.get(npcInstance.definition_id);await publishQuestEvent(base44,currentCharacter,'dialogue.option.selected','dialogue',session.id,requestId,{node_key:node.key,option_key:option.key,completed,npc_definition_id:npcDefinition.id,npc_instance_id:npcInstance.id});if(completed)await publishQuestEvent(base44,currentCharacter,'npc.interaction.completed','dialogue',session.id,`${requestId}:completed`,{npc_definition_id:npcDefinition.id,npc_instance_id:npcInstance.id});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{dialogue_session_id:session.id,node_key:node.key,option_key:option.key},occurred_at:new Date().toISOString()});return Response.json({dialogue:await present(base44,session,currentCharacter)});
}