import { recordCommandFailure,recordCommandRecovery } from './reliability.ts';
const mutations=new Set(['GET_QUESTS','ADVANCE_WORLD_TIME','EXECUTE_CONTEXTUAL_ACTION','SEARCH_LOCATION','SEARCH_FEATURE','CRAFT_RECIPE','INVITE_USER','UPDATE_USER_ROLE','GET_ACHIEVEMENTS','MARK_NOTIFICATION_READ','SAVE_ACCOUNT_LOCALE','EXECUTE_NPC_ACTION','START_DIALOGUE','SELECT_DIALOGUE_OPTION','CREATE_PARTY','ADD_PARTY_MEMBER','REMOVE_PARTY_MEMBER','DISBAND_PARTY','START_ENCOUNTER','SELECT_COMBAT_ACTION','COMPLETE_COMBAT','CLAIM_ACHIEVEMENT_REWARD','SAVE_SETTINGS','SAVE_KEY_BINDING','RESET_KEY_BINDINGS','CREATE_RELEASE','VALIDATE_RELEASE','PUBLISH_RELEASE','MIGRATE_CHARACTER','CREATE_GAME','SAVE_GAME_CONFIG','CREATE_CONTENT_PACK','IMPORT_CONTENT_PACKS','REBUILD_CONTENT_DEPENDENCY_INDEX','IMPORT_BULK_STUDIO_CONTENT','SAVE_STUDIO_CONTENT','DELETE_STUDIO_CONTENT','TRAIN_SKILL','SAVE_LOADOUT','ACTIVATE_LOADOUT','DELETE_LOADOUT','CREATE_TEST_CHARACTER','SIM_MOVE_CHARACTER','SIM_GIVE_ITEM','SIM_APPLY_STATUS','SIM_SET_QUEST_STATE','SIM_START_ENCOUNTER','SIM_REPLAY_COMBAT','CREATE_CHARACTER','SPLIT_ITEM','MERGE_ITEM','TRANSFER_ITEM','BULK_TRANSFER_ITEMS','COLLECT_LOOT','SELECT_QUEST_BRANCH','SELECT_QUEST_REWARD','ACCEPT_QUEST','ABANDON_QUEST','EQUIP_ITEM','UNEQUIP_ITEM','USE_ITEM','MOVE_TO_LOCATION']);
const aggregateId=(body:any)=>body.characterId||body.combatId||body.questInstanceId||body.releaseId||body.gameId||body.sessionId||body.itemId||body.userId||body.notificationId||'';
const canonicalize=(value:any):any=>Array.isArray(value)?value.map(canonicalize):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).filter(key=>key!=='requestId').sort().map(key=>[key,canonicalize(value[key])])):value;
async function requestFingerprint(body:any){const bytes=new TextEncoder().encode(JSON.stringify(canonicalize(body))),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export function isIdempotentMutation(command:string){return mutations.has(command);}
export async function beginCommand(base44:any,user:any,body:any,requestId:string){
  if(!isIdempotentMutation(body.command))return {tracked:false};
  const fingerprint=await requestFingerprint(body),rows=await base44.asServiceRole.entities.CommandExecution.filter({actor_user_id:user.id,request_id:requestId,command:body.command},'created_date',10),existing=rows[0],now=Date.now();
  if(existing?.request_fingerprint&&existing.request_fingerprint!==fingerprint)return {tracked:true,replay:Response.json({error:'This request ID was already used with different command data.'},{status:409})};
  if(existing?.status==='completed')return {tracked:true,replay:Response.json(existing.response_body||{saved:true},{status:Number(existing.status_code||200)})};
  if(existing?.status==='processing'&&new Date(existing.lease_expires_at||0).getTime()>now)return {tracked:true,replay:Response.json({error:'This command is already processing.'},{status:409})};
  const lockToken=crypto.randomUUID(),leaseExpiresAt=new Date(now+60000).toISOString(),aggregate=aggregateId(body);
  if(!existing&&aggregate){const active=await base44.asServiceRole.entities.CommandExecution.filter({aggregate_id:aggregate,status:'processing'},'created_date',20);for(const row of active)if(new Date(row.lease_expires_at||0).getTime()<=now){await base44.asServiceRole.entities.CommandExecution.update(row.id,{status:'failed',error:'Command lease expired before completion.'});await recordCommandRecovery(base44,row,'stale_lease_reaped');}const blocking=active.find((row:any)=>new Date(row.lease_expires_at||0).getTime()>now);if(blocking)return {tracked:true,replay:Response.json({error:'Another command is already updating this record.'},{status:409})};}
  if(existing){await recordCommandRecovery(base44,existing,existing.status==='failed'?'failed_retry':'expired_lease_retry');const execution=await base44.asServiceRole.entities.CommandExecution.update(existing.id,{status:'processing',request_fingerprint:fingerprint,lock_token:lockToken,lease_expires_at:leaseExpiresAt,error:null,started_at:new Date(now).toISOString(),attempt_count:Number(existing.attempt_count||1)+1});return {tracked:true,execution,lockToken,userId:user.id,command:body.command,requestId};}
  const execution=await base44.asServiceRole.entities.CommandExecution.create({actor_user_id:user.id,request_id:requestId,request_fingerprint:fingerprint,command:body.command,aggregate_id:aggregate,status:'processing',lock_token:lockToken,lease_expires_at:leaseExpiresAt,started_at:new Date(now).toISOString(),attempt_count:1});
  if(aggregate){const aggregateOwner=(await base44.asServiceRole.entities.CommandExecution.filter({aggregate_id:aggregate,status:'processing'},'created_date',20))[0];if(aggregateOwner.id!==execution.id){await base44.asServiceRole.entities.CommandExecution.delete(execution.id);return {tracked:true,replay:Response.json({error:'Another command is already updating this record.'},{status:409})};}}
  const canonical=(await base44.asServiceRole.entities.CommandExecution.filter({actor_user_id:user.id,request_id:requestId,command:body.command},'created_date',10))[0];
  if(canonical.id!==execution.id){await base44.asServiceRole.entities.CommandExecution.delete(execution.id);if(canonical.status==='completed')return {tracked:true,replay:Response.json(canonical.response_body||{saved:true},{status:Number(canonical.status_code||200)})};return {tracked:true,replay:Response.json({error:'This command is already processing.'},{status:409})};}
  return {tracked:true,execution,lockToken,userId:user.id,command:body.command,requestId};
}
export async function completeCommand(base44:any,context:any,response:Response){if(!context?.execution)return;const current=await base44.asServiceRole.entities.CommandExecution.get(context.execution.id);if(current.lock_token!==context.lockToken)return;let responseBody:any={};try{responseBody=await response.clone().json();}catch{responseBody={saved:response.ok};}const failed=response.status>=500,finishedAt=new Date(),durationMs=Math.max(0,finishedAt.getTime()-new Date(current.started_at||current.created_date).getTime());await base44.asServiceRole.entities.CommandExecution.update(current.id,{status:failed?'failed':'completed',status_code:response.status,response_body:responseBody,error:failed?String(responseBody.error||'Server error'):null,completed_at:failed?null:finishedAt.toISOString(),duration_ms:durationMs,lease_expires_at:finishedAt.toISOString()});if(failed)await recordCommandFailure(base44,context.userId,context.command,context.requestId,responseBody.error,{status_code:response.status,aggregate_id:current.aggregate_id||null,duration_ms:durationMs});}
export async function failCommand(base44:any,context:any,error:any){if(!context?.execution)return;const current=await base44.asServiceRole.entities.CommandExecution.get(context.execution.id);if(current.lock_token!==context.lockToken)return;const finishedAt=new Date(),durationMs=Math.max(0,finishedAt.getTime()-new Date(current.started_at||current.created_date).getTime());await base44.asServiceRole.entities.CommandExecution.update(current.id,{status:'failed',error:String(error?.message||error),duration_ms:durationMs,lease_expires_at:finishedAt.toISOString()});await recordCommandFailure(base44,context.userId,context.command,context.requestId,error,{aggregate_id:current.aggregate_id||null,duration_ms:durationMs});}