function stackSignature(item:any){return JSON.stringify([item.definition_id,item.quality,item.durability,item.bound_state,item.custom_properties||{},item.applied_modifications||[]]);}
export async function inventoryContainersFor(base44:any,character:any){const owned=await base44.asServiceRole.entities.Container.filter({character_id:character.id},'name',50),memberships=await base44.asServiceRole.entities.PartyMember.filter({character_id:character.id,status:'active'},'-updated_date',1);if(!memberships.length)return owned;let shared=await base44.asServiceRole.entities.Container.filter({owner_type:'party',owner_id:memberships[0].party_id},'name',20);if(!shared.length)shared=[await base44.asServiceRole.entities.Container.create({game_id:character.game_id,content_version:character.content_version,owner_type:'party',owner_id:memberships[0].party_id,name:'Party storage',container_type:'party',capacity:0,version:1})];return [...new Map([...owned,...shared].map((container:any)=>[container.id,container])).values()];}
function itemOwner(container:any,character:any){return container.owner_type==='party'?{owner_type:'party',owner_id:container.owner_id,deposited_by_character_id:character.id}:{owner_type:'character',owner_id:character.id,character_id:character.id};}
async function grantItem(base44:any,character:any,reward:any,containerType:string,containerName:string,transactionId?:string){
  const definition=await base44.asServiceRole.entities.ItemDefinition.get(reward.itemDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)throw new Error('Item content is not valid for this character.');
  let containers=await base44.asServiceRole.entities.Container.filter({character_id:character.id,container_type:containerType},'created_date',1),container=containers[0];if(!container)container=await base44.asServiceRole.entities.Container.create({game_id:character.game_id,content_version:character.content_version,owner_type:'character',owner_id:character.id,character_id:character.id,name:containerName,container_type:containerType,capacity:0,version:1});
  let remaining=Math.max(1,Math.floor(Number(reward.quantity||1))),granted=remaining;const limit=Math.max(1,Number(definition.stack_limit||1));
  const stacks=await base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id,container_id:container.id,definition_id:definition.id},'created_date',200);
  if(transactionId&&stacks.some((item:any)=>item.custom_properties?.transaction_id===transactionId))return {type:'item',item_definition_id:definition.id,item_name:definition.name,quantity:granted,container_id:container.id};
  for(const stack of (transactionId?[]:stacks).filter((item:any)=>!item.equipped_slot&&item.quality==='standard'&&item.bound_state==='unbound'&&stackSignature(item)===stackSignature({definition_id:definition.id,quality:'standard',bound_state:'unbound',custom_properties:{},applied_modifications:[]}))){const space=Math.max(0,limit-Number(stack.quantity||0)),added=Math.min(space,remaining);if(added>0)await base44.asServiceRole.entities.ItemInstance.update(stack.id,{quantity:Number(stack.quantity||0)+added,version:Number(stack.version||1)+1});remaining-=added;if(!remaining)break;}
  const rows=[];while(remaining>0){const quantity=Math.min(limit,remaining);rows.push({game_id:character.game_id,content_version:character.content_version,definition_id:definition.id,container_id:container.id,owner_type:'character',owner_id:character.id,character_id:character.id,quantity,quality:'standard',bound_state:'unbound',custom_properties:transactionId?{transaction_id:transactionId}:{},applied_modifications:[],acquired_at:new Date().toISOString(),version:1});remaining-=quantity;}if(rows.length)await base44.asServiceRole.entities.ItemInstance.bulkCreate(rows);
  return {type:'item',item_definition_id:definition.id,item_name:definition.name,quantity:granted,container_id:container.id};
}
export async function grantItemReward(base44:any,character:any,reward:any,transactionId?:string){return await grantItem(base44,character,reward,'loot','Encounter loot',transactionId);}
export async function grantPurchasedItem(base44:any,character:any,reward:any,transactionId?:string){return await grantItem(base44,character,reward,'character','Carried items',transactionId);}
export async function grantQuestItem(base44:any,character:any,reward:any,transactionId?:string){return await grantItem(base44,character,reward,'character','Carried items',transactionId);}
async function ownedItem(base44:any,character:any,itemId:string,itemVersion:number){const item=await base44.asServiceRole.entities.ItemInstance.get(itemId),containers=await inventoryContainersFor(base44,character);if(!containers.some((container:any)=>container.id===item.container_id))return {response:Response.json({error:'Item ownership could not be verified.'},{status:403})};if(item.version!==itemVersion)return {response:Response.json({error:'Item state changed. Refresh and try again.'},{status:409})};return {item};}
export async function handleInventoryCommand(base44:any,user:any,character:any,body:any,requestId:string){
  const duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);if(duplicate.length)return null;
  if(body.command==='COLLECT_LOOT'){
    const containers=await inventoryContainersFor(base44,character),target=containers.find((container:any)=>container.container_type==='character'),lootIds=containers.filter((container:any)=>container.container_type==='loot').map((container:any)=>container.id);if(!target)return Response.json({error:'No carried storage is available.'},{status:422});
    const allItems=await base44.asServiceRole.entities.ItemInstance.filter({container_id:{'$in':containers.map((container:any)=>container.id)}},'-created_date',200),loot=allItems.filter((row:any)=>lootIds.includes(row.container_id));if(!loot.length)return Response.json({error:'There is no encounter loot to collect.'},{status:422});
    const carried=allItems.filter((row:any)=>row.container_id===target.id),weighted=[...carried,...loot],definitions=await Promise.all(weighted.map((row:any)=>base44.asServiceRole.entities.ItemDefinition.get(row.definition_id))),weight=weighted.reduce((sum:number,row:any,index:number)=>sum+Number(definitions[index].weight||0)*Number(row.quantity||0),0);if(Number(target.capacity||0)>0&&weight>Number(target.capacity))return Response.json({error:'Carried storage does not have enough capacity for all loot.'},{status:422});
    await base44.asServiceRole.entities.ItemInstance.bulkUpdate(loot.map((row:any)=>({id:row.id,container_id:target.id,version:Number(row.version||1)+1})));await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{container_id:target.id,item_count:loot.length,quantity:loot.reduce((sum:number,row:any)=>sum+Number(row.quantity||0),0)},occurred_at:new Date().toISOString()});return null;
  }
  if(body.command==='BULK_TRANSFER_ITEMS'){
    const selections=Array.isArray(body.items)?body.items.slice(0,100):[];if(!selections.length)return Response.json({error:'Select at least one item.'},{status:422});
    const container=await base44.asServiceRole.entities.Container.get(body.containerId);if(!(await inventoryContainersFor(base44,character)).some((allowed:any)=>allowed.id===container.id)||container.game_id!==character.game_id)return Response.json({error:'Container access could not be verified.'},{status:403});
    const items=await Promise.all(selections.map((selection:any)=>base44.asServiceRole.entities.ItemInstance.get(selection.id)));const allowedIds=new Set((await inventoryContainersFor(base44,character)).map((allowed:any)=>allowed.id));if(items.some((row:any,index:number)=>!allowedIds.has(row.container_id)||row.version!==selections[index].version))return Response.json({error:'One or more selected items changed. Refresh and try again.'},{status:409});if(items.some((row:any)=>row.equipped_slot))return Response.json({error:'Unequip selected items before moving them.'},{status:422});if(container.owner_type==='party'&&items.some((row:any)=>row.bound_state==='character'))return Response.json({error:'Character-bound items cannot be placed in party storage.'},{status:422});
    const moving=items.filter((row:any)=>row.container_id!==container.id),targetItems=await base44.asServiceRole.entities.ItemInstance.filter({container_id:container.id},'-created_date',200),weighted=[...targetItems,...moving],definitionIds=[...new Set(weighted.map((row:any)=>row.definition_id))],definitions=await Promise.all(definitionIds.map((id:any)=>base44.asServiceRole.entities.ItemDefinition.get(id))),weight=weighted.reduce((sum:number,row:any)=>sum+Number(definitions.find((definition:any)=>definition.id===row.definition_id)?.weight||0)*Number(row.quantity||0),0);if(Number(container.capacity||0)>0&&weight>Number(container.capacity))return Response.json({error:'That container does not have enough capacity.'},{status:422});
    if(moving.length)await base44.asServiceRole.entities.ItemInstance.bulkUpdate(moving.map((row:any)=>({id:row.id,container_id:container.id,...itemOwner(container,character),version:Number(row.version||1)+1})));await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{item_ids:moving.map((row:any)=>row.id),container_id:container.id,item_count:moving.length},occurred_at:new Date().toISOString()});return null;
  }
  const sourceResult=await ownedItem(base44,character,body.itemId,body.itemVersion);if(sourceResult.response)return sourceResult.response;const item=sourceResult.item;
  if(item.equipped_slot)return Response.json({error:'Unequip this item before changing its stack or container.'},{status:422});
  const definition=await base44.asServiceRole.entities.ItemDefinition.get(item.definition_id);
  if(body.command==='SPLIT_ITEM'){
    const quantity=Number(body.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>=item.quantity)return Response.json({error:'Split quantity must be less than the current stack.'},{status:422});if(Number(definition.stack_limit||1)<=1)return Response.json({error:'This item cannot be stacked.'},{status:422});
    await base44.asServiceRole.entities.ItemInstance.update(item.id,{quantity:item.quantity-quantity,version:item.version+1});
    await base44.asServiceRole.entities.ItemInstance.create({game_id:item.game_id,content_version:item.content_version,definition_id:item.definition_id,container_id:item.container_id,owner_type:item.owner_type,owner_id:item.owner_id,character_id:item.character_id,deposited_by_character_id:item.deposited_by_character_id,quantity,durability:item.durability,quality:item.quality,bound_state:item.bound_state,custom_properties:item.custom_properties||{},applied_modifications:item.applied_modifications||[],acquired_at:new Date().toISOString(),version:1});
  }
  if(body.command==='MERGE_ITEM'){
    const targetResult=await ownedItem(base44,character,body.targetItemId,body.targetItemVersion);if(targetResult.response)return targetResult.response;const target=targetResult.item;if(target.id===item.id||target.container_id!==item.container_id||target.equipped_slot||stackSignature(target)!==stackSignature(item))return Response.json({error:'Those item stacks cannot be merged.'},{status:422});
    const total=Number(item.quantity)+Number(target.quantity);if(total>Number(definition.stack_limit||1))return Response.json({error:'The merged stack would exceed its stack limit.'},{status:422});
    await base44.asServiceRole.entities.ItemInstance.update(target.id,{quantity:total,version:target.version+1});await base44.asServiceRole.entities.ItemInstance.delete(item.id);
  }
  if(body.command==='TRANSFER_ITEM'){
    const container=await base44.asServiceRole.entities.Container.get(body.containerId);if(!(await inventoryContainersFor(base44,character)).some((allowed:any)=>allowed.id===container.id)||container.game_id!==character.game_id)return Response.json({error:'Container access could not be verified.'},{status:403});if(container.id===item.container_id)return Response.json({error:'The item is already in that container.'},{status:422});if(container.owner_type==='party'&&item.bound_state==='character')return Response.json({error:'Character-bound items cannot be placed in party storage.'},{status:422});
    const targetItems=await base44.asServiceRole.entities.ItemInstance.filter({container_id:container.id},'-created_date',200),definitions=await Promise.all(targetItems.map((row:any)=>base44.asServiceRole.entities.ItemDefinition.get(row.definition_id))),weight=targetItems.reduce((sum:number,row:any,index:number)=>sum+Number(definitions[index].weight||0)*Number(row.quantity||0),0)+Number(definition.weight||0)*Number(item.quantity||0);if(Number(container.capacity||0)>0&&weight>Number(container.capacity))return Response.json({error:'That container does not have enough capacity.'},{status:422});
    await base44.asServiceRole.entities.ItemInstance.update(item.id,{container_id:container.id,...itemOwner(container,character),version:item.version+1});
  }
  await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command:body.command,request_id:requestId,result:'accepted',details:{item_id:item.id,target_item_id:body.targetItemId||null,container_id:body.containerId||item.container_id,quantity:body.quantity||item.quantity},occurred_at:new Date().toISOString()});return null;
}