import { evaluateCondition, resolveCharacterEffects } from './rules.ts';
import { grantPurchasedItem } from './inventory.ts';
import { applyCharacterTransaction, applySkillRankTransaction } from './economy.ts';

const amounts=(values:any)=>Object.entries(values||{}).filter(([,amount])=>Number(amount)>0);
function affordability(character:any,service:any){return amounts(service.costs).every(([key,amount])=>Number(character.currency?.[key]||0)>=Number(amount))&&amounts(service.resource_costs).every(([key,amount])=>Number(character.resources?.[key]||0)>=Number(amount));}
async function purchaseIssue(base44:any,character:any,item:any,quantity:number){const containers=await base44.asServiceRole.entities.Container.filter({character_id:character.id,container_type:'character'},'created_date',1),container=containers[0];if(!container||Number(container.capacity||0)<=0)return '';const rows=await base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id,container_id:container.id},'-created_date',500),definitions=await Promise.all(rows.map((row:any)=>base44.asServiceRole.entities.ItemDefinition.get(row.definition_id))),weight=rows.reduce((sum:number,row:any,index:number)=>sum+Number(definitions[index].weight||0)*Number(row.quantity||0),0)+Number(item.weight||0)*quantity;return weight>Number(container.capacity)?'Not enough carried capacity.':'';}
export async function describeNpcService(base44:any,character:any,service:any={}){
  const canAfford=affordability(character,service),summary:any={kind:service.kind||'custom',costs:service.costs||{},resource_costs:service.resource_costs||{},can_use:canAfford,unavailable_reason:canAfford?'':'Insufficient funds or resources.'};
  if(service.item_definition_id){const item=await base44.asServiceRole.entities.ItemDefinition.get(service.item_definition_id),quantity=Math.max(1,Number(service.quantity||1)),issue=await purchaseIssue(base44,character,item,quantity);summary.item={id:item.id,name:item.name,quantity};if(issue){summary.can_use=false;summary.unavailable_reason=issue;}}
  if(service.skill_definition_id){const skill=await base44.asServiceRole.entities.SkillDefinition.get(service.skill_definition_id),rows=await base44.asServiceRole.entities.CharacterSkill.filter({character_id:character.id,skill_definition_id:skill.id},'-updated_date',1),rank=Number(rows[0]?.rank||0);summary.skill={id:skill.id,name:skill.name,rank,max_rank:Number(skill.max_rank||1)};if(rank>=summary.skill.max_rank){summary.can_use=false;summary.unavailable_reason='Maximum rank reached.';}else if(!await evaluateCondition(base44,{character},skill.requirements)){summary.can_use=false;summary.unavailable_reason='Training requirements are not met.';}}
  return summary;
}
export async function executeNpcService(base44:any,character:any,action:any,transactionId:string){
  const service=action.service||{},kind=service.kind||'custom';
  if(!affordability(character,service))return {error:'This character cannot afford that service.'};
  if(kind==='shop'&&!service.item_definition_id)return {error:'This shop service has no item configured.'};
  if(kind==='training'&&!service.skill_definition_id)return {error:'This training service has no skill configured.'};
  let item=null,skill=null,skillRecord=null;
  if(service.item_definition_id){item=await base44.asServiceRole.entities.ItemDefinition.get(service.item_definition_id);if(item.game_id!==character.game_id||item.content_version!==character.content_version)return {error:'That shop item is not valid for this character.'};const issue=await purchaseIssue(base44,character,item,Math.max(1,Number(service.quantity||1)));if(issue)return {error:issue};}
  if(service.skill_definition_id){skill=await base44.asServiceRole.entities.SkillDefinition.get(service.skill_definition_id);if(skill.game_id!==character.game_id||skill.content_version!==character.content_version)return {error:'That training is not valid for this character.'};if(!await evaluateCondition(base44,{character},skill.requirements))return {error:'This character does not meet the training requirements.'};const rows=await base44.asServiceRole.entities.CharacterSkill.filter({character_id:character.id,skill_definition_id:skill.id},'-updated_date',1);skillRecord=rows[0]||null;if(Number(skillRecord?.rank||0)>=Number(skill.max_rank||1)&&!skillRecord?.processed_transaction_ids?.includes(`${transactionId}:skill`))return {error:'This skill is already at maximum rank.'};}
  const applied=await applyCharacterTransaction(base44,character.id,`${transactionId}:character`,async(fresh:any)=>{if(!affordability(fresh,service))throw new Error('This character cannot afford that service.');const currency={...(fresh.currency||{})},resources={...(fresh.resources||{})};for(const [key,amount] of amounts(service.costs))currency[key]=Number(currency[key]||0)-Number(amount);for(const [key,amount] of amounts(service.resource_costs))resources[key]=Number(resources[key]||0)-Number(amount);const resolved=await resolveCharacterEffects(base44,{...fresh,currency,resources},(action.effects||[]).filter((effect:any)=>effect.type!=='relationshipChange'));return resolved.patch;});
  const updated=applied.character,outcomes:any[]=[];
  if(item)outcomes.push(await grantPurchasedItem(base44,updated,{itemDefinitionId:item.id,quantity:service.quantity||1},`${transactionId}:item`));
  if(skill){const trained=await applySkillRankTransaction(base44,updated,skill,`${transactionId}:skill`);outcomes.push({type:'training',skill_definition_id:skill.id,skill_name:skill.name,rank:trained.rank});}
  return {character:updated,outcomes};
}