import { authorizedGameIds } from './authorization.ts';
import { summarizeCommandHealth } from './reliability.ts';
const limits:any={CREATE_CHARACTER_BACKUP:10,RESTORE_CHARACTER_BACKUP:5,ROLLBACK_MIGRATION:5,RETRY_DEAD_LETTER:20,COMPARE_RELEASES:20,SIM_REPLAY_SUITE:10,CREATE_CHARACTER:5,MOVE_TO_LOCATION:60,USE_ITEM:40,EQUIP_ITEM:40,UNEQUIP_ITEM:40,ACCEPT_QUEST:20,ABANDON_QUEST:20,START_ENCOUNTER:20,SELECT_COMBAT_ACTION:120,COMPLETE_COMBAT:20,TRAIN_SKILL:20,SAVE_LOADOUT:30,ACTIVATE_LOADOUT:30,DELETE_LOADOUT:20,SAVE_SETTINGS:30,SAVE_KEY_BINDING:30,RESET_KEY_BINDINGS:10,CREATE_RELEASE:10,VALIDATE_RELEASE:20,PUBLISH_RELEASE:5,PREVIEW_MIGRATION:20,MIGRATE_CHARACTER:10,MARK_NOTIFICATION_READ:60,SAVE_ACCOUNT_LOCALE:20};
export async function enforceCommandRate(base44:any,user:any,command:string){const limit=limits[command];if(!limit)return null;const windowKey=new Date().toISOString().slice(0,16),query={user_id:user.id,command,window_key:windowKey};const rows=await base44.asServiceRole.entities.CommandUsage.filter(query,'-created_date',1),row=rows[0];if(row&&row.count>=limit){await base44.asServiceRole.entities.OperationalEvent.create({user_id:user.id,category:'rate_limit',severity:'warning',command,message:`Rate limit reached for ${command}.`,metadata:{limit,window_key:windowKey},occurred_at:new Date().toISOString()});return Response.json({error:'Too many requests. Please wait a moment and try again.',retry_after_seconds:60-new Date().getSeconds()},{status:429});}if(row)await base44.asServiceRole.entities.CommandUsage.update(row.id,{count:row.count+1,version:row.version+1});else await base44.asServiceRole.entities.CommandUsage.create({...query,count:1,limit,version:1});return null;}
export async function createNotification(base44:any,recipientUserId:string,category:string,title:string,message:string,link='/'){if(!recipientUserId)return;await base44.asServiceRole.entities.Notification.create({recipient_user_id:recipientUserId,category,title,message,link,read:false});}
async function notificationInbox(base44:any,userId:string){const notifications=await base44.asServiceRole.entities.Notification.filter({recipient_user_id:userId},'-created_date',200);return {notifications,unread:notifications.filter((item:any)=>!item.read).length};}
export async function handleOperationsCommand(base44:any,user:any,body:any){
  if(body.command==='GET_ADMIN_USERS'||body.command==='INVITE_USER'||body.command==='UPDATE_USER_ROLE'){
    if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
    if(body.command==='INVITE_USER'){const role=['admin','user'].includes(body.role)?body.role:'user';await base44.users.inviteUser(String(body.email).trim().toLowerCase(),role);}
    if(body.command==='UPDATE_USER_ROLE'){if(!['admin','user'].includes(body.role))return Response.json({error:'Role must be admin or user.'},{status:422});if(body.userId===user.id&&body.role!=='admin')return Response.json({error:'You cannot remove your own administrator access.'},{status:409});await base44.entities.User.update(body.userId,{role:body.role});}
    return Response.json({users:await base44.entities.User.list('-created_date',200)});
  }
  if(body.command==='GET_NOTIFICATIONS')return Response.json(await notificationInbox(base44,user.id));
  if(body.command==='MARK_NOTIFICATION_READ'){const notification=await base44.asServiceRole.entities.Notification.get(body.notificationId);if(notification.recipient_user_id!==user.id)return Response.json({error:'Notification ownership could not be verified.'},{status:403});if(!notification.read)await base44.asServiceRole.entities.Notification.update(notification.id,{read:true});return Response.json(await notificationInbox(base44,user.id));}
  if(body.command==='GET_OPERATIONS'){
    if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
    const allowedGameIds=await authorizedGameIds(base44,user,'operations:read');if(allowedGameIds&&allowedGameIds.length===0)return Response.json({error:'Forbidden'},{status:403});
    const [usage,events,executions,allAudits,allSnapshots,allMigrations,outbox]=await Promise.all([base44.asServiceRole.entities.CommandUsage.list('-updated_date',100),base44.asServiceRole.entities.OperationalEvent.list('-occurred_at',50),base44.asServiceRole.entities.CommandExecution.list('-updated_date',100),base44.asServiceRole.entities.AuditEvent.list('-occurred_at',100),base44.asServiceRole.entities.CharacterSnapshot.list('-created_date',50),base44.asServiceRole.entities.ContentMigration.list('-created_date',50),base44.asServiceRole.entities.OutboxEvent.list('-updated_date',100)]);
    const within=(row:any)=>!allowedGameIds||allowedGameIds.includes(row.game_id),audits=allAudits.filter(within),snapshots=allSnapshots.filter(within),migrations=allMigrations.filter(within),visibleUsage=allowedGameIds?[]:usage,visibleEvents=allowedGameIds?[]:events,visibleExecutions=allowedGameIds?[]:executions,visibleOutbox=outbox.filter(within),executionHealth=summarizeCommandHealth(visibleExecutions),outboxHealth={pending:visibleOutbox.filter((row:any)=>row.status==='pending'||row.status==='publishing').length,failed:visibleOutbox.filter((row:any)=>row.status==='failed').length,published:visibleOutbox.filter((row:any)=>row.status==='published').length},deadLetters=visibleOutbox.filter((row:any)=>row.status==='failed').slice(0,20).map((row:any)=>({id:row.id,envelope:{event_type:row.envelope?.event_type},attempts:row.attempts,last_error:row.last_error,available_at:row.available_at}));
    return Response.json({counts:{commands:visibleUsage.reduce((sum:number,x:any)=>sum+x.count,0),warnings:visibleEvents.filter((x:any)=>x.severity!=='info').length,processing:executionHealth.processing,failed:executionHealth.failed,stale:executionHealth.stale,outbox_pending:outboxHealth.pending,outbox_failed:outboxHealth.failed,snapshots:snapshots.length,migrations:migrations.filter((x:any)=>x.status==='completed').length},executionHealth,outboxHealth,events:visibleEvents.slice(0,12),usage:visibleUsage.slice(0,12),activity:visibleExecutions.slice(0,20).map((row:any)=>({id:row.id,command:row.command,status:row.status,status_code:row.status_code,started_at:row.started_at,completed_at:row.completed_at,duration_ms:row.duration_ms})),audits:audits.slice(0,20).map((row:any)=>({id:row.id,command:row.command,result:row.result,occurred_at:row.occurred_at,character_id:row.character_id})),deadLetters,backups:snapshots.slice(0,20).map((row:any)=>({id:row.id,character_id:row.character_id,content_version:row.content_version,reason:row.reason,created_date:row.created_date})),migrations:migrations.slice(0,20).map((row:any)=>({id:row.id,character_id:row.character_id,from_version:row.from_version,to_version:row.to_version,status:row.status,snapshot_id:row.snapshot_id,executed_at:row.executed_at}))});
  }
  return Response.json({error:'Unknown operations command.'},{status:400});
}