async function currentContext(base44:any){const characters=await base44.entities.Character.list('-updated_date',20),character=characters[0]||null,games=await base44.asServiceRole.entities.Game.filter({status:'published'},'title',20),game=character?games.find((item:any)=>item.id===character.game_id)||await base44.asServiceRole.entities.Game.get(character.game_id):games[0]||null;return {character,game};}
async function accountLocale(base44:any,user:any){const rows=await base44.asServiceRole.entities.UserSetting.filter({user_id:user.id,scope:'account'},'-updated_date',1);return {record:rows[0]||null,locale:String(rows[0]?.values?.locale||'en')};}
async function localization(base44:any,user:any,game:any,contentVersion:string){const account=await accountLocale(base44,user);if(!game||!contentVersion)return {locale:account.locale,locales:['en'],translations:{}};const all=await base44.asServiceRole.entities.LocalizationEntry.filter({game_id:game.id,content_version:contentVersion},'locale',500),locales=[...new Set(['en',...all.map((entry:any)=>entry.locale)])].sort(),locale=locales.includes(account.locale)?account.locale:'en',translations=Object.fromEntries(all.filter((entry:any)=>entry.locale===locale).map((entry:any)=>[entry.key,entry.value]));return {locale,locales,translations};}
export async function loadPresentation(base44:any,user:any){const {character,game}=await currentContext(base44);let version=character?.content_version;if(!version&&game){const releases=await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',1);version=releases[0]?.version;}return await localization(base44,user,game,version);}
export async function handlePlatformCommand(base44:any,user:any,body:any){const {character,game}=await currentContext(base44);
  if(body.command==='GET_PRESENTATION')return Response.json(await loadPresentation(base44,user));
  if(body.command==='GET_RUNTIME_MODULE'){if(!character||!game)return Response.json({error:'Create a character before opening this module.'},{status:409});const key=String(body.moduleKey||''),rows=await base44.asServiceRole.entities.RuntimeModuleDefinition.filter({game_id:game.id,content_version:character.content_version,route_slug:key},'-created_date',1),module=rows[0];if(!module||((game.enabled_modules||[]).length&&!(game.enabled_modules||[]).includes(module.key)))return Response.json({error:'That runtime module is not enabled.'},{status:404});return Response.json({module,...await loadPresentation(base44,user)});}
  if(body.command==='GET_ACCOUNT'){const presentation=await loadPresentation(base44,user);return Response.json({account:{id:user.id,full_name:user.full_name,email:user.email},...presentation});}
  if(body.command==='SAVE_ACCOUNT_LOCALE'){const requested=String(body.locale||'').trim(),presentation=await loadPresentation(base44,user);if(!presentation.locales.includes(requested))return Response.json({error:'That locale is not available for this game.'},{status:422});const account=await accountLocale(base44,user),values={...(account.record?.values||{}),locale:requested};if(account.record)await base44.asServiceRole.entities.UserSetting.update(account.record.id,{values,version:Number(account.record.version||1)+1});else await base44.asServiceRole.entities.UserSetting.create({user_id:user.id,scope:'account',values,version:1});return Response.json({saved:true,locale:requested});}
  if(!character)return Response.json({error:'Create a character before opening this module.'},{status:409});
  if(body.command==='GET_WORLD'){const [locations,connections]=await Promise.all([base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:character.content_version},'name',500),base44.asServiceRole.entities.Connection.filter({game_id:character.game_id,content_version:character.content_version,enabled:true},'label',500)]);return Response.json({character,current_location_id:character.current_location_id,locations,connections});}
  if(body.command==='GET_JOURNAL'){const [events,quests]=await Promise.all([base44.asServiceRole.entities.DomainEvent.filter({character_id:character.id},'-occurred_at',200),base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id},'-updated_date',100)]),definitionIds=[...new Set(quests.map((quest:any)=>quest.definition_id))],definitions=await Promise.all(definitionIds.map((id:any)=>base44.asServiceRole.entities.QuestDefinition.get(id)));return Response.json({events,quests:quests.map((quest:any)=>({...quest,definition:definitions.find((definition:any)=>definition.id===quest.definition_id)||null}))});}
  return Response.json({error:'Unknown platform command.'},{status:400});
}