import { requireGamePermission } from './authorization.ts';
import { drainOutbox } from './eventBus.ts';
const protectedFields=new Set(['id','created_date','updated_date','created_by_id','created_by','version']);
const restorable=(state:any)=>Object.fromEntries(Object.entries(state||{}).filter(([key])=>!protectedFields.has(key)));
const audit=(base44:any,user:any,gameId:string,characterId:string,command:string,requestId:string,details:any)=>base44.asServiceRole.entities.AuditEvent.create({game_id:gameId,actor_user_id:user.id,character_id:characterId,command,request_id:requestId,result:'accepted',details,occurred_at:new Date().toISOString()});
async function restoreSnapshot(base44:any,user:any,snapshot:any,requestId:string,reason:string){const character=await base44.asServiceRole.entities.Character.get(snapshot.character_id),access=await requireGamePermission(base44,user,character.game_id,'migration:write');if(access)return access;if(character.game_id!==snapshot.game_id)return Response.json({error:'Backup ownership could not be verified.'},{status:403});const safety=await base44.asServiceRole.entities.CharacterSnapshot.create({game_id:character.game_id,character_id:character.id,content_version:character.content_version,reason:`Before restore: ${reason}`,state:character,created_by_user_id:user.id}),restored=await base44.asServiceRole.entities.Character.update(character.id,{...restorable(snapshot.state),version:Number(character.version||0)+1});await audit(base44,user,character.game_id,character.id,'RESTORE_CHARACTER_BACKUP',requestId,{snapshot_id:snapshot.id,safety_snapshot_id:safety.id});return Response.json({restored:true,character:restored,safetySnapshotId:safety.id});}
export async function handleHardeningCommand(base44:any,user:any,body:any,requestId:string){
  if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  if(body.command==='CREATE_CHARACTER_BACKUP'){const character=await base44.asServiceRole.entities.Character.get(body.characterId),access=await requireGamePermission(base44,user,character.game_id,'migration:write');if(access)return access;const snapshot=await base44.asServiceRole.entities.CharacterSnapshot.create({game_id:character.game_id,character_id:character.id,content_version:character.content_version,reason:String(body.reason||'Manual production backup').slice(0,160),state:character,created_by_user_id:user.id});await audit(base44,user,character.game_id,character.id,body.command,requestId,{snapshot_id:snapshot.id});return Response.json({snapshot});}
  if(body.command==='RESTORE_CHARACTER_BACKUP'){const snapshot=await base44.asServiceRole.entities.CharacterSnapshot.get(body.snapshotId);return await restoreSnapshot(base44,user,snapshot,requestId,snapshot.reason);}
  if(body.command==='ROLLBACK_MIGRATION'){const migration=await base44.asServiceRole.entities.ContentMigration.get(body.migrationId);if(migration.status!=='completed'||!migration.snapshot_id)return Response.json({error:'Only completed migrations with a saved snapshot can be rolled back.'},{status:409});const snapshot=await base44.asServiceRole.entities.CharacterSnapshot.get(migration.snapshot_id),response=await restoreSnapshot(base44,user,snapshot,requestId,`migration ${migration.id}`);if(!response.ok)return response;await base44.asServiceRole.entities.ContentMigration.update(migration.id,{status:'rolled_back',rolled_back_at:new Date().toISOString()});return response;}
  if(body.command==='RETRY_DEAD_LETTER'){const event=await base44.asServiceRole.entities.OutboxEvent.get(body.outboxEventId),access=await requireGamePermission(base44,user,event.game_id,'operations:write');if(access)return access;if(event.status!=='failed')return Response.json({error:'Only failed outbox events can be retried.'},{status:409});await base44.asServiceRole.entities.OutboxEvent.update(event.id,{status:'pending',available_at:new Date().toISOString(),last_error:null,lock_token:null,lease_expires_at:new Date().toISOString(),version:Number(event.version||1)+1});const recovered=await drainOutbox(base44,1);await audit(base44,user,event.game_id,'',body.command,requestId,{outbox_event_id:event.id,recovered:recovered.length===1});return Response.json({recovered:recovered.length===1,outboxEventId:event.id});}
  return Response.json({error:'Unknown hardening command.'},{status:400});
}