import { evaluateCondition } from './rules.ts';
import { applyCharacterTransaction } from './economy.ts';
import { grantQuestItem } from './inventory.ts';
import { processWorldSignals } from './worldEvents.ts';
import { characterEventInput, publishDomainEvent } from './eventBus.ts';
import { applyNarrativeEffects,createQuestOutcomeRecap,recordQuestHistory } from './narrative.ts';
export { recordQuestHistory };
const objectiveTypes=['visitLocation','interactWithEntity','acquireItem','loseItem','deliverItem','defeatEntity','surviveEncounter','useAbility','reachAttributeThreshold','selectDialogueResponse','completeQuest','customEvent','satisfyCondition'];
const targetMatches=(objective:any,value:any)=>!objective.targetId||objective.targetId===value;
async function matches(base44:any,character:any,objective:any,event:any){
  const payload=event.payload||{},type=objective.type;
  if(objective.eventType&&objective.eventType!==event.event_type)return false;
  if(type==='visitLocation')return event.event_type==='character.location.entered'&&targetMatches(objective,payload.location_id||payload.to);
  if(type==='interactWithEntity')return ['npc.interaction.started','npc.interaction.completed'].includes(event.event_type)&&targetMatches(objective,payload.npc_definition_id||payload.npc_instance_id);
  if(type==='acquireItem')return event.event_type==='inventory.item.added'&&targetMatches(objective,payload.item_definition_id);
  if(type==='loseItem'||type==='deliverItem')return ['inventory.item.removed','inventory.item.delivered'].includes(event.event_type)&&targetMatches(objective,payload.item_definition_id);
  if(type==='defeatEntity')return event.event_type==='combat.entity.defeated'&&targetMatches(objective,payload.entity_definition_id);
  if(type==='surviveEncounter')return event.event_type==='combat.encounter.won'&&targetMatches(objective,payload.encounter_definition_id);
  if(type==='useAbility')return event.event_type==='combat.ability.used'&&targetMatches(objective,payload.ability_id);
  if(type==='selectDialogueResponse')return event.event_type==='dialogue.option.selected'&&targetMatches(objective,payload.option_key)&&(!objective.dialogueGraphId||[payload.dialogue_graph_id,payload.dialogue_graph_key].includes(objective.dialogueGraphId))&&(!objective.nodeKey||objective.nodeKey===payload.node_key);
  if(type==='completeQuest')return event.event_type==='quest.completed'&&targetMatches(objective,payload.definition_id);
  if(type==='customEvent')return event.event_type===(objective.eventType||objective.targetId);
  if(type==='reachAttributeThreshold')return Number(character.attributes?.[objective.attributeId||objective.targetId]||0)>=Number(objective.value||objective.count||1);
  if(type==='satisfyCondition')return await evaluateCondition(base44,{character,event},objective.condition||{});
  return false;
}
function graphNodeComplete(node:any,states:Map<string,string>):boolean{if(typeof node==='string')return states.get(node)==='COMPLETED';if(!node)return false;if(node.objective)return states.get(node.objective)==='COMPLETED';if(Array.isArray(node.all))return node.all.every((child:any)=>graphNodeComplete(child,states));if(Array.isArray(node.any))return node.any.some((child:any)=>graphNodeComplete(child,states));if(Array.isArray(node.sequence))return node.sequence.every((child:any)=>graphNodeComplete(child,states));return false;}
function questComplete(graph:any,rows:any[]){const states=new Map(rows.map(row=>[row.objective_key,row.state]));if(graph.root)return graphNodeComplete(graph.root,states);const required=rows.filter(row=>!row.optional&&!['SKIPPED','REPLACED'].includes(row.state));return graph.mode==='any'?required.some(row=>row.state==='COMPLETED'):required.every(row=>row.state==='COMPLETED');}
function canActivate(definition:any,states:Map<string,string>,graph:any,branchState:any={}){if(definition.replacementFor&&!['FAILED','REPLACED'].includes(states.get(definition.replacementFor)||''))return false;const containing=(graph.branches||[]).find((branch:any)=>(branch.objectiveKeys||[]).includes(definition.key));if(containing&&branchState.selected_branch!==containing.key)return false;if((definition.dependsOn||[]).some((key:string)=>states.get(key)!=='COMPLETED'))return false;const sequence=graph.sequence||(graph.mode==='sequence'?(graph.objectives||[]).map((item:any)=>item.key):[]);const index=sequence.indexOf(definition.key),otherBranchKeys=new Set((graph.branches||[]).filter((branch:any)=>branch.key!==branchState.selected_branch).flatMap((branch:any)=>branch.objectiveKeys||[]));return index<0||sequence.slice(0,index).every((key:string)=>otherBranchKeys.has(key)||['COMPLETED','SKIPPED'].includes(states.get(key)||''));}
export function createObjectiveRows(definition:any,instance:any,character:any){const graph=definition.objective_graph||{},objectives=graph.objectives||[],states=new Map(objectives.map((objective:any)=>[objective.key,'PENDING']));return objectives.map((objective:any)=>{const active=!objective.replacementFor&&!Object.keys(objective.activationCondition||{}).length&&canActivate(objective,states,graph,instance.branch_state||{});if(active)states.set(objective.key,'ACTIVE');return {game_id:character.game_id,quest_instance_id:instance.id,character_id:character.id,objective_key:objective.key,objective_type:objective.type,target_id:objective.targetId||'',required_count:Number(objective.count||1),current_count:0,state:active?'ACTIVE':'PENDING',optional:!!objective.optional,alternative_group:objective.alternativeGroup||'',replacement_for:objective.replacementFor||'',replacement_objective_key:objective.replacementObjectiveKey||'',activation_condition:objective.activationCondition||{},failure_condition:objective.failureCondition||{},activated_at:active?new Date().toISOString():undefined,processed_event_ids:[],version:1};});}
async function grantRewards(base44:any,character:any,definition:any,transactionId:string){
  const rewards=definition.rewards||[],stateRewards=rewards.filter((reward:any)=>reward.type==='currency'||reward.type==='resourceChange');
  const applied=await applyCharacterTransaction(base44,character.id,`${transactionId}:state`,(fresh:any)=>{const currency={...(fresh.currency||{})},resources={...(fresh.resources||{})};for(const reward of stateRewards){if(reward.type==='currency')currency[reward.currencyId]=Number(currency[reward.currencyId]||0)+Number(reward.amount||0);else resources[reward.resourceId]=Math.max(0,Number(resources[reward.resourceId]||0)+Number(reward.amount||0));}return {currency,resources};});
  for(const [index,reward] of rewards.entries())if(reward.type==='item'){const granted=await grantQuestItem(base44,applied.character,reward,`${transactionId}:item:${index}`);await publishQuestEvent(base44,applied.character,'inventory.item.added','item',granted.item_definition_id,`${transactionId}:event:${index}`,{item_definition_id:granted.item_definition_id,quantity:granted.quantity});}
}
async function deliverAutomaticRewards(base44:any,character:any,quest:any,definition:any){let current=quest;if(current.reward_state==='pending')current=await base44.asServiceRole.entities.QuestInstance.update(current.id,{reward_state:'granting',version:Number(current.version||1)+1});if(current.reward_state!=='granting')return current;await grantRewards(base44,character,definition,`quest:${current.id}:automatic`);const granted=await base44.asServiceRole.entities.QuestInstance.update(current.id,{reward_state:'granted',version:Number(current.version||1)+1});await recordQuestHistory(base44,character,granted,'rewards_granted',`Rewards granted for ${definition.name}.`,{dedupe_key:`${quest.id}:rewards:automatic`});return granted;}
async function failQuest(base44:any,character:any,quest:any,definition:any,rows:any[],event:any,reason='Quest failed'){const active=rows.filter(row=>row.state==='ACTIVE'||row.state==='PENDING');if(active.length)await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(active.map(row=>({id:row.id,state:'FAILED',failed_at:new Date().toISOString(),version:row.version+1})));const failed=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{state:'FAILED',failed_at:new Date().toISOString(),reward_state:'none',version:quest.version+1});await recordQuestHistory(base44,character,failed,'quest_failed',reason,{dedupe_key:`${quest.id}:failed`},event?.id);await createQuestOutcomeRecap(base44,character,failed,definition,'FAILED',event);const effects=(definition.relationship_changes||[]).filter((effect:any)=>!effect.whenState||effect.whenState==='FAILED');if(effects.length)await applyNarrativeEffects(base44,character,effects,{quest:failed,questDefinition:definition,event});}
export async function processQuestEvent(base44:any,character:any,event:any){
  const rewardGrantEvent=String(event.request_id||'').startsWith('quest:')&&String(event.request_id||'').includes(':event:');
  const awaiting=rewardGrantEvent?[]:await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,state:'COMPLETED',reward_state:{'$in':['pending','granting']}},'-completed_at',100);
  for(const quest of awaiting){const definition=await base44.asServiceRole.entities.QuestDefinition.get(quest.definition_id);if(!(definition.reward_selection?.choices||[]).length){await deliverAutomaticRewards(base44,character,quest,definition);await publishQuestEvent(base44,character,'quest.completed','quest',quest.id,`quest:${quest.id}:completed`,{definition_id:definition.id,quest_key:definition.key});}}
  const quests=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,state:'ACTIVE'},'-accepted_at',100);
  for(const quest of quests){const definition=await base44.asServiceRole.entities.QuestDefinition.get(quest.definition_id),now=Date.now(),expired=quest.expires_at&&new Date(quest.expires_at).getTime()<=now,failureRules=definition.failure_rules||{},failed=Object.keys(failureRules).length>0&&await evaluateCondition(base44,{character,event},failureRules);if(expired||failed){await failQuest(base44,character,quest,definition,await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200),event,expired?'Quest expired':'Quest failure conditions were met');continue;}
    let rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200),changed=false;
    for(const row of rows.filter(item=>item.state==='ACTIVE'&&!(item.processed_event_ids||[]).includes(event.id))){const objective=(definition.objective_graph?.objectives||[]).find((item:any)=>item.key===row.objective_key);if(!objective)continue;if(Object.keys(objective.failureCondition||{}).length&&await evaluateCondition(base44,{character,quest,event},objective.failureCondition)){const replacement=objective.replacementObjectiveKey?rows.find((item:any)=>item.objective_key===objective.replacementObjectiveKey):null;await base44.asServiceRole.entities.ObjectiveInstance.update(row.id,{state:replacement?'REPLACED':'FAILED',failed_at:new Date().toISOString(),replaced_by_key:replacement?.objective_key,processed_event_ids:[...(row.processed_event_ids||[]),event.id],last_event_at:event.occurred_at,version:row.version+1});if(replacement)await base44.asServiceRole.entities.ObjectiveInstance.update(replacement.id,{state:'ACTIVE',activated_at:new Date().toISOString(),version:replacement.version+1});await recordQuestHistory(base44,character,quest,replacement?'objective_replaced':'objective_failed',replacement?`${objective.label||objective.key} was replaced by ${replacement.objective_key}.`:`${objective.label||objective.key} failed.`,{objective_key:objective.key,replacement_key:replacement?.objective_key,dedupe_key:`${quest.id}:${objective.key}:failed:${event.id}`},event.id);changed=true;continue;}if(!await matches(base44,character,objective,event))continue;const stateful=['reachAttributeThreshold','satisfyCondition'].includes(objective.type),increment=Number(event.payload?.quantity||event.payload?.count||1),current=stateful?row.required_count:Math.min(row.required_count,Number(row.current_count||0)+Math.max(1,increment)),completed=current>=row.required_count;await base44.asServiceRole.entities.ObjectiveInstance.update(row.id,{current_count:current,state:completed?'COMPLETED':'ACTIVE',completed_at:completed?new Date().toISOString():undefined,processed_event_ids:[...(row.processed_event_ids||[]),event.id],last_event_at:event.occurred_at,version:row.version+1});if(completed){await recordQuestHistory(base44,character,quest,'objective_completed',`${objective.label||objective.key} completed.`,{objective_key:objective.key,dedupe_key:`${quest.id}:${objective.key}:completed`},event.id);if(objective.alternativeGroup){const alternatives=rows.filter((item:any)=>item.id!==row.id&&item.alternative_group===objective.alternativeGroup&&!['COMPLETED','SKIPPED'].includes(item.state));if(alternatives.length)await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(alternatives.map((item:any)=>({id:item.id,state:'SKIPPED',version:item.version+1})));}if((objective.onCompleteEffects||[]).length)await applyNarrativeEffects(base44,character,objective.onCompleteEffects,{quest,questDefinition:definition,event});}changed=true;}
    if(changed){rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200);const states=new Map(rows.map(row=>[row.objective_key,row.state])),pending=[];for(const row of rows.filter(item=>item.state==='PENDING')){const objective=(definition.objective_graph?.objectives||[]).find((item:any)=>item.key===row.objective_key);if(objective&&canActivate(objective,states,definition.objective_graph||{},quest.branch_state||{})&&(!Object.keys(objective.activationCondition||{}).length||await evaluateCondition(base44,{character,quest,event},objective.activationCondition)))pending.push(row);}if(pending.length){await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(pending.map(row=>({id:row.id,state:'ACTIVE',activated_at:new Date().toISOString(),version:row.version+1})));for(const row of pending)await recordQuestHistory(base44,character,quest,'objective_activated',`${(definition.objective_graph?.objectives||[]).find((item:any)=>item.key===row.objective_key)?.label||row.objective_key} activated.`,{objective_key:row.objective_key,dedupe_key:`${quest.id}:${row.objective_key}:activated`},event.id);rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200);}}
    const completionRules=definition.completion_rules||{},completionAllowed=!Object.keys(completionRules).length||completionRules.allRequired===true||await evaluateCondition(base44,{character,event},completionRules);if(questComplete(definition.objective_graph||{},rows)&&completionAllowed){const currentQuest=await base44.asServiceRole.entities.QuestInstance.get(quest.id),needsChoice=(definition.reward_selection?.choices||[]).length>0,completed=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{state:'COMPLETED',completed_at:new Date().toISOString(),reward_state:'pending',version:Number(currentQuest.version||1)+1});await recordQuestHistory(base44,character,completed,'quest_completed',`${definition.name} completed.`,{dedupe_key:`${quest.id}:completed`},event.id);const effects=(definition.relationship_changes||[]).filter((effect:any)=>!effect.whenState||effect.whenState==='COMPLETED');if(effects.length)await applyNarrativeEffects(base44,character,effects,{quest:completed,questDefinition:definition,event});if(!needsChoice)await deliverAutomaticRewards(base44,character,completed,definition);await createQuestOutcomeRecap(base44,character,await base44.asServiceRole.entities.QuestInstance.get(quest.id),definition,'COMPLETED',event);await publishQuestEvent(base44,character,'quest.completed','quest',completed.id,`quest:${quest.id}:completed`,{definition_id:definition.id,quest_key:definition.key});}
  }
}
export async function refreshQuestProgress(base44:any,character:any){const fresh=await base44.entities.Character.get(character.id);await processQuestEvent(base44,fresh,{id:`quest-state-refresh:${fresh.id}`,event_type:'quest.progress.refreshed',aggregate_type:'character',aggregate_id:fresh.id,request_id:`quest-state-refresh:${fresh.id}`,payload:{},occurred_at:new Date().toISOString()});}
export async function selectQuestBranch(base44:any,character:any,questId:string,questVersion:number,branchKey:string,requestId:string){const quest=await base44.asServiceRole.entities.QuestInstance.get(questId);if(quest.character_id!==character.id)return Response.json({error:'Quest ownership could not be verified.'},{status:403});if(quest.state!=='ACTIVE'||quest.version!==questVersion||quest.branch_state?.selected_branch)return Response.json({error:'Quest branch state changed. Refresh and try again.'},{status:409});const definition=await base44.asServiceRole.entities.QuestDefinition.get(quest.definition_id),graph=definition.objective_graph||{},branch=(graph.branches||[]).find((item:any)=>item.key===branchKey);if(!branch)return Response.json({error:'That quest branch is unavailable.'},{status:422});const rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200),states=new Map(rows.map(row=>[row.objective_key,row.state]));if((branch.dependsOn||[]).some((key:string)=>states.get(key)!=='COMPLETED'))return Response.json({error:'That quest branch is still locked.'},{status:422});const selected=new Set(branch.objectiveKeys||[]),allBranchKeys=new Set((graph.branches||[]).flatMap((item:any)=>item.objectiveKeys||[])),updates=rows.filter(row=>allBranchKeys.has(row.objective_key)).map(row=>({id:row.id,state:selected.has(row.objective_key)?(canActivate((graph.objectives||[]).find((item:any)=>item.key===row.objective_key),states,graph,{selected_branch:branchKey})?'ACTIVE':'PENDING'):'SKIPPED',version:row.version+1}));if(updates.length)await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(updates);const updated=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{branch_state:{selected_branch:branchKey},version:quest.version+1});await recordQuestHistory(base44,character,updated,'branch_selected',`Selected quest path ${branch.label||branchKey}.`,{branch_key:branchKey,dedupe_key:`${quest.id}:branch:${branchKey}`},requestId);await publishQuestEvent(base44,character,'quest.branch.selected','quest',quest.id,requestId,{definition_id:definition.id,branch_key:branchKey});return null;}
export async function claimQuestReward(base44:any,character:any,questId:string,questVersion:number,choiceKey:string){let quest=await base44.asServiceRole.entities.QuestInstance.get(questId);if(quest.character_id!==character.id)return Response.json({error:'Quest ownership could not be verified.'},{status:403});if(quest.state!=='COMPLETED'||!['pending','granting'].includes(quest.reward_state)||quest.reward_state==='pending'&&quest.version!==questVersion)return Response.json({error:'Quest reward state changed. Refresh and try again.'},{status:409});const definition=await base44.asServiceRole.entities.QuestDefinition.get(quest.definition_id),selectedKey=quest.branch_state?.reward_choice||choiceKey,choice=(definition.reward_selection?.choices||[]).find((item:any)=>item.key===selectedKey);if(!choice||quest.branch_state?.reward_choice&&quest.branch_state.reward_choice!==choiceKey)return Response.json({error:'That reward choice is unavailable.'},{status:422});if(quest.reward_state==='pending')quest=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{reward_state:'granting',branch_state:{...(quest.branch_state||{}),reward_choice:selectedKey},version:Number(quest.version||1)+1});await grantRewards(base44,character,{...definition,rewards:[...(definition.rewards||[]),...(choice.rewards||[])]},`quest:${quest.id}:choice:${selectedKey}`);const granted=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{reward_state:'granted',version:Number(quest.version||1)+1});await recordQuestHistory(base44,character,granted,'reward_claimed',`Claimed reward choice ${choice.label||selectedKey}.`,{choice_key:selectedKey,dedupe_key:`${quest.id}:reward:${selectedKey}`});return null;}
export async function publishQuestEvent(base44:any,character:any,eventType:string,aggregateType:string,aggregateId:string,requestId:string,payload:any={}){const event=await publishDomainEvent(base44,characterEventInput(character,eventType,aggregateType,aggregateId,requestId,payload));await processQuestEvent(base44,character,event);const emitted=await processWorldSignals(base44,character,{event});for(const generated of emitted)await processQuestEvent(base44,await base44.asServiceRole.entities.Character.get(character.id),generated);return event;}
export function validateObjectiveGraph(graph:any){if(!graph||!Array.isArray(graph.objectives))return 'Objective graph must contain an objectives array.';const keys=new Set<string>();for(const objective of graph.objectives){if(!objective.key)return 'Every objective requires a key.';if(keys.has(objective.key))return `Duplicate objective key ${objective.key}.`;keys.add(objective.key);if(!objectiveTypes.includes(objective.type))return `Unsupported objective type ${objective.type}.`;}for(const objective of graph.objectives){for(const dependency of objective.dependsOn||[])if(!keys.has(dependency))return `Objective ${objective.key} depends on missing objective ${dependency}.`;for(const reference of [objective.replacementFor,objective.replacementObjectiveKey].filter(Boolean))if(!keys.has(reference))return `Objective ${objective.key} references missing replacement objective ${reference}.`;if(objective.replacementObjectiveKey===objective.key)return `Objective ${objective.key} cannot replace itself.`;for(const condition of [objective.activationCondition,objective.failureCondition])if(condition!==undefined&&(!condition||typeof condition!=='object'||Array.isArray(condition)))return `Objective ${objective.key} has an invalid lifecycle condition.`;}for(const key of graph.sequence||[])if(!keys.has(key))return `Quest sequence references missing objective ${key}.`;const branchKeys=new Set<string>(),assigned=new Set<string>();for(const branch of graph.branches||[]){if(!branch.key)return 'Every quest branch requires a key.';if(branchKeys.has(branch.key))return `Duplicate quest branch key ${branch.key}.`;branchKeys.add(branch.key);if(!(branch.objectiveKeys||[]).length)return `Quest branch ${branch.key} requires at least one objective.`;for(const key of [...(branch.objectiveKeys||[]),...(branch.dependsOn||[])])if(!keys.has(key))return `Quest branch ${branch.key} references missing objective ${key}.`;for(const key of branch.objectiveKeys||[]){if(assigned.has(key))return `Objective ${key} belongs to more than one branch.`;assigned.add(key);}}const dependencies=new Map((graph.objectives||[]).map((item:any)=>[item.key,item.dependsOn||[]])),visiting=new Set<string>(),visited=new Set<string>();const walk=(key:string):boolean=>{if(visiting.has(key))return true;if(visited.has(key))return false;visiting.add(key);for(const dependency of dependencies.get(key)||[])if(walk(dependency))return true;visiting.delete(key);visited.add(key);return false;};for(const key of keys)if(walk(key))return `Quest objective dependencies contain a cycle at ${key}.`;return null;}
export function validateRewardSelection(selection:any){if(!selection||!Object.keys(selection).length)return null;if(!Array.isArray(selection.choices)||!selection.choices.length)return 'Reward selection requires a non-empty choices array.';const keys=new Set<string>();for(const choice of selection.choices){if(!choice.key||!choice.label)return 'Every reward choice requires a key and label.';if(keys.has(choice.key))return `Duplicate reward choice key ${choice.key}.`;keys.add(choice.key);if(!Array.isArray(choice.rewards))return `Reward choice ${choice.key} requires a rewards array.`;}return null;}