import { evaluateCondition } from './rules.ts';
const objectiveTypes=['visitLocation','interactWithEntity','acquireItem','loseItem','deliverItem','defeatEntity','surviveEncounter','useAbility','reachAttributeThreshold','selectDialogueResponse','completeQuest','customEvent','satisfyCondition'];
const targetMatches=(objective:any,value:any)=>!objective.targetId||objective.targetId===value;
async function matches(base44:any,character:any,objective:any,event:any){
  const payload=event.payload||{},type=objective.type;
  if(objective.eventType&&objective.eventType!==event.event_type)return false;
  if(type==='visitLocation')return event.event_type==='character.location.entered'&&targetMatches(objective,payload.location_id||payload.to);
  if(type==='interactWithEntity')return ['npc.interaction.started','npc.interaction.completed'].includes(event.event_type)&&targetMatches(objective,payload.npc_definition_id||payload.npc_instance_id);
  if(type==='acquireItem')return event.event_type==='inventory.item.added'&&targetMatches(objective,payload.item_definition_id);
  if(type==='loseItem'||type==='deliverItem')return ['inventory.item.removed','inventory.item.delivered'].includes(event.event_type)&&targetMatches(objective,payload.item_definition_id);
  if(type==='defeatEntity')return event.event_type==='combat.entity.defeated'&&targetMatches(objective,payload.entity_definition_id);
  if(type==='surviveEncounter')return event.event_type==='combat.encounter.won'&&targetMatches(objective,payload.encounter_definition_id);
  if(type==='useAbility')return event.event_type==='combat.ability.used'&&targetMatches(objective,payload.ability_id);
  if(type==='selectDialogueResponse')return event.event_type==='dialogue.option.selected'&&targetMatches(objective,payload.option_key);
  if(type==='completeQuest')return event.event_type==='quest.completed'&&targetMatches(objective,payload.definition_id);
  if(type==='customEvent')return event.event_type===(objective.eventType||objective.targetId);
  if(type==='reachAttributeThreshold')return Number(character.attributes?.[objective.attributeId||objective.targetId]||0)>=Number(objective.value||objective.count||1);
  if(type==='satisfyCondition')return await evaluateCondition(base44,{character,event},objective.condition||{});
  return false;
}
function graphNodeComplete(node:any,states:Map<string,string>):boolean{if(typeof node==='string')return states.get(node)==='COMPLETED';if(!node)return false;if(node.objective)return states.get(node.objective)==='COMPLETED';if(Array.isArray(node.all))return node.all.every((child:any)=>graphNodeComplete(child,states));if(Array.isArray(node.any))return node.any.some((child:any)=>graphNodeComplete(child,states));if(Array.isArray(node.sequence))return node.sequence.every((child:any)=>graphNodeComplete(child,states));return false;}
function questComplete(graph:any,rows:any[]){const states=new Map(rows.map(row=>[row.objective_key,row.state]));if(graph.root)return graphNodeComplete(graph.root,states);return rows.filter(row=>!row.optional).every(row=>row.state==='COMPLETED');}
function canActivate(definition:any,states:Map<string,string>,graph:any){if((definition.dependsOn||[]).some((key:string)=>states.get(key)!=='COMPLETED'))return false;const sequence=graph.sequence||(graph.mode==='sequence'?(graph.objectives||[]).map((item:any)=>item.key):[]);const index=sequence.indexOf(definition.key);return index<0||sequence.slice(0,index).every((key:string)=>states.get(key)==='COMPLETED');}
export function createObjectiveRows(definition:any,instance:any,character:any){const graph=definition.objective_graph||{},objectives=graph.objectives||[],states=new Map(objectives.map((objective:any)=>[objective.key,'PENDING']));return objectives.map((objective:any)=>{const active=canActivate(objective,states,graph);if(active)states.set(objective.key,'ACTIVE');return {game_id:character.game_id,quest_instance_id:instance.id,character_id:character.id,objective_key:objective.key,objective_type:objective.type,target_id:objective.targetId||'',required_count:Number(objective.count||1),current_count:0,state:active?'ACTIVE':'PENDING',optional:!!objective.optional,processed_event_ids:[],version:1};});}
async function grantRewards(base44:any,character:any,definition:any){
  const fresh=await base44.asServiceRole.entities.Character.get(character.id),currency={...(fresh.currency||{})},resources={...(fresh.resources||{})},itemRewards:any[]=[],stateRewards:any[]=[];
  for(const reward of definition.rewards||[]){if(reward.type==='currency'){currency[reward.currencyId]=(currency[reward.currencyId]||0)+Number(reward.amount||0);stateRewards.push(reward);}else if(reward.type==='resourceChange'){resources[reward.resourceId]=Math.max(0,(resources[reward.resourceId]||0)+Number(reward.amount||0));stateRewards.push(reward);}else if(reward.type==='item')itemRewards.push(reward);}
  if(stateRewards.length)await base44.asServiceRole.entities.Character.update(fresh.id,{currency,resources,version:fresh.version+1});
  if(itemRewards.length){const containers=await base44.asServiceRole.entities.Container.filter({character_id:fresh.id},'created_date',1),container=containers[0];if(container){const created=await base44.asServiceRole.entities.ItemInstance.bulkCreate(itemRewards.map(reward=>({game_id:fresh.game_id,content_version:fresh.content_version,definition_id:reward.itemDefinitionId,container_id:container.id,character_id:fresh.id,quantity:Number(reward.quantity||1),quality:'standard',bound_state:'unbound',custom_properties:{},applied_modifications:[],acquired_at:new Date().toISOString(),version:1})));for(const item of created)await publishQuestEvent(base44,fresh,'inventory.item.added','item',item.id,`quest-reward:${item.id}`,{item_definition_id:item.definition_id,quantity:item.quantity});}}
}
async function failQuest(base44:any,quest:any,rows:any[]){const active=rows.filter(row=>row.state==='ACTIVE'||row.state==='PENDING');if(active.length)await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(active.map(row=>({id:row.id,state:'FAILED',version:row.version+1})));await base44.asServiceRole.entities.QuestInstance.update(quest.id,{state:'FAILED',failed_at:new Date().toISOString(),reward_state:'none',version:quest.version+1});}
export async function processQuestEvent(base44:any,character:any,event:any){
  const quests=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,state:'ACTIVE'},'-accepted_at',100);
  for(const quest of quests){const definition=await base44.asServiceRole.entities.QuestDefinition.get(quest.definition_id),now=Date.now(),expired=quest.expires_at&&new Date(quest.expires_at).getTime()<=now,failureRules=definition.failure_rules||{},failed=Object.keys(failureRules).length>0&&await evaluateCondition(base44,{character,event},failureRules);if(expired||failed){await failQuest(base44,quest,await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200));continue;}
    let rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200),changed=false;
    for(const row of rows.filter(item=>item.state==='ACTIVE'&&!(item.processed_event_ids||[]).includes(event.id))){const objective=(definition.objective_graph?.objectives||[]).find((item:any)=>item.key===row.objective_key);if(!objective||!await matches(base44,character,objective,event))continue;const increment=Number(event.payload?.quantity||event.payload?.count||1),current=Math.min(row.required_count,Number(row.current_count||0)+Math.max(1,increment));await base44.asServiceRole.entities.ObjectiveInstance.update(row.id,{current_count:current,state:current>=row.required_count?'COMPLETED':'ACTIVE',processed_event_ids:[...(row.processed_event_ids||[]),event.id],last_event_at:event.occurred_at,version:row.version+1});changed=true;}
    if(changed){rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200);const states=new Map(rows.map(row=>[row.objective_key,row.state])),pending=rows.filter(row=>row.state==='PENDING').filter(row=>{const objective=(definition.objective_graph?.objectives||[]).find((item:any)=>item.key===row.objective_key);return objective&&canActivate(objective,states,definition.objective_graph||{});});if(pending.length){await base44.asServiceRole.entities.ObjectiveInstance.bulkUpdate(pending.map(row=>({id:row.id,state:'ACTIVE',version:row.version+1})));rows=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:quest.id},'objective_key',200);}}
    const completionRules=definition.completion_rules||{},completionAllowed=!Object.keys(completionRules).length||completionRules.allRequired===true||await evaluateCondition(base44,{character,event},completionRules);if(questComplete(definition.objective_graph||{},rows)&&completionAllowed){const completed=await base44.asServiceRole.entities.QuestInstance.update(quest.id,{state:'COMPLETED',completed_at:new Date().toISOString(),reward_state:'granted',version:quest.version+1});await grantRewards(base44,character,definition);await publishQuestEvent(base44,character,'quest.completed','quest',completed.id,`${event.request_id}:quest:${quest.id}`,{definition_id:definition.id,quest_key:definition.key});}
  }
}
export async function publishQuestEvent(base44:any,character:any,eventType:string,aggregateType:string,aggregateId:string,requestId:string,payload:any={}){const existing=await base44.asServiceRole.entities.DomainEvent.filter({character_id:character.id,event_type:eventType,request_id:requestId},'-occurred_at',1);const event=existing[0]||await base44.asServiceRole.entities.DomainEvent.create({game_id:character.game_id,character_id:character.id,event_type:eventType,aggregate_type:aggregateType,aggregate_id:aggregateId,request_id:requestId,content_version:character.content_version,payload,occurred_at:new Date().toISOString()});await processQuestEvent(base44,character,event);return event;}
export function validateObjectiveGraph(graph:any){if(!graph||!Array.isArray(graph.objectives))return 'Objective graph must contain an objectives array.';const keys=new Set<string>();for(const objective of graph.objectives){if(!objective.key)return 'Every objective requires a key.';if(keys.has(objective.key))return `Duplicate objective key ${objective.key}.`;keys.add(objective.key);if(!objectiveTypes.includes(objective.type))return `Unsupported objective type ${objective.type}.`;}for(const objective of graph.objectives)for(const dependency of objective.dependsOn||[])if(!keys.has(dependency))return `Objective ${objective.key} depends on missing objective ${dependency}.`;for(const key of graph.sequence||[])if(!keys.has(key))return `Quest sequence references missing objective ${key}.`;return null;}