type FieldType='string'|'number'|'boolean'|'object'|'array'|'any';
type RuleDescriptor={type:string,fields?:Record<string,FieldType>,required?:string[],targets?:string[]};
const conditionDescriptors:RuleDescriptor[]=[
  {type:'hasTag',required:['tag'],fields:{tag:'string',subject:'string'}},{type:'attributeAtLeast',required:['attributeId','value'],fields:{attributeId:'string',value:'number'}},{type:'resourceAtLeast',required:['resourceId','value'],fields:{resourceId:'string',value:'number'}},{type:'locationIs',fields:{locationId:'string',locationKey:'string'}},{type:'compare',required:['left','right'],fields:{left:'object',right:'object',operator:'string'}},{type:'questState',required:['questKey','state'],fields:{questKey:'string',state:'string'}},{type:'hasItem',required:['itemKey'],fields:{itemKey:'string',quantity:'number'}},{type:'hasStatus',required:['statusKey'],fields:{statusKey:'string'}},{type:'relationshipAtLeast',required:['value'],fields:{relationshipKey:'string',value:'number'}},{type:'relationshipHasTag',required:['tag'],fields:{tag:'string'}},{type:'knowledgeBelief',required:['propositionKey'],fields:{propositionKey:'string',minConfidence:'number',value:'any'}},{type:'npcMemory',required:['memoryKey'],fields:{memoryKey:'string',minSalience:'number'}},{type:'reputationAtLeast',required:['factionKey','value'],fields:{factionKey:'string',dimensionKey:'string',value:'number'}},{type:'legalStandingIs',required:['jurisdictionKey','status'],fields:{jurisdictionKey:'string',status:'string'}},{type:'factionStateAtLeast',required:['factionKey','stateKey','value'],fields:{factionKey:'string',stateKey:'string',value:'number'}},{type:'timePhaseIs',required:['phase'],fields:{phase:'string'}},{type:'weatherIs',fields:{weatherKey:'string',tag:'string'}},{type:'variable',required:['key','operator'],fields:{namespace:'string',key:'string',operator:'string',value:'any'}},{type:'locationAccessIs',required:['access'],fields:{access:'string'}},{type:'featureDiscovered',required:['featureKey'],fields:{featureKey:'string'}},{type:'featureAccessIs',required:['featureKey','access'],fields:{featureKey:'string',access:'string'}},{type:'featureDamageAtLeast',required:['featureKey','value'],fields:{featureKey:'string',value:'number'}}
];
const effectDescriptors:RuleDescriptor[]=[
  {type:'damage',required:['amount'],fields:{amount:'object'}},{type:'healing',required:['amount'],fields:{amount:'object'}},{type:'resourceChange',required:['resourceId','amount'],fields:{resourceId:'string',amount:'object'}},{type:'currencyChange',required:['currencyId','amount'],fields:{currencyId:'string',amount:'object'}},{type:'modifyAttribute',required:['attributeId','amount'],fields:{attributeId:'string',amount:'object'}},{type:'setResource',required:['resourceId','amount'],fields:{resourceId:'string',amount:'object'}},{type:'addTag',required:['tag'],fields:{tag:'string',scope:'string'}},{type:'removeTag',required:['tag'],fields:{tag:'string',scope:'string'}},{type:'applyStatus',required:['statusKey'],fields:{statusKey:'string',stacks:'number'}},{type:'removeStatus',required:['statusKey'],fields:{statusKey:'string'}},{type:'relationshipChange',required:['amount'],fields:{relationshipKey:'string',amount:'number'}},{type:'remember',required:['memoryKey','summary'],fields:{memoryKey:'string',summary:'string',facts:'object',salience:'number',valence:'number',decayMinutes:'number'}},{type:'learnKnowledge',required:['propositionKey','believedValue'],fields:{knowerType:'string',knowerId:'string',propositionKey:'string',believedValue:'any',confidence:'number',veracity:'string',expiresMinutes:'number'}},{type:'createRumor',fields:{definitionKey:'string',propositionKey:'string',payload:'object',accuracy:'number',strength:'number',spreadIntervalMinutes:'number'}},{type:'reputationChange',required:['factionKey','amount'],fields:{factionKey:'string',dimensionKey:'string',amount:'number',reasonKey:'string'}},{type:'commitCrime',required:['crimeKey'],fields:{crimeKey:'string',jurisdictionKey:'string',severity:'number'}},{type:'startFactionOperation',required:['definitionKey'],fields:{definitionKey:'string'}},{type:'setVariable',required:['key','value'],fields:{namespace:'string',key:'string',value:'any'}},{type:'incrementVariable',required:['key','amount'],fields:{namespace:'string',key:'string',amount:'object'}},{type:'removeVariable',required:['key'],fields:{namespace:'string',key:'string'}},{type:'locationDamage',required:['amount'],fields:{amount:'object'}},{type:'setLocationAccess',required:['access'],fields:{access:'string'}},{type:'setLocationOwner',fields:{ownerType:'string',ownerId:'string'}},{type:'featureDamage',required:['featureKey','amount'],fields:{featureKey:'string',amount:'object'}},{type:'setFeatureAccess',required:['featureKey','access'],fields:{featureKey:'string',access:'string'}},{type:'setFeatureOwner',required:['featureKey'],fields:{featureKey:'string',ownerType:'string',ownerId:'string'}},{type:'discoverFeature',required:['featureKey'],fields:{featureKey:'string'}},{type:'setFeatureSearchState',required:['featureKey','searchState'],fields:{featureKey:'string',searchState:'string'}},{type:'transformItem',required:['outputItemDefinitionId'],fields:{itemRole:'string',outputItemDefinitionId:'string',quantity:'number'}}
];
export const conditionRegistry=new Map(conditionDescriptors.map(item=>[item.type,item]));
export const effectRegistry=new Map(effectDescriptors.map(item=>[item.type,item]));
export const conditionTypeNames=[...conditionRegistry.keys()];
export const effectTypeNames=[...effectRegistry.keys()];
const matches=(value:any,type:FieldType)=>type==='any'||type==='array'?type==='any'||Array.isArray(value):type==='object'?value!==null&&typeof value==='object':typeof value===type;
function validate(registry:Map<string,RuleDescriptor>,rule:any,kind:string){if(!rule||typeof rule!=='object'||Array.isArray(rule))return `${kind} must be an object.`;const descriptor=registry.get(rule.type);if(!descriptor)return `Unsupported ${kind.toLowerCase()} type ${rule.type}.`;for(const field of descriptor.required||[])if(rule[field]===undefined||field!=='value'&&(rule[field]===null||rule[field]===''))return `${rule.type}.${field} is required.`;for(const [field,type] of Object.entries(descriptor.fields||{}))if(rule[field]!==undefined&&!matches(rule[field],type)&&!(type==='object'&&typeof rule[field]==='number'))return `${rule.type}.${field} must be a ${type}.`;if(rule.type==='variable'&&!['eq','neq','gt','gte','lt','lte','exists','not_exists'].includes(rule.operator))return 'variable.operator is unsupported.';if(rule.type==='compare'&&rule.operator&&!['eq','neq','gt','gte','lt','lte'].includes(rule.operator))return 'compare.operator is unsupported.';if(['setLocationAccess','setFeatureAccess'].includes(rule.type)&&!['open','restricted','locked'].includes(rule.access))return `${rule.type}.access is unsupported.`;if(rule.type==='setFeatureSearchState'&&!['unsearched','searched','depleted'].includes(rule.searchState))return 'setFeatureSearchState.searchState is unsupported.';if(rule.type==='transformItem'&&rule.quantity!==undefined&&(!Number.isInteger(rule.quantity)||rule.quantity<1))return 'transformItem.quantity must be a positive integer.';if(rule.type==='legalStandingIs'&&!['clear','suspected','wanted','convicted','pardoned'].includes(rule.status))return 'legalStandingIs.status is unsupported.';if(rule.type==='learnKnowledge'&&rule.confidence!==undefined&&(rule.confidence<0||rule.confidence>1))return 'learnKnowledge.confidence must be from 0 to 1.';return null;}
export const validateRegisteredCondition=(condition:any)=>validate(conditionRegistry,condition,'Condition');
export const validateRegisteredEffect=(effect:any)=>validate(effectRegistry,effect,'Effect');
export function publicRuleRegistry(){return {conditions:conditionDescriptors,effects:effectDescriptors};}