type FieldType='string'|'number'|'boolean'|'object'|'array';
type RuleDescriptor={type:string,fields?:Record<string,FieldType>,required?:string[],targets?:string[]};
const conditionDescriptors:RuleDescriptor[]=[
  {type:'hasTag',required:['tag'],fields:{tag:'string',subject:'string'}},{type:'attributeAtLeast',required:['attributeId','value'],fields:{attributeId:'string',value:'number'}},{type:'resourceAtLeast',required:['resourceId','value'],fields:{resourceId:'string',value:'number'}},{type:'locationIs',fields:{locationId:'string',locationKey:'string'}},{type:'compare',required:['left','right'],fields:{left:'object',right:'object',operator:'string'}},{type:'questState',required:['questKey','state'],fields:{questKey:'string',state:'string'}},{type:'hasItem',required:['itemKey'],fields:{itemKey:'string',quantity:'number'}},{type:'hasStatus',required:['statusKey'],fields:{statusKey:'string'}},{type:'relationshipAtLeast',required:['value'],fields:{relationshipKey:'string',value:'number'}},{type:'relationshipHasTag',required:['tag'],fields:{tag:'string'}},{type:'timePhaseIs',required:['phase'],fields:{phase:'string'}},{type:'weatherIs',fields:{weatherKey:'string',tag:'string'}},{type:'variable',required:['key','operator'],fields:{namespace:'string',key:'string',operator:'string'}}
];
const effectDescriptors:RuleDescriptor[]=[
  {type:'damage',required:['amount'],fields:{amount:'object'}},{type:'healing',required:['amount'],fields:{amount:'object'}},{type:'resourceChange',required:['resourceId','amount'],fields:{resourceId:'string',amount:'object'}},{type:'currencyChange',required:['currencyId','amount'],fields:{currencyId:'string',amount:'object'}},{type:'modifyAttribute',required:['attributeId','amount'],fields:{attributeId:'string',amount:'object'}},{type:'setResource',required:['resourceId','amount'],fields:{resourceId:'string',amount:'object'}},{type:'addTag',required:['tag'],fields:{tag:'string',scope:'string'}},{type:'removeTag',required:['tag'],fields:{tag:'string',scope:'string'}},{type:'applyStatus',required:['statusKey'],fields:{statusKey:'string',stacks:'number'}},{type:'removeStatus',required:['statusKey'],fields:{statusKey:'string'}},{type:'relationshipChange',required:['amount'],fields:{relationshipKey:'string',amount:'number'}},{type:'setVariable',required:['key','value'],fields:{namespace:'string',key:'string'}},{type:'incrementVariable',required:['key','amount'],fields:{namespace:'string',key:'string',amount:'object'}},{type:'removeVariable',required:['key'],fields:{namespace:'string',key:'string'}}
];
export const conditionRegistry=new Map(conditionDescriptors.map(item=>[item.type,item]));
export const effectRegistry=new Map(effectDescriptors.map(item=>[item.type,item]));
export const conditionTypeNames=[...conditionRegistry.keys()];
export const effectTypeNames=[...effectRegistry.keys()];
const matches=(value:any,type:FieldType)=>type==='array'?Array.isArray(value):type==='object'?value!==null&&typeof value==='object':typeof value===type;
function validate(registry:Map<string,RuleDescriptor>,rule:any,kind:string){if(!rule||typeof rule!=='object'||Array.isArray(rule))return `${kind} must be an object.`;const descriptor=registry.get(rule.type);if(!descriptor)return `Unsupported ${kind.toLowerCase()} type ${rule.type}.`;for(const field of descriptor.required||[])if(rule[field]===undefined||field!=='value'&&(rule[field]===null||rule[field]===''))return `${rule.type}.${field} is required.`;for(const [field,type] of Object.entries(descriptor.fields||{}))if(rule[field]!==undefined&&!matches(rule[field],type)&&!(type==='object'&&typeof rule[field]==='number'))return `${rule.type}.${field} must be a ${type}.`;return null;}
export const validateRegisteredCondition=(condition:any)=>validate(conditionRegistry,condition,'Condition');
export const validateRegisteredEffect=(effect:any)=>validate(effectRegistry,effect,'Effect');
export function publicRuleRegistry(){return {conditions:conditionDescriptors,effects:effectDescriptors};}