import { evaluateCondition, resolveCharacterEffects } from './rules.ts';
import { loadVisibleNpcs } from './dialogue.ts';
import { isMovementLocked, movePartyWithLeader } from './party.ts';
import { claimQuestReward, createObjectiveRows, publishQuestEvent, refreshQuestProgress, selectQuestBranch } from './quests.ts';
import { handleInventoryCommand } from './inventory.ts';

async function loadInventory(base44:any,user:any,characterId:string){
  const character=await base44.entities.Character.get(characterId);
  const [containers,items,inventoryEvents]=await Promise.all([
    base44.asServiceRole.entities.Container.filter({character_id:character.id},'name',30),
    base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id},'-acquired_at',200),
    base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,character_id:character.id,result:'accepted'},'-occurred_at',200)
  ]);
  const definitionIds=[...new Set(items.map((item:any)=>item.definition_id))];
  const definitions=await Promise.all(definitionIds.map((id:any)=>base44.asServiceRole.entities.ItemDefinition.get(id)));
  const abilityIds=[...new Set(definitions.flatMap((definition:any)=>definition.granted_ability_ids||[]))];
  const abilities=await Promise.all(abilityIds.map((id:any)=>base44.asServiceRole.entities.AbilityDefinition.get(id)));
  const requirementResults=await Promise.all(definitions.map((definition:any)=>evaluateCondition(base44,{character},definition.requirements)));
  const rows=items.map((item:any)=>{const definitionIndex=definitions.findIndex((current:any)=>current.id===item.definition_id),definition=definitions[definitionIndex];return {...item,definition,requirements_met:requirementResults[definitionIndex],granted_abilities:(definition.granted_ability_ids||[]).map((id:string)=>abilities.find((ability:any)=>ability.id===id)).filter(Boolean),container:containers.find((container:any)=>container.id===item.container_id)||null,history:inventoryEvents.filter((event:any)=>event.details?.item_id===item.id||event.details?.item_ids?.includes(item.id)).slice(0,12)};});
  const carried=rows.filter((item:any)=>item.container?.container_type!=='loot'),loot=rows.filter((item:any)=>item.container?.container_type==='loot');
  const weight=carried.reduce((sum:number,item:any)=>sum+(item.definition.weight||0)*item.quantity,0),lootWeight=loot.reduce((sum:number,item:any)=>sum+(item.definition.weight||0)*item.quantity,0),capacity=containers.filter((container:any)=>container.container_type!=='loot').reduce((sum:number,container:any)=>sum+(container.capacity||0),0);
  return {character,containers,items:rows,summary:{weight,capacity,lootWeight,canCollectLoot:capacity<=0||weight+lootWeight<=capacity,equipped:carried.filter((item:any)=>item.equipped_slot).length,loot:loot.reduce((sum:number,item:any)=>sum+item.quantity,0)}};
}

async function loadQuests(base44:any,characterId:string){
  const character=await base44.entities.Character.get(characterId);
  await refreshQuestProgress(base44,character);
  const currentDefinitions=await base44.asServiceRole.entities.QuestDefinition.filter({game_id:character.game_id,content_version:character.content_version},'name',100),instances=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id},'-updated_date',100);
  const missingIds=[...new Set(instances.map((instance:any)=>instance.definition_id).filter((id:string)=>!currentDefinitions.some((definition:any)=>definition.id===id)))];
  const legacyDefinitions=await Promise.all(missingIds.map((id:any)=>base44.asServiceRole.entities.QuestDefinition.get(id))),definitions=[...currentDefinitions,...legacyDefinitions];
  const rows=await Promise.all(instances.map(async(instance:any)=>{const definition=definitions.find((item:any)=>item.id===instance.definition_id),objectives=await base44.asServiceRole.entities.ObjectiveInstance.filter({quest_instance_id:instance.id},'objective_key',100);return {...instance,definition,objectives:objectives.map((objective:any)=>({...objective,label:definition?.objective_graph?.objectives?.find((item:any)=>item.key===objective.objective_key)?.label||objective.objective_key}))};}));
  const instancedIds=new Set(instances.filter((instance:any)=>instance.state!=='ABANDONED').map((instance:any)=>instance.definition_id)),availability=await Promise.all(currentDefinitions.map((definition:any)=>evaluateCondition(base44,{character},definition.availability_conditions))),availableDefinitions=currentDefinitions.filter((definition:any,index:number)=>availability[index]);
  return {character,available:availableDefinitions.filter((definition:any)=>!instancedIds.has(definition.id)),quests:rows};
}

async function loadState(base44:any,user:any,characterId?:string){
  const characters=await base44.entities.Character.list('-updated_date',20),games=await base44.asServiceRole.entities.Game.filter({status:'published'},'title',20),selected=characters.find((item:any)=>item.id===characterId)||characters[0]||null;
  if(!selected)return {games,game:games[0]||null,characters,character:null,location:null,exits:[],npcs:[],activity:[]};
  const game=games.find((item:any)=>item.id===selected.game_id)||null,location=await base44.asServiceRole.entities.LocationDefinition.get(selected.current_location_id);
  const [forwardLinks,reverseLinks]=await Promise.all([base44.asServiceRole.entities.Connection.filter({from_location_id:selected.current_location_id,content_version:selected.content_version,enabled:true},'label',30),base44.asServiceRole.entities.Connection.filter({to_location_id:selected.current_location_id,content_version:selected.content_version,enabled:true,one_way:false},'label',30)]);
  const reverseOnly=reverseLinks.filter((link:any)=>!forwardLinks.some((forward:any)=>forward.to_location_id===link.from_location_id)),links=[...forwardLinks,...reverseOnly.map((link:any)=>({...link,to_location_id:link.from_location_id,from_location_id:selected.current_location_id,reverse:true}))],destinations=await Promise.all(links.map((link:any)=>base44.asServiceRole.entities.LocationDefinition.get(link.to_location_id))),exits=links.map((link:any,index:number)=>({...link,destination:destinations[index]}));
  const [npcs,activity]=await Promise.all([loadVisibleNpcs(base44,selected),base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,character_id:selected.id,result:'accepted'},'-occurred_at',8)]);
  return {games,game,characters,character:selected,location,exits,npcs,activity};
}

async function studioOverview(base44:any,user:any){
  if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  const [games,releases,packs,locations,connections,quests,encounters,characters]=await Promise.all([base44.asServiceRole.entities.Game.list(),base44.asServiceRole.entities.ContentRelease.list('-created_date',50),base44.asServiceRole.entities.ContentPack.list('-created_date',100),base44.asServiceRole.entities.LocationDefinition.list(),base44.asServiceRole.entities.Connection.list(),base44.asServiceRole.entities.QuestDefinition.list(),base44.asServiceRole.entities.EncounterDefinition.list(),base44.asServiceRole.entities.Character.list('-updated_date',100)]);
  return Response.json({games,releases,packs,characters,counts:{games:games.length,releases:releases.length,packs:packs.length,locations:locations.length,connections:connections.length,quests:quests.length,encounters:encounters.length}});
}

export async function handleRuntimeCommand(base44:any,user:any,body:any,requestId:string){
  const command=body.command;
  if(command==='STUDIO_OVERVIEW')return studioOverview(base44,user);
  if(command==='CREATE_CHARACTER'){
    const game=await base44.asServiceRole.entities.Game.get(body.gameId),release=(await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',1))[0];
    if(!release)return Response.json({error:'This game has no published content.'},{status:409});
    const start=(await base44.asServiceRole.entities.LocationDefinition.filter({game_id:game.id,content_version:release.version,tags:{'$in':['start']}},'-created_date',1))[0];
    if(!start)return Response.json({error:'This game has no starting location.'},{status:409});
    const definitions=await base44.asServiceRole.entities.AttributeDefinition.filter({game_id:game.id,content_version:release.version},'name',200),definedAttributes=Object.fromEntries(definitions.filter((item:any)=>item.category!=='resource').map((item:any)=>[item.key,item.default_value])),definedResources=Object.fromEntries(definitions.filter((item:any)=>item.category==='resource').map((item:any)=>[item.key,item.default_value])),defaults=game.character_defaults||{},rules=game.rules||{};
    const character=await base44.entities.Character.create({game_id:game.id,content_version:release.version,name:String(body.name||'').trim(),current_location_id:start.id,attributes:{...definedAttributes,...(defaults.attributes||{})},resources:{...definedResources,...(defaults.resources||{})},currency:defaults.currency||{},tags:defaults.tags||[],version:1});
    const container=await base44.asServiceRole.entities.Container.create({game_id:game.id,character_id:character.id,name:'Carried items',container_type:'character',capacity:Number(rules.inventory_capacity||0),version:1}),starters=await base44.asServiceRole.entities.ItemDefinition.filter({game_id:game.id,content_version:release.version,tags:{'$in':['starter']}},'name',20);
    if(starters.length)await base44.asServiceRole.entities.ItemInstance.bulkCreate(starters.map((definition:any)=>({game_id:game.id,content_version:release.version,definition_id:definition.id,container_id:container.id,character_id:character.id,quantity:definition.stack_limit>1?Math.min(definition.stack_limit,Number(rules.starter_stack_quantity||1)):1,quality:'standard',bound_state:'unbound',custom_properties:{},applied_modifications:[],acquired_at:new Date().toISOString(),version:1})));
  }
  if(command==='GET_INVENTORY')return Response.json(await loadInventory(base44,user,body.characterId));
  if(['SPLIT_ITEM','MERGE_ITEM','TRANSFER_ITEM','BULK_TRANSFER_ITEMS','COLLECT_LOOT'].includes(command)){const character=await base44.entities.Character.get(body.characterId),result=await handleInventoryCommand(base44,user,character,body,requestId);if(result)return result;return Response.json(await loadInventory(base44,user,character.id));}
  if(command==='GET_QUESTS')return Response.json(await loadQuests(base44,body.characterId));
  if(['SELECT_QUEST_BRANCH','SELECT_QUEST_REWARD'].includes(command)){const character=await base44.entities.Character.get(body.characterId),result=command==='SELECT_QUEST_BRANCH'?await selectQuestBranch(base44,character,body.questInstanceId,body.questVersion,body.branchKey,requestId):await claimQuestReward(base44,character,body.questInstanceId,body.questVersion,body.choiceKey);if(result)return result;return Response.json(await loadQuests(base44,character.id));}
  if(command==='ACCEPT_QUEST'){
    const character=await base44.entities.Character.get(body.characterId),duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);
    if(!duplicate.length){const definition=await base44.asServiceRole.entities.QuestDefinition.get(body.questDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Quest content is not valid for this character.'},{status:422});if(!await evaluateCondition(base44,{character},definition.availability_conditions))return Response.json({error:'This character does not meet the quest requirements.'},{status:422});const existing=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,definition_id:definition.id},'-created_date',20);if(existing.some((instance:any)=>instance.state!=='ABANDONED')&&definition.repeatability==='never')return Response.json({error:'This quest cannot be accepted again.'},{status:409});const acceptedAt=new Date(),afterSeconds=Number(definition.expiration_rules?.afterSeconds||0),instance=await base44.asServiceRole.entities.QuestInstance.create({game_id:character.game_id,content_version:character.content_version,definition_id:definition.id,character_id:character.id,state:'ACTIVE',accepted_at:acceptedAt.toISOString(),expires_at:afterSeconds>0?new Date(acceptedAt.getTime()+afterSeconds*1000).toISOString():undefined,branch_state:{},reward_state:'pending',version:1}),objectiveRows=createObjectiveRows(definition,instance,character);if(objectiveRows.length)await base44.asServiceRole.entities.ObjectiveInstance.bulkCreate(objectiveRows);await publishQuestEvent(base44,character,'quest.accepted','quest',instance.id,requestId,{definition_id:definition.id});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details:{quest_instance_id:instance.id,definition_id:definition.id},occurred_at:new Date().toISOString()});await publishQuestEvent(base44,character,'character.location.entered','character',character.id,`${requestId}:initial-location`,{location_id:character.current_location_id,to:character.current_location_id});}
    return Response.json(await loadQuests(base44,character.id));
  }
  if(command==='ABANDON_QUEST'){const character=await base44.entities.Character.get(body.characterId),instance=await base44.asServiceRole.entities.QuestInstance.get(body.questInstanceId);if(instance.character_id!==character.id)return Response.json({error:'Quest ownership could not be verified.'},{status:403});if(instance.state!=='ACTIVE'||instance.version!==body.questVersion)return Response.json({error:'Quest state changed. Refresh and try again.'},{status:409});await base44.asServiceRole.entities.QuestInstance.update(instance.id,{state:'ABANDONED',reward_state:'none',version:instance.version+1});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details:{quest_instance_id:instance.id},occurred_at:new Date().toISOString()});return Response.json(await loadQuests(base44,character.id));}
  if(['EQUIP_ITEM','UNEQUIP_ITEM','USE_ITEM'].includes(command)){
    const character=await base44.entities.Character.get(body.characterId),duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);
    if(!duplicate.length){const item=await base44.asServiceRole.entities.ItemInstance.get(body.itemId);if(item.character_id!==character.id)return Response.json({error:'Item ownership could not be verified.'},{status:403});if(item.version!==body.itemVersion)return Response.json({error:'Item state changed. Refresh and try again.'},{status:409});const definition=await base44.asServiceRole.entities.ItemDefinition.get(item.definition_id);if(!await evaluateCondition(base44,{character},definition.requirements))return Response.json({error:'This character does not meet the item requirements.'},{status:422});if(command==='EQUIP_ITEM'){const slot=body.slot;if(!(definition.equipment_slots||[]).includes(slot))return Response.json({error:'That item cannot use the selected slot.'},{status:422});const equipped=await base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id,equipped_slot:slot},'-updated_date',20);if(equipped.length)await base44.asServiceRole.entities.ItemInstance.bulkUpdate(equipped.map((current:any)=>({id:current.id,equipped_slot:null,version:current.version+1})));await base44.asServiceRole.entities.ItemInstance.update(item.id,{equipped_slot:slot,version:item.version+1});}if(command==='UNEQUIP_ITEM')await base44.asServiceRole.entities.ItemInstance.update(item.id,{equipped_slot:null,version:item.version+1});if(command==='USE_ITEM'){if(!(definition.actions||[]).includes('use'))return Response.json({error:'This item is not usable.'},{status:422});const resolved=await resolveCharacterEffects(base44,character,definition.use_effects||[]);await base44.entities.Character.update(character.id,{...resolved.patch,version:character.version+1});if(item.quantity<=1)await base44.asServiceRole.entities.ItemInstance.delete(item.id);else await base44.asServiceRole.entities.ItemInstance.update(item.id,{quantity:item.quantity-1,version:item.version+1});await publishQuestEvent(base44,character,'inventory.item.used','item',item.id,requestId,{item_definition_id:definition.id,quantity:1});}await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details:{item_id:item.id,definition_id:definition.id,slot:body.slot||null},occurred_at:new Date().toISOString()});}
    return Response.json(await loadInventory(base44,user,character.id));
  }
  if(command==='MOVE_TO_LOCATION'){
    const duplicates=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1);
    if(!duplicates.length){const character=await base44.entities.Character.get(body.characterId);if(await isMovementLocked(base44,character))return Response.json({error:'Characters cannot move while their combat is unresolved.'},{status:409});if(character.version!==body.characterVersion)return Response.json({error:'Character state changed. Refresh and try again.'},{status:409});const [forwardRoutes,reverseRoutes]=await Promise.all([base44.asServiceRole.entities.Connection.filter({from_location_id:character.current_location_id,to_location_id:body.destinationId,content_version:character.content_version,enabled:true}),base44.asServiceRole.entities.Connection.filter({from_location_id:body.destinationId,to_location_id:character.current_location_id,content_version:character.content_version,enabled:true,one_way:false})]),connection=forwardRoutes[0]||reverseRoutes[0];if(!connection)return Response.json({error:'That route is not currently available.'},{status:422});const missingTags=(connection.required_tags||[]).filter((tag:string)=>!(character.tags||[]).includes(tag));if(missingTags.length||!await evaluateCondition(base44,{character},connection.conditions))return Response.json({error:'This character does not meet the route requirements.'},{status:422});const movedCharacters=await movePartyWithLeader(base44,character,body.destinationId);for(const movedCharacter of movedCharacters)await publishQuestEvent(base44,movedCharacter,'character.location.entered','character',movedCharacter.id,requestId,{from:movedCharacter.current_location_id,to:body.destinationId,location_id:body.destinationId});await base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details:{from:character.current_location_id,to:body.destinationId,travel_time:connection.travel_time},occurred_at:new Date().toISOString()});}
  }
  return Response.json(await loadState(base44,user,body.characterId));
}