export type EntityRef={type:string,id:string,version?:string|number};
const REF_TYPE=/^[A-Za-z][A-Za-z0-9_]{0,63}$/;
export function entityRef(type:string,id:string,version?:string|number):EntityRef{const ref:any={type:String(type||''),id:String(id||'')};if(version!==undefined&&version!==null)ref.version=version;assertEntityRef(ref);return ref;}
export function entityRefFrom(type:string,record:any):EntityRef{if(!record?.id)throw new Error(`Cannot create ${type} reference without an id.`);return entityRef(type,record.id,record.version??record.content_version);}
export function assertEntityRef(ref:any,label='EntityRef'){if(!ref||typeof ref!=='object'||!REF_TYPE.test(String(ref.type||''))||!String(ref.id||'').trim())throw new Error(`${label} requires a valid type and id.`);if(ref.version!==undefined&&!['string','number'].includes(typeof ref.version))throw new Error(`${label} version must be a string or number.`);return ref as EntityRef;}
export const entityRefKey=(ref:EntityRef)=>`${ref.type}:${ref.id}${ref.version===undefined?'':`@${ref.version}`}`;
export function definitionRefFor(instance:any,definitionType:string,idField='definition_id'){const id=instance?.definition_ref?.id||instance?.[idField];if(!id)throw new Error(`${definitionType} instance is missing its definition reference.`);return entityRef(definitionType,id,instance?.definition_ref?.version||instance?.content_version);}
export function assertDefinitionInstance(definition:any,instance:any,definitionType:string,idField='definition_id'){const ref=definitionRefFor(instance,definitionType,idField);if(definition?.id!==ref.id)throw new Error(`${definitionType} instance references a different definition.`);if(definition.game_id&&instance.game_id&&definition.game_id!==instance.game_id)throw new Error(`${definitionType} definition belongs to a different game.`);if(definition.content_version&&instance.content_version&&definition.content_version!==instance.content_version)throw new Error(`${definitionType} definition belongs to a different content version.`);return ref;}
export function valueType(value:any){if(value===null)return 'null';if(Array.isArray(value))return 'array';return typeof value;}
export function assertVariableValue(value:any){const type=valueType(value);if(!['string','number','boolean','object','array','null'].includes(type)||type==='number'&&!Number.isFinite(value))throw new Error('Variable value must be finite JSON data.');JSON.stringify(value);return type;}