import { handleCombatCommand } from './combat.ts';
import { authorizedGameIds, requireGamePermission } from './authorization.ts';
import { randomFloatAt } from './deterministic.ts';
import { entityRef } from './simulationContracts.ts';
import { ensureWorldInstance } from './worldInstances.ts';
import { publicRuleRegistry } from './ruleRegistry.ts';

const audit=async(base44,user,character,command,requestId,details)=>base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details,occurred_at:new Date().toISOString()});
const assertTest=(character)=>{if(!character.is_test_character)throw new Error('Simulation commands are restricted to test characters.');};
async function replayCombat(base44,character,combatId){
  const combat=await base44.asServiceRole.entities.CombatInstance.get(combatId);
  if(combat.character_id!==character.id)return {error:'Combat ownership could not be verified.'};
  const events=await base44.asServiceRole.entities.CombatEvent.filter({combat_instance_id:combat.id},'sequence',500),mismatches=[];
  let checked=0;
  for(const event of events.filter(row=>['action.resolved','status.ticked'].includes(row.event_type))){
    const effects=event.payload?.effects||event.payload?.targets?.flatMap((target:any)=>target.effects||[])||[],start=Number(event.rng_cursor||0)-effects.length;
    for(let index=0;index<effects.length;index++){const recorded=effects[index]?.roll;if(!Number.isFinite(recorded))continue;checked+=1;const expected=randomFloatAt(combat.seed,start+index+1);if(Math.abs(expected-recorded)>1e-12)mismatches.push({sequence:event.sequence,effect:index+1,expected,recorded});}
  }
  return {combat_id:combat.id,seed:combat.seed,events_checked:events.length,rolls_checked:checked,matched:mismatches.length===0,mismatches};
}

async function isolateTestWorld(base44:any,character:any){const membership=(await base44.asServiceRole.entities.PartyMember.filter({character_id:character.id,status:'active'},'-updated_date',1))[0],key=membership?`simulation-party-${membership.party_id}`:`simulation-${character.id}`,instance=await ensureWorldInstance(base44,character.game_id,character.content_version,key);if(character.world_instance_id!==instance.id){await base44.asServiceRole.entities.Character.update(character.id,{world_instance_id:instance.id});character.world_instance_id=instance.id;}if(membership){const party=await base44.asServiceRole.entities.Party.get(membership.party_id);if(party.world_instance_id!==instance.id)await base44.asServiceRole.entities.Party.update(party.id,{world_instance_id:instance.id});}return character;}

export async function loadSimulation(base44,body={}){
  const registry=publicRuleRegistry(),emptyRules={...registry,extensions:[]};
  const games=await base44.asServiceRole.entities.Game.list('title',100),game=games.find(item=>item.id===body.gameId)||games[0]||null;
  if(!game)return {games,game:null,release:null,characters:[],locations:[],items:[],statuses:[],quests:[],encounters:[],combats:[],questInstances:[],rules:emptyRules};
  const releases=await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',50),release=releases.find(item=>item.version===body.contentVersion)||releases[0]||null;
  if(!release)return {games,game,release:null,characters:[],locations:[],items:[],statuses:[],quests:[],encounters:[],combats:[],questInstances:[],rules:emptyRules};
  const [characters,locations,items,statuses,quests,encounters,extensions]=await Promise.all([
    base44.asServiceRole.entities.Character.filter({game_id:game.id,content_version:release.version,is_test_character:true},'-updated_date',100),base44.asServiceRole.entities.LocationDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.ItemDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.StatusDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.QuestDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.EncounterDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.RuleExtensionDefinition.filter({game_id:game.id,content_version:release.version},'kind',200)
  ]);
  for(const testCharacter of characters)await isolateTestWorld(base44,testCharacter);const character=characters.find(item=>item.id===body.characterId)||characters[0]||null;
  const [combats,questInstances,worldInstance,worldStates,tasks,ticks,activities,consequences,facts]=character?await Promise.all([base44.asServiceRole.entities.CombatInstance.filter({character_id:character.id},'-created_date',100),base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id},'-updated_date',100),base44.asServiceRole.entities.WorldInstance.get(character.world_instance_id),base44.asServiceRole.entities.WorldState.filter({world_instance_id:character.world_instance_id},'-updated_date',1),base44.asServiceRole.entities.WorldScheduledTask.filter({world_instance_id:character.world_instance_id},'due_minute',100),base44.asServiceRole.entities.WorldSimulationTick.filter({world_instance_id:character.world_instance_id},'-created_date',50),base44.asServiceRole.entities.NPCActivity.filter({world_instance_id:character.world_instance_id},'-updated_date',200),base44.asServiceRole.entities.TimedConsequence.filter({world_instance_id:character.world_instance_id,character_id:character.id},'-created_date',100),base44.asServiceRole.entities.StoryFact.filter({world_instance_id:character.world_instance_id,character_id:character.id},'-updated_date',100)]):[[],[],null,[],[],[],[],[],[]];
  const worldState=character?{instance:worldInstance,clock:worldStates[0]||null,tasks,ticks,activities,consequences,facts}:null;
  return {games,game,release,characters,locations,items,statuses,quests,encounters,combats,questInstances,worldState,rules:{...registry,extensions:extensions.map(row=>({type:row.key,name:row.name,description:row.description,kind:row.kind,parameters:row.parameters||[]}))}};
}

async function createTestCharacter(base44,user,body,requestId){
  const game=await base44.asServiceRole.entities.Game.get(body.gameId),releases=await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',1),release=releases[0];
  if(!release)return Response.json({error:'Publish content before creating a test character.'},{status:409});
  const [starts,definitions]=await Promise.all([base44.asServiceRole.entities.LocationDefinition.filter({game_id:game.id,content_version:release.version,tags:{'$in':['start']}},'-created_date',1),base44.asServiceRole.entities.AttributeDefinition.filter({game_id:game.id,content_version:release.version},'name',200)]);
  if(!starts[0])return Response.json({error:'The release has no starting location.'},{status:409});
  const defaults=game.character_defaults||{},attributes=Object.fromEntries(definitions.filter(item=>item.category!=='resource').map(item=>[item.key,item.default_value])),resources=Object.fromEntries(definitions.filter(item=>item.category==='resource').map(item=>[item.key,item.default_value])),worldInstance=await ensureWorldInstance(base44,game.id,release.version,`simulation-${requestId}`);
  const character=await base44.entities.Character.create({game_id:game.id,world_instance_id:worldInstance.id,content_version:release.version,name:String(body.name||'Test Character').trim(),current_location_id:starts[0].id,status:'active',is_test_character:true,attributes:{...attributes,...(defaults.attributes||{})},resources:{...resources,...(defaults.resources||{})},currency:defaults.currency||{},tags:defaults.tags||[],version:1});
  await base44.asServiceRole.entities.Container.create({game_id:game.id,content_version:release.version,owner_type:'character',owner_id:character.id,character_id:character.id,name:'Carried items',container_type:'character',capacity:Number(game.rules?.inventory_capacity||0),version:1});await audit(base44,user,character,body.command,requestId,{created:true});
  return Response.json(await loadSimulation(base44,{gameId:game.id,contentVersion:release.version,characterId:character.id}));
}

async function mutateTestCharacter(base44,user,character,body,requestId){
  if(body.command==='SIM_MOVE_CHARACTER'){if(character.version!==body.characterVersion)return Response.json({error:'Character state changed. Refresh and try again.'},{status:409});const location=await base44.asServiceRole.entities.LocationDefinition.get(body.locationId);if(location.game_id!==character.game_id||location.content_version!==character.content_version)return Response.json({error:'Location is outside this character’s content version.'},{status:422});await base44.asServiceRole.entities.Character.update(character.id,{current_location_id:location.id,version:character.version+1});await audit(base44,user,character,body.command,requestId,{location_id:location.id});}
  if(body.command==='SIM_GIVE_ITEM'){const definition=await base44.asServiceRole.entities.ItemDefinition.get(body.itemDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Item is outside this character’s content version.'},{status:422});let containers=await base44.asServiceRole.entities.Container.filter({character_id:character.id,container_type:'character'},'-created_date',1);if(!containers[0])containers=[await base44.asServiceRole.entities.Container.create({game_id:character.game_id,character_id:character.id,name:'Carried items',container_type:'character',capacity:0,version:1})];const item=await base44.asServiceRole.entities.ItemInstance.create({game_id:character.game_id,content_version:character.content_version,definition_id:definition.id,container_id:containers[0].id,character_id:character.id,quantity:Math.max(1,Math.floor(Number(body.quantity||1))),quality:'standard',bound_state:'unbound',custom_properties:{},applied_modifications:[],acquired_at:new Date().toISOString(),version:1});await audit(base44,user,character,body.command,requestId,{item_id:item.id,definition_id:definition.id,quantity:item.quantity});}
  if(body.command==='SIM_APPLY_STATUS'){const definition=await base44.asServiceRole.entities.StatusDefinition.get(body.statusDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Status is outside this character’s content version.'},{status:422});const rows=await base44.asServiceRole.entities.ActiveEffect.filter({target_type:'character',target_id:character.id,status_key:definition.key},'-updated_date',1),requested=Math.max(1,Math.floor(Number(body.stacks||1))),stacks=definition.stacking==='stack'?Math.min(Number(definition.maximum_stacks||1),Number(rows[0]?.stacks||0)+requested):requested;if(rows[0])await base44.asServiceRole.entities.ActiveEffect.update(rows[0].id,{stacks,version:Number(rows[0].version||1)+1});else await base44.asServiceRole.entities.ActiveEffect.create({game_id:character.game_id,content_version:character.content_version,target_type:'character',target_id:character.id,status_key:definition.key,source_id:'studio-simulation',stacks,payload:{simulation:true},version:1});await audit(base44,user,character,body.command,requestId,{status_key:definition.key,stacks});}
  if(body.command==='SIM_SET_QUEST_STATE'){const allowed=['AVAILABLE','ACTIVE','COMPLETED','FAILED','ABANDONED'];if(!allowed.includes(body.questState))return Response.json({error:'Unsupported quest state.'},{status:422});const definition=await base44.asServiceRole.entities.QuestDefinition.get(body.questDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Quest is outside this character’s content version.'},{status:422});const rows=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,definition_id:definition.id},'-updated_date',1),now=new Date().toISOString(),values={state:body.questState,reward_state:body.questState==='ACTIVE'?'pending':'none',completed_at:body.questState==='COMPLETED'?now:null,failed_at:body.questState==='FAILED'?now:null};let instance;if(rows[0])instance=await base44.asServiceRole.entities.QuestInstance.update(rows[0].id,{...values,version:Number(rows[0].version||1)+1});else instance=await base44.asServiceRole.entities.QuestInstance.create({game_id:character.game_id,world_instance_id:character.world_instance_id,content_version:character.content_version,definition_id:definition.id,definition_ref:entityRef('QuestDefinition',definition.id,definition.content_version),character_id:character.id,...values,accepted_at:['ACTIVE','COMPLETED','FAILED'].includes(body.questState)?now:null,branch_state:{},version:1});await audit(base44,user,character,body.command,requestId,{quest_definition_id:definition.id,quest_instance_id:instance.id,state:body.questState});}
  return null;
}

export async function handleSimulationCommand(base44,user,body,requestId){
  if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  if(body.command==='GET_SIMULATION'){const allowed=await authorizedGameIds(base44,user,'simulation:read');if(allowed&&allowed.length===0)return Response.json({error:'Forbidden'},{status:403});const scopedBody=allowed?{...body,gameId:allowed.includes(body.gameId)?body.gameId:allowed[0]}:body;return Response.json(await loadSimulation(base44,scopedBody));}
  if(body.command==='CREATE_TEST_CHARACTER'){const access=await requireGamePermission(base44,user,body.gameId,'simulation:write');if(access)return access;return await createTestCharacter(base44,user,body,requestId);}
  const characterAccessTarget=await base44.asServiceRole.entities.Character.get(body.characterId),access=await requireGamePermission(base44,user,characterAccessTarget.game_id,'simulation:write');if(access)return access;
  const duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1),character=characterAccessTarget;assertTest(character);
  if(body.command==='SIM_START_ENCOUNTER'){const response=await handleCombatCommand(base44,user,{...body,command:'START_ENCOUNTER'},requestId);if(!response.ok)return response;const combatData=await response.json();return Response.json({...await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}),startedCombatId:combatData.combat?.id||null});}
  if(body.command==='SIM_REPLAY_COMBAT'){const replay=await replayCombat(base44,character,body.combatId);if(replay.error)return Response.json({error:replay.error},{status:403});await audit(base44,user,character,body.command,requestId,{combat_id:body.combatId,matched:replay.matched,rolls_checked:replay.rolls_checked});return Response.json({...await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}),replay});}
  if(!duplicate.length){const errorResponse=await mutateTestCharacter(base44,user,character,body,requestId);if(errorResponse)return errorResponse;}
  return Response.json(await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}));
}