import { handleCombatCommand } from './combat.ts';

const audit=async(base44,user,character,command,requestId,details)=>base44.asServiceRole.entities.AuditEvent.create({game_id:character.game_id,actor_user_id:user.id,character_id:character.id,command,request_id:requestId,result:'accepted',details,occurred_at:new Date().toISOString()});
const assertTest=(character)=>{if(!character.is_test_character)throw new Error('Simulation commands are restricted to test characters.');};
const randomAt=(seed,cursor)=>{let x=(Number(seed)+Math.imul(cursor+1,0x6D2B79F5))>>>0;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296;};

async function replayCombat(base44,character,combatId){
  const combat=await base44.asServiceRole.entities.CombatInstance.get(combatId);
  if(combat.character_id!==character.id)return {error:'Combat ownership could not be verified.'};
  const events=await base44.asServiceRole.entities.CombatEvent.filter({combat_instance_id:combat.id},'sequence',500),mismatches=[];
  let checked=0;
  for(const event of events.filter(row=>['action.resolved','status.ticked'].includes(row.event_type))){
    const effects=event.payload?.effects||[],start=Number(event.rng_cursor||0)-effects.length;
    for(let index=0;index<effects.length;index++){const recorded=effects[index]?.roll;if(!Number.isFinite(recorded))continue;checked+=1;const expected=randomAt(combat.seed,start+index+1);if(Math.abs(expected-recorded)>1e-12)mismatches.push({sequence:event.sequence,effect:index+1,expected,recorded});}
  }
  return {combat_id:combat.id,seed:combat.seed,events_checked:events.length,rolls_checked:checked,matched:mismatches.length===0,mismatches};
}

export async function loadSimulation(base44,body={}){
  const games=await base44.asServiceRole.entities.Game.list('title',100),game=games.find(item=>item.id===body.gameId)||games[0]||null;
  if(!game)return {games,game:null,release:null,characters:[],locations:[],items:[],statuses:[],quests:[],encounters:[],combats:[],questInstances:[]};
  const releases=await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',50),release=releases.find(item=>item.version===body.contentVersion)||releases[0]||null;
  if(!release)return {games,game,release:null,characters:[],locations:[],items:[],statuses:[],quests:[],encounters:[],combats:[],questInstances:[]};
  const [characters,locations,items,statuses,quests,encounters]=await Promise.all([
    base44.asServiceRole.entities.Character.filter({game_id:game.id,content_version:release.version,is_test_character:true},'-updated_date',100),base44.asServiceRole.entities.LocationDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.ItemDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.StatusDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.QuestDefinition.filter({game_id:game.id,content_version:release.version},'name',200),base44.asServiceRole.entities.EncounterDefinition.filter({game_id:game.id,content_version:release.version},'name',200)
  ]);
  const character=characters.find(item=>item.id===body.characterId)||characters[0]||null;
  const [combats,questInstances]=character?await Promise.all([base44.asServiceRole.entities.CombatInstance.filter({character_id:character.id},'-created_date',100),base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id},'-updated_date',100)]):[[],[]];
  return {games,game,release,characters,locations,items,statuses,quests,encounters,combats,questInstances};
}

async function createTestCharacter(base44,user,body,requestId){
  const game=await base44.asServiceRole.entities.Game.get(body.gameId),releases=await base44.asServiceRole.entities.ContentRelease.filter({game_id:game.id,status:'published'},'-published_at',1),release=releases[0];
  if(!release)return Response.json({error:'Publish content before creating a test character.'},{status:409});
  const [starts,definitions]=await Promise.all([base44.asServiceRole.entities.LocationDefinition.filter({game_id:game.id,content_version:release.version,tags:{'$in':['start']}},'-created_date',1),base44.asServiceRole.entities.AttributeDefinition.filter({game_id:game.id,content_version:release.version},'name',200)]);
  if(!starts[0])return Response.json({error:'The release has no starting location.'},{status:409});
  const defaults=game.character_defaults||{},attributes=Object.fromEntries(definitions.filter(item=>item.category!=='resource').map(item=>[item.key,item.default_value])),resources=Object.fromEntries(definitions.filter(item=>item.category==='resource').map(item=>[item.key,item.default_value]));
  const character=await base44.entities.Character.create({game_id:game.id,content_version:release.version,name:String(body.name||'Test Character').trim(),current_location_id:starts[0].id,status:'active',is_test_character:true,attributes:{...attributes,...(defaults.attributes||{})},resources:{...resources,...(defaults.resources||{})},currency:defaults.currency||{},tags:defaults.tags||[],version:1});
  await base44.asServiceRole.entities.Container.create({game_id:game.id,character_id:character.id,name:'Carried items',container_type:'character',capacity:Number(game.rules?.inventory_capacity||0),version:1});await audit(base44,user,character,body.command,requestId,{created:true});
  return Response.json(await loadSimulation(base44,{gameId:game.id,contentVersion:release.version,characterId:character.id}));
}

async function mutateTestCharacter(base44,user,character,body,requestId){
  if(body.command==='SIM_MOVE_CHARACTER'){if(character.version!==body.characterVersion)return Response.json({error:'Character state changed. Refresh and try again.'},{status:409});const location=await base44.asServiceRole.entities.LocationDefinition.get(body.locationId);if(location.game_id!==character.game_id||location.content_version!==character.content_version)return Response.json({error:'Location is outside this character’s content version.'},{status:422});await base44.asServiceRole.entities.Character.update(character.id,{current_location_id:location.id,version:character.version+1});await audit(base44,user,character,body.command,requestId,{location_id:location.id});}
  if(body.command==='SIM_GIVE_ITEM'){const definition=await base44.asServiceRole.entities.ItemDefinition.get(body.itemDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Item is outside this character’s content version.'},{status:422});let containers=await base44.asServiceRole.entities.Container.filter({character_id:character.id,container_type:'character'},'-created_date',1);if(!containers[0])containers=[await base44.asServiceRole.entities.Container.create({game_id:character.game_id,character_id:character.id,name:'Carried items',container_type:'character',capacity:0,version:1})];const item=await base44.asServiceRole.entities.ItemInstance.create({game_id:character.game_id,content_version:character.content_version,definition_id:definition.id,container_id:containers[0].id,character_id:character.id,quantity:Math.max(1,Math.floor(Number(body.quantity||1))),quality:'standard',bound_state:'unbound',custom_properties:{},applied_modifications:[],acquired_at:new Date().toISOString(),version:1});await audit(base44,user,character,body.command,requestId,{item_id:item.id,definition_id:definition.id,quantity:item.quantity});}
  if(body.command==='SIM_APPLY_STATUS'){const definition=await base44.asServiceRole.entities.StatusDefinition.get(body.statusDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Status is outside this character’s content version.'},{status:422});const rows=await base44.asServiceRole.entities.ActiveEffect.filter({target_type:'character',target_id:character.id,status_key:definition.key},'-updated_date',1),requested=Math.max(1,Math.floor(Number(body.stacks||1))),stacks=definition.stacking==='stack'?Math.min(Number(definition.maximum_stacks||1),Number(rows[0]?.stacks||0)+requested):requested;if(rows[0])await base44.asServiceRole.entities.ActiveEffect.update(rows[0].id,{stacks,version:Number(rows[0].version||1)+1});else await base44.asServiceRole.entities.ActiveEffect.create({game_id:character.game_id,content_version:character.content_version,target_type:'character',target_id:character.id,status_key:definition.key,source_id:'studio-simulation',stacks,payload:{simulation:true},version:1});await audit(base44,user,character,body.command,requestId,{status_key:definition.key,stacks});}
  if(body.command==='SIM_SET_QUEST_STATE'){const allowed=['AVAILABLE','ACTIVE','COMPLETED','FAILED','ABANDONED'];if(!allowed.includes(body.questState))return Response.json({error:'Unsupported quest state.'},{status:422});const definition=await base44.asServiceRole.entities.QuestDefinition.get(body.questDefinitionId);if(definition.game_id!==character.game_id||definition.content_version!==character.content_version)return Response.json({error:'Quest is outside this character’s content version.'},{status:422});const rows=await base44.asServiceRole.entities.QuestInstance.filter({character_id:character.id,definition_id:definition.id},'-updated_date',1),now=new Date().toISOString(),values={state:body.questState,reward_state:body.questState==='ACTIVE'?'pending':'none',completed_at:body.questState==='COMPLETED'?now:null,failed_at:body.questState==='FAILED'?now:null};let instance;if(rows[0])instance=await base44.asServiceRole.entities.QuestInstance.update(rows[0].id,{...values,version:Number(rows[0].version||1)+1});else instance=await base44.asServiceRole.entities.QuestInstance.create({game_id:character.game_id,content_version:character.content_version,definition_id:definition.id,character_id:character.id,...values,accepted_at:['ACTIVE','COMPLETED','FAILED'].includes(body.questState)?now:null,branch_state:{},version:1});await audit(base44,user,character,body.command,requestId,{quest_definition_id:definition.id,quest_instance_id:instance.id,state:body.questState});}
  return null;
}

export async function handleSimulationCommand(base44,user,body,requestId){
  if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
  if(body.command==='GET_SIMULATION')return Response.json(await loadSimulation(base44,body));
  if(body.command==='CREATE_TEST_CHARACTER')return await createTestCharacter(base44,user,body,requestId);
  const duplicate=await base44.asServiceRole.entities.AuditEvent.filter({actor_user_id:user.id,request_id:requestId,result:'accepted'},'-occurred_at',1),character=await base44.asServiceRole.entities.Character.get(body.characterId);assertTest(character);
  if(body.command==='SIM_START_ENCOUNTER'){const response=await handleCombatCommand(base44,user,{...body,command:'START_ENCOUNTER'},requestId);if(!response.ok)return response;const combatData=await response.json();return Response.json({...await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}),startedCombatId:combatData.combat?.id||null});}
  if(body.command==='SIM_REPLAY_COMBAT'){const replay=await replayCombat(base44,character,body.combatId);if(replay.error)return Response.json({error:replay.error},{status:403});await audit(base44,user,character,body.command,requestId,{combat_id:body.combatId,matched:replay.matched,rolls_checked:replay.rolls_checked});return Response.json({...await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}),replay});}
  if(!duplicate.length){const errorResponse=await mutateTestCharacter(base44,user,character,body,requestId);if(errorResponse)return errorResponse;}
  return Response.json(await loadSimulation(base44,{gameId:character.game_id,contentVersion:character.content_version,characterId:character.id}));
}