import { contentDefinitionTypes, createBasePack, resolveContentPackLayers } from './contentPacks.ts';
import { exportContentBundle, importContentBundle } from './contentBundles.ts';
import { requireGamePermission } from './authorization.ts';
import { validateCalendarConfig,validateSimulationConfig } from './calendar.ts';
import { cleanStudioValues, createStudioRows, previewStudioRows } from './studioAuthoring.ts';
import { acquireReleaseLock, abandonReleaseLock, exposeRecordRevision, finishReleaseLock, recordConflict, recordRevision } from './studioConcurrency.ts';
import { contentIdentity, ensureContentIdentity, makeContentRef, publicContentSchemaRegistry } from './contentSchemaRegistry.ts';
import { getContentDependencies, rebuildContentDependencyIndex } from './contentDependencies.ts';
import { pageRequest } from './entityPagination.ts';
import { assignContentPack, effectiveContentForType, recordContentChange } from './contentLifecycle.ts';
import { moveContent, renameContent, replaceContent } from './contentTransformations.ts';
const contentTypes = contentDefinitionTypes;
const reserved = new Set(['id','game_id','content_version','created_date','updated_date','created_by_id']);
const gameFields = ['title','description','terminology','theme','enabled_modules','navigation','header_indicators','character_defaults','calendar','simulation','rules'];
const clean = cleanStudioValues;
const exposeContent=(release:any,type:string,row:any)=>({...exposeRecordRevision(row),content_ref:makeContentRef(release.game_id,type,contentIdentity(type,row))});
async function draftRelease(base44:any, releaseId:string) { const release=await base44.asServiceRole.entities.ContentRelease.get(releaseId); if(release.status!=='draft')throw new Error('Published and retired releases are immutable.'); return release; }
export async function handleStudioAuthoringCommand(base44:any,user:any,body:any,requestId=''){
  if(body.command==='CREATE_GAME'){
    if(user.role!=='admin')return Response.json({error:'Forbidden'},{status:403});
    const key=String(body.key||'').trim().toLowerCase().replace(/[^a-z0-9._-]/g,'-'),title=String(body.title||'').trim(),version=String(body.version||'1.0.0').trim();
    if(!key||!title||!version)return Response.json({error:'Title, key, and initial version are required.'},{status:422});
    if((await base44.asServiceRole.entities.Game.filter({key},'-created_date',1)).length)return Response.json({error:'That game key already exists.'},{status:409});
    const game=await base44.asServiceRole.entities.Game.create({key,title,description:String(body.description||''),status:'draft',terminology:{},theme:{accent:'#22d3ee',surface:'#0a1728',background:'#07111f',text:'#f1f5f9',muted:'#64748b',border:'#ffffff',danger:'#f87171',heading_font:'system',body_font:'system',density:'comfortable',radius:'rounded',media_style:'rounded'},enabled_modules:['world','characters','quests','achievements','journal','inventory','skills','party','combat','messages','studio','settings','account'],header_indicators:['character','location','resource','currency'],character_defaults:{attributes:{},resources:{},currency:{},tags:[]},calendar:{name:'World Calendar',minutes_per_hour:60,hours_per_day:24,weekdays:[{key:'day-1',name:'Day 1'},{key:'day-2',name:'Day 2'},{key:'day-3',name:'Day 3'},{key:'day-4',name:'Day 4'},{key:'day-5',name:'Day 5'},{key:'day-6',name:'Day 6'},{key:'day-7',name:'Day 7'}],months:Array.from({length:12},(_,index)=>({key:`month-${index+1}`,name:`Month ${index+1}`,days:30})),epoch:{year:1,month:1,day:1,hour:8,minute:0},format:'{weekday}, {month} {day}, Year {year} · {hour}:{minute}'},simulation:{local_tick_minutes:15,regional_tick_minutes:60,global_tick_minutes:360,max_fast_forward_minutes:1440,fast_forward_options:[{label:'Wait 1 hour',minutes:60},{label:'Rest 8 hours',minutes:480,rest:true},{label:'Wait 1 day',minutes:1440}]},rules:{inventory_capacity:0,starter_stack_quantity:1}});
    await base44.asServiceRole.entities.GameMembership.create({game_id:game.id,user_id:user.id,role:'owner',status:'active'});
    const pack=await createBasePack(base44,game,version),release=await base44.asServiceRole.entities.ContentRelease.create({game_id:game.id,version,content_pack_ids:[pack.id],status:'draft',revision:1,dependency_index_revision:1,notes:'Initial authoring release',validation_summary:{}});
    return Response.json({game,pack,release});
  }
  if(body.command==='SAVE_GAME_CONFIG'){
    const game=await base44.asServiceRole.entities.Game.get(body.gameId),access=await requireGamePermission(base44,user,game.id,'studio:write');if(access)return access;
    const patch=Object.fromEntries(Object.entries(body.values||{}).filter(([key])=>gameFields.includes(key))),calendarIssue=validateCalendarConfig(patch.calendar),simulationIssue=validateSimulationConfig(patch.simulation);if(calendarIssue||simulationIssue)return Response.json({error:calendarIssue||simulationIssue},{status:422});
    return Response.json({game:await base44.asServiceRole.entities.Game.update(game.id,patch)});
  }
  if(body.command==='CREATE_CONTENT_PACK'){const game=await base44.asServiceRole.entities.Game.get(body.gameId),access=await requireGamePermission(base44,user,game.id,'content:write');if(access)return access;const key=String(body.values?.key||'').trim(),name=String(body.values?.name||'').trim(),version=String(body.values?.version||'').trim();if(!key||!name||!version)return Response.json({error:'Pack name, key, and version are required.'},{status:422});const duplicate=await base44.asServiceRole.entities.ContentPack.filter({game_id:game.id,key},'-created_date',1);if(duplicate.length)return Response.json({error:'That content pack key already exists.'},{status:409});const dependencies=await resolveContentPackLayers(base44,game.id,body.values?.dependencyPackIds||[]),pack=await base44.asServiceRole.entities.ContentPack.create({game_id:game.id,key,name,description:String(body.values?.description||''),version,status:'draft',package_kind:['core','mod','extension'].includes(body.values?.packageKind)?body.values.packageKind:'mod',engine_api_version:String(body.values?.engineApiVersion||'1'),namespace:String(body.values?.namespace||key),dependency_pack_ids:dependencies.map((item:any)=>item.id),module_keys:body.values?.moduleKeys||[]});return Response.json({pack});}
  if(body.command==='EXPORT_CONTENT_PACKS'){const access=await requireGamePermission(base44,user,body.gameId,'content:read');if(access)return access;return Response.json({bundle:await exportContentBundle(base44,body.gameId)});}
  if(body.command==='IMPORT_CONTENT_PACKS'){const access=await requireGamePermission(base44,user,body.gameId,'content:write');if(access)return access;const imported=await importContentBundle(base44,body.gameId,body.bundle);return Response.json(imported);}
  if(body.command==='GET_CONTENT_SCHEMA_REGISTRY')return Response.json({registry:publicContentSchemaRegistry()});
  if(['GET_CONTENT_DEPENDENCIES','REBUILD_CONTENT_DEPENDENCY_INDEX'].includes(body.command)){const release=await base44.asServiceRole.entities.ContentRelease.get(body.releaseId),access=await requireGamePermission(base44,user,release.game_id,body.command==='GET_CONTENT_DEPENDENCIES'?'content:read':'content:write');if(access)return access;if(body.command==='GET_CONTENT_DEPENDENCIES'){if(body.contentRef&&(!body.contentRef.content_type||!body.contentRef.key||body.contentRef.game_id!==release.game_id))return Response.json({error:'A valid content reference for this game is required.'},{status:422});return Response.json({dependencies:await getContentDependencies(base44,release,body.contentRef||null)});}if(release.status==='published'){const index=await rebuildContentDependencyIndex(base44,release),updated=await base44.asServiceRole.entities.ContentRelease.update(release.id,{dependency_index_revision:index.revision});return Response.json({index,release:updated});}const lock=await acquireReleaseLock(base44,release,body.expectedReleaseRevision,'indexing');if(lock.response)return lock.response;try{const index=await rebuildContentDependencyIndex(base44,lock.release),draft=await finishReleaseLock(base44,lock.release,'draft',{dependency_index_revision:index.revision});return Response.json({index,release:draft});}catch(error){await abandonReleaseLock(base44,lock.release);throw error;}}
  if(!contentTypes.includes(body.contentType))return Response.json({error:'Unsupported content type.'},{status:422});
  const release=await base44.asServiceRole.entities.ContentRelease.get(body.releaseId);
  const permission=body.command==='GET_STUDIO_CONTENT'?'content:read':'content:write',access=await requireGamePermission(base44,user,release.game_id,permission);if(access)return access;
  const entity=base44.asServiceRole.entities[body.contentType];
  if(body.command==='GET_STUDIO_CONTENT'){const {limit,skip}=pageRequest(body),search=String(body.search||'').trim(),query:any={game_id:release.game_id,content_version:release.version};if(body.itemId)query.id=body.itemId;if(search)query.$or=[{key:{$regex:search,$options:'i'}},{name:{$regex:search,$options:'i'}},{label:{$regex:search,$options:'i'}}];const rows=await entity.filter(query,'created_date',limit+1,skip),has_more=rows.length>limit,items=rows.slice(0,limit),entries=items.length?await base44.asServiceRole.entities.ContentPackEntry.filter({release_id:release.id,content_type:body.contentType,record_id:{$in:items.map((item:any)=>item.id)}},'created_date',items.length):[],packByRecord=new Map(entries.map((entry:any)=>[entry.record_id,entry.pack_id]));return Response.json({release:{...release,revision:Number(release.revision||1)},items:items.map((item:any)=>({...exposeContent(release,body.contentType,item),pack_id:packByRecord.get(item.id)})),page:{skip,limit,has_more,next_skip:has_more?skip+limit:null}});}
  if(body.command==='GET_EFFECTIVE_CONTENT'){const rows=await effectiveContentForType(base44,release,body.contentType);return Response.json({release,items:rows.map((item:any)=>({...exposeContent(release,body.contentType,item.record),pack_id:item.pack_id,layer:item.layer}))});}
  if(body.command==='PREVIEW_BULK_STUDIO_CONTENT'){if(release.status!=='draft')return Response.json({error:`Release is locked for ${release.status}.`},{status:409});return Response.json({preview:await previewStudioRows(base44,release,body.contentType,body.items)});}
  if(body.command==='IMPORT_BULK_STUDIO_CONTENT'){
    const lock=await acquireReleaseLock(base44,release,body.expectedReleaseRevision,'editing',true);if(lock.response)return lock.response;
    try{const result=await createStudioRows(base44,lock.release,body.contentType,body.items);if(!result.preview.valid){await abandonReleaseLock(base44,lock.release);return Response.json({error:'Bulk content validation failed.',preview:result.preview},{status:422});}await Promise.all(result.items.map(async(item:any)=>{const entry=await assignContentPack(base44,lock.release,body.contentType,item,body.packId);await recordContentChange(base44,user,lock.release,'create',body.contentType,item,null,entry.pack_id,`${requestId}:${item.id}`)}));const index=await rebuildContentDependencyIndex(base44,lock.release),draft=await finishReleaseLock(base44,lock.release,'draft',{dependency_index_revision:index.revision});return Response.json({...result,items:result.items.map((item:any)=>exposeContent(lock.release,body.contentType,item)),release:draft,index});}catch(error){await abandonReleaseLock(base44,lock.release);throw error;}
  }
  if(['RENAME_STUDIO_CONTENT','REPLACE_STUDIO_CONTENT','MOVE_STUDIO_CONTENT'].includes(body.command)){
    let item=await entity.get(body.itemId);if(item.game_id!==release.game_id||item.content_version!==release.version)return Response.json({error:'Content ownership could not be verified.'},{status:403});if(recordRevision(item)!==String(body.expectedRevision||''))return recordConflict(body.expectedRevision,item,{});
    let replacement:any=null;if(body.command==='RENAME_STUDIO_CONTENT'){const newKey=String(body.newKey||'').trim();if(!newKey)return Response.json({error:'A new key is required.'},{status:422});const duplicates=await entity.filter({game_id:release.game_id,content_version:release.version,key:newKey},'-created_date',2);if(duplicates.some((row:any)=>row.id!==item.id))return Response.json({error:'That content key already exists in this release.'},{status:409});}if(body.command==='REPLACE_STUDIO_CONTENT'){replacement=await entity.get(body.replacementItemId);if(replacement.id===item.id||replacement.game_id!==release.game_id||replacement.content_version!==release.version)return Response.json({error:'Choose valid replacement content from this release.'},{status:422});}
    const lock=await acquireReleaseLock(base44,release,body.expectedReleaseRevision,'editing',true);if(lock.response)return lock.response;
    try{item=await entity.get(body.itemId);if(recordRevision(item)!==String(body.expectedRevision||'')){await abandonReleaseLock(base44,lock.release);return recordConflict(body.expectedRevision,item,{});}const result=body.command==='RENAME_STUDIO_CONTENT'?await renameContent(base44,user,lock.release,body.contentType,item,String(body.newKey).trim(),requestId):body.command==='REPLACE_STUDIO_CONTENT'?await replaceContent(base44,user,lock.release,body.contentType,item,replacement,requestId):await moveContent(base44,user,lock.release,body.contentType,item,body.packId,requestId),index=await rebuildContentDependencyIndex(base44,lock.release),draft=await finishReleaseLock(base44,lock.release,'draft',{dependency_index_revision:index.revision});return Response.json({...result,release:draft,index});}catch(error){await abandonReleaseLock(base44,lock.release);throw error;}
  }
  if(body.command==='SAVE_STUDIO_CONTENT'){
    let current:any=null,values=clean(body.values);if(body.itemId)current=await entity.get(body.itemId);values=ensureContentIdentity(body.contentType,values,current);const key=String(values.key||'').trim();
    if(body.itemId){if(current.id!==body.itemId||current.game_id!==release.game_id||current.content_version!==release.version)return Response.json({error:'Content ownership could not be verified.'},{status:403});if(recordRevision(current)!==String(body.expectedRevision||''))return recordConflict(body.expectedRevision,current,values);}
    if(key){const uniqueQuery:any={game_id:release.game_id,content_version:release.version,key};if(body.contentType==='LocalizationEntry')uniqueQuery.locale=String(values.locale||'').trim();const duplicate=await entity.filter(uniqueQuery,'-created_date',10);if(duplicate.some((item:any)=>item.id!==body.itemId))return Response.json({error:'That content key already exists in this release.'},{status:409});}
    const preview=await previewStudioRows(base44,release,body.contentType,[values],body.itemId);if(!preview.valid)return Response.json({error:[...preview.errors,...preview.rows.flatMap((row:any)=>row.errors)].join(' ')||'Content validation failed.',preview},{status:422});
    const lock=await acquireReleaseLock(base44,release,body.expectedReleaseRevision,'editing',true);if(lock.response)return lock.response;
    try{if(body.itemId){current=await entity.get(body.itemId);if(current.game_id!==release.game_id||current.content_version!==release.version){await abandonReleaseLock(base44,lock.release);return Response.json({error:'Content ownership could not be verified.'},{status:403});}if(recordRevision(current)!==String(body.expectedRevision||'')){await abandonReleaseLock(base44,lock.release);return recordConflict(body.expectedRevision,current,values);}}const before=current?{...current}:null,payload={...values,game_id:release.game_id,content_version:release.version},item=body.itemId?await entity.update(body.itemId,payload):await entity.create(payload),entry=await assignContentPack(base44,lock.release,body.contentType,item,body.packId);await recordContentChange(base44,user,lock.release,body.itemId?'update':'create',body.contentType,item,before,entry.pack_id,requestId);const index=await rebuildContentDependencyIndex(base44,lock.release),draft=await finishReleaseLock(base44,lock.release,'draft',{dependency_index_revision:index.revision});return Response.json({item:exposeContent(lock.release,body.contentType,item),release:draft,index,change_set_revision:lock.release.revision});}catch(error){await abandonReleaseLock(base44,lock.release);throw error;}
  }
  if(body.command==='DELETE_STUDIO_CONTENT'){
    let item=await entity.get(body.itemId);if(item.id!==body.itemId||item.game_id!==release.game_id||item.content_version!==release.version)return Response.json({error:'Content ownership could not be verified.'},{status:403});if(recordRevision(item)!==String(body.expectedRevision||''))return recordConflict(body.expectedRevision,item,{});const dependencies=await getContentDependencies(base44,release,makeContentRef(release.game_id,body.contentType,contentIdentity(body.contentType,item)));if(dependencies.inbound.length)return Response.json({error:'This content is still referenced. Replace or remove inbound references before deleting it.',dependencies},{status:409});
    const lock=await acquireReleaseLock(base44,release,body.expectedReleaseRevision,'editing',true);if(lock.response)return lock.response;
    try{item=await entity.get(body.itemId);if(recordRevision(item)!==String(body.expectedRevision||'')){await abandonReleaseLock(base44,lock.release);return recordConflict(body.expectedRevision,item,{});}await entity.delete(item.id);await base44.asServiceRole.entities.ContentPackEntry.deleteMany({release_id:release.id,content_type:body.contentType,record_id:item.id});await recordContentChange(base44,user,lock.release,'delete',body.contentType,null,item,undefined,requestId);const index=await rebuildContentDependencyIndex(base44,lock.release),draft=await finishReleaseLock(base44,lock.release,'draft',{dependency_index_revision:index.revision});return Response.json({deleted:true,release:draft,index,change_set_revision:lock.release.revision});}catch(error){await abandonReleaseLock(base44,lock.release);throw error;}
  }
  return Response.json({error:'Unknown studio command.'},{status:400});
}