import { validateReleaseContent, loadReleaseData } from './content.ts';
const reserved=new Set(['id','game_id','content_version','created_date','updated_date','created_by_id','is_sample']);
export const cleanStudioValues=(values:any)=>Object.fromEntries(Object.entries(values||{}).filter(([key])=>!reserved.has(key)));
const required:Record<string,string[]>={TagDefinition:['key','name'],EnvironmentalFeatureDefinition:['key','name','location_definition_ids'],ItemRecipeDefinition:['key','name','inputs','outputs'],WeatherDefinition:['key','name','region_key'],WorldEventDefinition:['key','name','trigger'],FactionDefinition:['key','name'],FactionOperationDefinition:['key','name','faction_key','duration_minutes'],CrimeDefinition:['key','name','jurisdiction_key','severity'],KnowledgeDefinition:['key','name','canonical_value'],RumorDefinition:['key','name','proposition_key'],StoryFactDefinition:['key','name','scope'],StoryletDefinition:['key','name','trigger_type'],InteractionRuleDefinition:['key','name','action_key','label'],LocationDefinition:['key','name','location_type'],Connection:['label','from_location_id','to_location_id'],NPCDefinition:['key','name'],NPCInstance:['definition_id'],NPCPlacement:['npc_instance_id','location_id'],DialogueGraph:['key','name','start_node_key','nodes'],QuestDefinition:['key','name','objective_graph'],AchievementDefinition:['key','name','criteria'],ItemDefinition:['key','name','category'],AbilityDefinition:['key','name'],EncounterDefinition:['key','name'],AttributeDefinition:['key','name','default_value'],SkillDefinition:['key','name','max_rank'],FormulaDefinition:['key','name','expression','output_type'],EffectDefinition:['key','name','effects'],StatusDefinition:['key','name','effects'],LocalizationEntry:['locale','key','value'],RuleExtensionDefinition:['key','name','kind'],RuntimeModuleDefinition:['key','name','route_slug','sections']};
const enums:Record<string,Record<string,string[]>>={TagDefinition:{visibility:['visible','hidden']},WeatherDefinition:{active_phases:['night','morning','afternoon','evening']},StoryFactDefinition:{scope:['character','world'],visibility:['public','journal','hidden']},StoryletDefinition:{trigger_type:['event','tick']},InteractionRuleDefinition:{},NPCInstance:{availability:['available','hidden','departed']},QuestDefinition:{repeatability:['never','repeatable','scheduled'],visibility:['visible','discovered','hidden']},AttributeDefinition:{data_type:['integer','decimal','boolean'],visibility:['public','player','hidden']},FormulaDefinition:{output_type:['integer','decimal']},StatusDefinition:{stacking:['replace','stack','refresh'],duration_type:['turns','time','permanent']},RuleExtensionDefinition:{kind:['condition','effect']}};
function contractIssues(value:any,contentType:string){if(!value||typeof value!=='object'||Array.isArray(value))return ['Record must be a JSON object.'];const issues:string[]=[];for(const key of required[contentType]||[])if(value[key]===undefined||value[key]===null||value[key]===''||Array.isArray(value[key])&&!value[key].length)issues.push(`${key} is required.`);for(const [key,allowed] of Object.entries(enums[contentType]||{})){const current=value[key];if(current===undefined||current==='')continue;if(Array.isArray(current)){for(const entry of current)if(!allowed.includes(entry))issues.push(`${key} contains unsupported value ${entry}.`);}else if(!allowed.includes(current))issues.push(`${key} must be one of: ${allowed.join(', ')}.`);}return issues;}
const signature=(issue:any)=>`${issue.type}|${issue.message}`;
export async function previewStudioRows(base44:any,release:any,contentType:string,rows:any[],itemId?:string){
  if(!Array.isArray(rows)||!rows.length||rows.length>500)return {valid:false,rows:[],errors:['Upload between 1 and 500 content records.'],summary:{total:Array.isArray(rows)?rows.length:0,valid:0,invalid:Array.isArray(rows)?rows.length:0}};
  const baseData=await loadReleaseData(base44,release),existing=(baseData[contentType]||[]).filter((row:any)=>row.id!==itemId),prepared=rows.map((row,index)=>({...cleanStudioValues(row),game_id:release.game_id,content_version:release.version,id:`preview-${index}`})),rowErrors=prepared.map((row:any)=>contractIssues(row,contentType)),identities=new Map<string,number>();
  [...existing,...prepared].forEach((row:any,index:number)=>{if(!row.key)return;const identity=`${row.key}|${contentType==='LocalizationEntry'?row.locale||'':''}`;if(identities.has(identity)){const preparedIndex=index-existing.length;if(preparedIndex>=0)rowErrors[preparedIndex].push('The content key already exists in this release.');const earlier=identities.get(identity)!-existing.length;if(earlier>=0)rowErrors[earlier].push('The content key is duplicated in this upload.');}else identities.set(identity,index);});
  const baseline=await validateReleaseContent(base44,release,{},baseData),candidateData={...baseData,[contentType]:[...existing,...prepared]},candidate=await validateReleaseContent(base44,release,{},candidateData),baselineIssues=new Set((baseline.errors||[]).map(signature)),introduced=(candidate.errors||[]).filter((issue:any)=>!baselineIssues.has(signature(issue))),globalErrors:string[]=[];
  for(const issue of introduced){const match=/^preview-(\d+)$/.exec(String(issue.id||''));if(match)rowErrors[Number(match[1])].push(issue.message);else globalErrors.push(issue.message);}
  const resultRows=prepared.map((row:any,index:number)=>({index,label:row.name||row.label||row.key||`Record ${index+1}`,valid:rowErrors[index].length===0,errors:[...new Set(rowErrors[index])]})),valid=resultRows.every(row=>row.valid)&&globalErrors.length===0;
  return {valid,rows:resultRows,errors:[...new Set(globalErrors)],summary:{total:rows.length,valid:resultRows.filter(row=>row.valid).length,invalid:resultRows.filter(row=>!row.valid).length}};
}
export async function createStudioRows(base44:any,release:any,contentType:string,rows:any[]){const preview=await previewStudioRows(base44,release,contentType,rows);if(!preview.valid)return {preview};const payloads=rows.map(row=>({...cleanStudioValues(row),game_id:release.game_id,content_version:release.version})),items=await base44.asServiceRole.entities[contentType].bulkCreate(payloads);return {preview,items};}