import { loadWorldEnvironment } from './worldEnvironment.ts';

const entityNames:any={location:'LocationDefinition',npc:'NPCInstance',item:'ItemInstance',character:'Character'};
async function partyCharacterIds(base44:any,character:any){const membership=(await base44.asServiceRole.entities.PartyMember.filter({character_id:character.id,status:'active'},'-updated_date',1))[0];if(!membership)return [character.id];const rows=await base44.asServiceRole.entities.PartyMember.filter({party_id:membership.party_id,status:'active'},'-updated_date',50);return [...new Set([character.id,...rows.map((row:any)=>row.character_id)])];}
async function hydrate(base44:any,type:string,record:any){if(type==='item'){const definition=await base44.asServiceRole.entities.ItemDefinition.get(record.definition_id);return {...record,definition,label:definition.name,description:definition.description};}if(type==='npc'){const definition=await base44.asServiceRole.entities.NPCDefinition.get(record.definition_id);return {...record,definition,label:definition.name,description:definition.description};}return {...record,label:record.name,description:record.description};}
export async function loadWorldContext(base44:any,character:any,targetType:string,targetId:string,selection:any={}){
  const entityName=entityNames[targetType];if(!entityName)throw new Error(`Unsupported contextual target type ${targetType}.`);
  const location=await base44.asServiceRole.entities.LocationDefinition.get(character.current_location_id),environment=await loadWorldEnvironment(base44,character,location),partyIds=await partyCharacterIds(base44,character);
  const [rawTarget,items,placements,partyCharacters]=await Promise.all([base44.asServiceRole.entities[entityName].get(targetId),base44.asServiceRole.entities.ItemInstance.filter({character_id:character.id},'-acquired_at',200),base44.asServiceRole.entities.NPCPlacement.filter({location_id:location.id,enabled:true},'created_date',100),base44.asServiceRole.entities.Character.filter({id:{'$in':partyIds}},'name',50)]);
  if(targetType==='location'&&rawTarget.id!==location.id)throw new Error('Location actions are only available at the current location.');if(targetType==='item'&&rawTarget.character_id!==character.id)throw new Error('Item ownership could not be verified.');if(targetType==='character'&&!partyIds.includes(rawTarget.id))throw new Error('Character targets must belong to the active party.');if(targetType==='npc'&&!placements.some((row:any)=>row.npc_instance_id===rawTarget.id))throw new Error('That NPC is not present at the current location.');if(rawTarget.game_id&&rawTarget.game_id!==character.game_id)throw new Error('The target belongs to a different game.');if(rawTarget.content_version&&rawTarget.content_version!==character.content_version)throw new Error('The target belongs to a different content version.');
  const npcIds=placements.map((row:any)=>row.npc_instance_id),npcRows=npcIds.length?await base44.asServiceRole.entities.NPCInstance.filter({id:{'$in':npcIds},availability:'available'},'created_date',100):[],[target,sourceItems,npcs]=await Promise.all([hydrate(base44,targetType,rawTarget),Promise.all(items.map((item:any)=>hydrate(base44,'item',item))),Promise.all(npcRows.map((npc:any)=>hydrate(base44,'npc',npc)))]),candidates=[{type:'location',id:location.id,label:location.name,record:location},...npcs.map((row:any)=>({type:'npc',id:row.id,label:row.label,record:row})),...partyCharacters.map((row:any)=>({type:'character',id:row.id,label:row.name,record:row}))];
  const selected=[];for(const ref of selection.targets||[]){const candidate=candidates.find((item:any)=>item.type===ref.type&&item.id===ref.id);if(!candidate)throw new Error('One or more selected targets are unavailable.');selected.push(candidate.record);}
  const sourceItem=selection.sourceItemId?sourceItems.find((item:any)=>item.id===selection.sourceItemId):null;if(selection.sourceItemId&&!sourceItem)throw new Error('The selected source item is unavailable.');
  return {character,actor:character,target,targets:selected,sourceItem,location,world:environment.clock,weather:environment.weather,worldInstance:environment.worldInstance,gameId:character.game_id,contentVersion:character.content_version,tagTypes:{actor:'character',character:'character',target:targetType,sourceItem:'item'},definitions:{target:target.definition,sourceItem:sourceItem?.definition},candidates,sourceItems};
}
export function publicWorldContext(context:any){return {actor:{type:'character',id:context.character.id,label:context.character.name,version:context.character.version},location:{type:'location',id:context.location.id,label:context.location.name},world:{instance_id:context.character.world_instance_id,time:context.world.current_time,phase:context.world.phase,weather:context.weather?.key||null},primary_target:{type:context.tagTypes.target,id:context.target.id,label:context.target.label,version:context.target.version||null},targets:context.candidates.map((item:any)=>({type:item.type,id:item.id,label:item.label,version:item.record.version||null})),source_items:context.sourceItems.map((item:any)=>({id:item.id,label:item.label,quantity:item.quantity,version:item.version,tags:item.definition?.tags||[]}))};}