import { processQuestEvent } from './quests.ts';
import { processWorldSignals } from './worldEvents.ts';
import { deriveSeed, randomFloatAt } from './deterministic.ts';
import { ensureWorldInstance } from './worldInstances.ts';
import { processTimedRuntimeEffects } from './runtimeEffects.ts';

const regionOf=(location:any)=>String(location?.region_key||'default');
const phaseOf=(date:Date)=>{const hour=date.getUTCHours();return hour<6?'night':hour<12?'morning':hour<18?'afternoon':hour<21?'evening':'night';};
function selectWeather(definitions:any[],region:string,slot:number,seed:number){const choices=definitions.filter(item=>item.region_key===region),pool=choices.length?choices:definitions.filter(item=>item.region_key==='default');if(!pool.length)return null;const weighted=pool.flatMap(item=>Array.from({length:Math.max(1,Math.min(20,Number(item.weight||1)))},()=>item)),index=Math.floor(randomFloatAt(deriveSeed(seed,region),slot)*weighted.length);return weighted[index];}
async function stateFor(base44:any,character:any){const instance=character.world_instance_id?await base44.asServiceRole.entities.WorldInstance.get(character.world_instance_id):await ensureWorldInstance(base44,character.game_id,character.content_version),scoped=await base44.asServiceRole.entities.WorldState.filter({world_instance_id:instance.id},'-updated_date',1),legacy=scoped[0]?[]:await base44.asServiceRole.entities.WorldState.filter({game_id:character.game_id,content_version:character.content_version},'-updated_date',1);if(scoped[0])return scoped[0];if(legacy[0])return await base44.asServiceRole.entities.WorldState.update(legacy[0].id,{world_instance_id:instance.id,version:Number(legacy[0].version||1)+1});const game=await base44.asServiceRole.entities.Game.get(character.game_id),start=game.rules?.world_start_time||instance.current_time;return await base44.asServiceRole.entities.WorldState.create({game_id:character.game_id,world_instance_id:instance.id,content_version:character.content_version,current_time:start,weather_by_region:{},weather_slot:0,version:1});}
export async function loadWorldEnvironment(base44:any,character:any,location?:any){const [state,definitions,currentLocation]=await Promise.all([stateFor(base44,character),base44.asServiceRole.entities.WeatherDefinition.filter({game_id:character.game_id,content_version:character.content_version},'region_key',500),location||base44.asServiceRole.entities.LocationDefinition.get(character.current_location_id)]),instance=await base44.asServiceRole.entities.WorldInstance.get(state.world_instance_id),region=regionOf(currentLocation),weatherKey=state.weather_by_region?.[region],weather=definitions.find((item:any)=>item.key===weatherKey&&item.region_key===region)||selectWeather(definitions,region,Number(state.weather_slot||0),Number(instance.seed||0)),time=new Date(state.current_time);return {clock:{current_time:time.toISOString(),phase:phaseOf(time),day:Math.floor(time.getTime()/86400000),version:state.version,world_instance_id:state.world_instance_id,seed:instance.seed},region,weather:weather?{key:weather.key,name:weather.name,description:weather.description,temperature:weather.temperature,tags:weather.tags||[]}:null};}
export async function advanceWorldTime(base44:any,character:any,minutes:number){const amount=Math.max(0,Number(minutes||0));if(!amount)return await loadWorldEnvironment(base44,character);const state=await stateFor(base44,character),game=await base44.asServiceRole.entities.Game.get(character.game_id),interval=Math.max(1,Number(game.rules?.weather_interval_minutes||360)),before=new Date(state.current_time),after=new Date(before.getTime()+amount*60000),oldSlot=Math.floor(before.getTime()/(interval*60000)),newSlot=Math.floor(after.getTime()/(interval*60000)),instance=await base44.asServiceRole.entities.WorldInstance.get(state.world_instance_id),definitions=await base44.asServiceRole.entities.WeatherDefinition.filter({game_id:character.game_id,content_version:character.content_version},'region_key',500),locations=await base44.asServiceRole.entities.LocationDefinition.filter({game_id:character.game_id,content_version:character.content_version},'region_key',500),regions=[...new Set(['default',...locations.map(regionOf),...definitions.map((item:any)=>item.region_key)])],previousWeather={...(state.weather_by_region||{})},weatherByRegion={...previousWeather};if(newSlot!==oldSlot||!Object.keys(weatherByRegion).length)for(const region of regions){const weather=selectWeather(definitions,region,newSlot,Number(instance.seed||0));if(weather)weatherByRegion[region]=weather.key;}await base44.asServiceRole.entities.WorldState.update(state.id,{current_time:after.toISOString(),weather_by_region:weatherByRegion,weather_slot:newSlot,version:Number(state.version||1)+1});if(state.world_instance_id){const instance=await base44.asServiceRole.entities.WorldInstance.get(state.world_instance_id);await base44.asServiceRole.entities.WorldInstance.update(instance.id,{current_time:after.toISOString(),version:Number(instance.version||1)+1});}await processTimedRuntimeEffects(base44,character,before,after);const environment=await loadWorldEnvironment(base44,character),weatherChanges=regions.filter(region=>previousWeather[region]!==weatherByRegion[region]).map(region=>({region,from:previousWeather[region]||null,to:weatherByRegion[region]||null})),events=await processWorldSignals(base44,character,{character,before:before.toISOString(),after:after.toISOString(),slot:newSlot,weatherChanges,world:environment.clock,weather:environment.weather});for(const event of events)await processQuestEvent(base44,await base44.asServiceRole.entities.Character.get(character.id),event);return await loadWorldEnvironment(base44,character);}