import { useEffect,useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import OperatorMemberSelector from '@/components/operator/OperatorMemberSelector';
import OperatorTabs from '@/components/operator/OperatorTabs';
import OperatorProfile from '@/components/operator/OperatorProfile';
import OperatorInventory from '@/components/operator/OperatorInventory';
import OperatorPartyPanel from '@/components/operator/OperatorPartyPanel';
import PageLayout from '@/components/runtime/PageLayout';
import PageAlert from '@/components/runtime/PageAlert';
import PageState from '@/components/runtime/PageState';
const validTabs=new Set(['profile','inventory','party']);
export default function Character(){
 const requestedTab=new URLSearchParams(window.location.search).get('tab')||'profile',[tab,setTab]=useState(validTabs.has(requestedTab)?requestedTab:'profile'),[partyData,setPartyData]=useState(null),[selectedId,setSelectedId]=useState(null),[profile,setProfile]=useState(null),[profileError,setProfileError]=useState(''),[profileReload,setProfileReload]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[empty,setEmpty]=useState(false);
 const loadParty=async characterId=>{setBusy(true);setError('');try{let id=characterId;if(!id){const {data}=await invokeRuntimeCommand({command:'GET_STATE'});if(!data.character){setEmpty(true);return}id=data.character.id;setSelectedId(id)}const {data}=await invokeRuntimeCommand({command:'GET_PARTY',characterId:id});setPartyData(data);setEmpty(false)}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}};
 useEffect(()=>{loadParty()},[]);
 useEffect(()=>{if(!selectedId||tab!=='profile')return;let active=true;setProfile(null);setProfileError('');invokeRuntimeCommand({command:'GET_CHARACTER_PROFILE',characterId:selectedId}).then(({data})=>active&&setProfile(data)).catch(caught=>active&&setProfileError(caught.response?.data?.error||caught.message));return()=>{active=false}},[selectedId,tab,profileReload]);
 if(error&&!partyData)return <PageState kind="error" title="Unable to load operators" description={error}/>;if(empty)return <PageState kind="empty" title="No active operator" description="Create a character from the Command page first."/>;if(!partyData)return <PageState title="Loading operators" description="Resolving party members, profiles, and storage."/>;
 const members=partyData.party?partyData.members:[{character:partyData.character,role:'operator'}],selected=members.find(member=>member.character.id===selectedId)?.character||partyData.character,changeTab=next=>{setTab(next);window.history.replaceState({},'',`${window.location.pathname}?tab=${next}`)},command=async payload=>{setBusy(true);setError('');try{const {data}=await invokeRuntimeCommand({characterId:partyData.character.id,requestId:crypto.randomUUID(),...payload});setPartyData(data);const ids=(data.party?data.members:[{character:data.character}]).map(member=>member.character.id);if(!ids.includes(selectedId))setSelectedId(data.character.id)}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}};
 const refreshAction=<button type="button" disabled={busy} onClick={()=>loadParty(partyData.character.id)} className="flex items-center gap-2 rounded border border-white/10 px-3 py-2 text-sm disabled:opacity-50"><RefreshCw size={15} className={busy?'animate-spin':''}/>Refresh</button>;
 return <PageLayout eyebrow="Operator system" title="Operator control" description="Manage every party member, their profile, equipment, personal inventory, and shared party storage." actions={refreshAction}><OperatorMemberSelector members={members} selectedId={selected.id} busy={busy} onSelect={setSelectedId}/><div className="mt-5"><OperatorTabs active={tab} busy={busy} onChange={changeTab}/></div>{error&&<div className="mt-4"><PageAlert message={error}/></div>}<div className="mt-5">{tab==='profile'&&<OperatorProfile profile={profile?.character.id===selected.id?profile:null} error={profileError} onRetry={()=>setProfileReload(value=>value+1)}/>} {tab==='inventory'&&<OperatorInventory key={selected.id} character={selected}/>} {tab==='party'&&<OperatorPartyPanel data={partyData} busy={busy} onCreate={name=>command({command:'CREATE_PARTY',name})} onAdd={memberCharacterId=>command({command:'ADD_PARTY_MEMBER',memberCharacterId})} onRemove={memberId=>command({command:'REMOVE_PARTY_MEMBER',memberId})} onDisband={()=>command({command:'DISBAND_PARTY'})}/>}</div></PageLayout>;
}