import { useEffect,useMemo,useState } from 'react';
import { Link } from 'react-router-dom';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import CombatRoster from '@/components/combat/CombatRoster';
import CombatActions from '@/components/combat/CombatActions';
import CombatLog from '@/components/combat/CombatLog';
import EncounterList from '@/components/combat/EncounterList';
import CombatToolbar from '@/components/combat/CombatToolbar';
import PageLayout from '@/components/runtime/PageLayout';
import PageAlert from '@/components/runtime/PageAlert';
import PageState from '@/components/runtime/PageState';

export default function Combat(){
 const [data,setData]=useState(null),[characters,setCharacters]=useState([]),[targetId,setTargetId]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(''),[error,setError]=useState(''),[empty,setEmpty]=useState(false),[reload,setReload]=useState(0);
 const invoke=async(payload,key='refresh')=>{setBusy(true);setPending(key);setError('');try{const {data:next}=await invokeRuntimeCommand(payload);setData(next);setTargetId(current=>next.participants?.some(item=>item.id===current&&item.team!=='player'&&item.status==='active')?current:next.participants?.find(item=>item.team!=='player'&&item.status==='active')?.id||'');return next}catch(caught){setError(caught.response?.data?.error||caught.message);return null}finally{setBusy(false);setPending('')}};
 const load=characterId=>invoke({command:'GET_COMBAT',characterId});
 useEffect(()=>{setError('');invokeRuntimeCommand({command:'GET_STATE'}).then(({data:state})=>{setCharacters(state.characters||[]);if(!state.character){setEmpty(true);return}load(state.character.id)}).catch(caught=>setError(caught.response?.data?.error||caught.message))},[reload]);
 const actor=useMemo(()=>data?.participants?.find(item=>item.id===data.combat?.active_participant_id),[data]),terminal=['VICTORY','DEFEAT','ESCAPED'].includes(data?.combat?.state),primaryResource=data?.game?.rules?.primary_resource_key||'vitality';
 if(empty)return <PageState kind="empty" title="Create a character first" description="Combat encounters require an active character." action={<Link to="/" className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Open Command Center</Link>}/>;
 if(!data&&error)return <PageState kind="error" title="Unable to load combat" description={error} action={<button onClick={()=>setReload(value=>value+1)} className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Try again</button>}/>;
 if(!data)return <PageState title="Loading combat state" description="Synchronizing participants, turn order, abilities, and combat events."/>;
 const start=encounterDefinitionId=>invoke({command:'START_ENCOUNTER',characterId:data.character.id,encounterDefinitionId,requestId:crypto.randomUUID()},`encounter:${encounterDefinitionId}`),submit=abilityId=>invoke({command:'SELECT_COMBAT_ACTION',characterId:data.character.id,combatId:data.combat.id,combatVersion:data.combat.version,targetParticipantId:targetId,abilityId,requestId:crypto.randomUUID()},`ability:${abilityId}`),close=()=>invoke({command:'COMPLETE_COMBAT',characterId:data.character.id,combatId:data.combat.id,requestId:crypto.randomUUID()},'close');
 const status=data.combat?<span className="rounded border border-white/10 bg-runtime-surface px-3 py-2 text-sm capitalize text-slate-300">Round {data.combat.round} · {data.combat.state.replaceAll('_',' ').toLowerCase()}</span>:null;
 return <PageLayout eyebrow="Runtime / Tactical resolution" title="Combat" description="Server-resolved actions with deterministic replay data." actions={<CombatToolbar characters={characters} characterId={data.character.id} onCharacterChange={load} onRefresh={()=>load(data.character.id)} busy={busy} status={status}/>}>{error&&<div className="mb-4"><PageAlert message={error}/></div>}{!data.combat?<EncounterList encounters={data.encounters} pending={pending} busy={busy} onStart={start}/>:<div className="grid gap-4 xl:grid-cols-[1fr_320px]"><div className="space-y-4"><CombatRoster participants={data.participants} activeId={data.combat.active_participant_id} selectedId={targetId} primaryResource={primaryResource} onSelect={setTargetId}/>{data.combat.state==='AWAITING_ACTIONS'?<CombatActions abilities={data.abilities} actor={actor} targetId={targetId} pending={pending} busy={busy} onSubmit={submit}/>:terminal?<div className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-runtime-surface p-4"><div><strong className="capitalize">{data.combat.state.toLowerCase()}</strong><p className="mt-1 text-sm text-slate-400">Review the combat log, then close this engagement.</p></div><button onClick={close} disabled={busy} className="rounded bg-runtime-accent px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{pending==='close'?'Closing…':'Close combat'}</button></div>:<PageState title="Resolving combat" description="The server is advancing the current engagement."/>}</div><CombatLog events={data.events} participants={data.participants} abilities={data.abilities}/></div>}</PageLayout>;
}