import { useEffect, useMemo, useState } from 'react';
import { Download, LayoutGrid, List, Search } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import InventorySummary from '@/components/inventory/InventorySummary';
import InventoryTable from '@/components/inventory/InventoryTable';
import InventoryGrid from '@/components/inventory/InventoryGrid';
import ItemDetailsDialog from '@/components/inventory/ItemDetailsDialog';
import InventoryBulkActions from '@/components/inventory/InventoryBulkActions';
import InventoryFilters from '@/components/inventory/InventoryFilters';

export default function Inventory() {
  const [data, setData] = useState(null), [query, setQuery] = useState(''), [category, setCategory] = useState('all'), [containerId, setContainerId] = useState('all'), [sort, setSort] = useState('name'), [view, setView] = useState('list'), [selected, setSelected] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [hasCharacter, setHasCharacter] = useState(true), [selectedIds, setSelectedIds] = useState([]);
  const invoke = async (payload) => { setBusy(true); setError(''); try { const response = await base44.functions.invoke('runtimeCommand', payload); setData(response.data); setSelected((current) => current ? response.data.items.find((item) => item.id === current.id) || null : null); return true; } catch (caught) { setError(caught.response?.data?.error || caught.message); return false; } finally { setBusy(false); } };
  useEffect(() => { base44.functions.invoke('runtimeCommand', { command: 'GET_STATE' }).then(({data:runtime}) => { setHasCharacter(!!runtime.character); if (runtime.character) invoke({ command: 'GET_INVENTORY', characterId: runtime.character.id }); }); }, []);
  const categories = [...new Set((data?.items || []).map((item) => item.definition.category).filter(Boolean))];
  const filtered = useMemo(() => (data?.items || []).filter((item) => (category === 'all' || item.definition.category === category) && (containerId === 'all' || item.container_id === containerId) && item.definition.name.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === 'newest' ? new Date(b.acquired_at) - new Date(a.acquired_at) : sort === 'weight' ? (b.definition.weight || 0) * b.quantity - (a.definition.weight || 0) * a.quantity : a.definition.name.localeCompare(b.definition.name)), [data, query, category, containerId, sort]);
  if (!hasCharacter) return <div className="p-6"><h2 className="text-2xl font-semibold">No active character</h2><p className="mt-2 text-sm text-slate-400">Create a character from the Runtime page before opening inventory.</p></div>;
  if (!data) return <div className="p-6 text-sm text-slate-400">Loading inventory…</div>;
  const action = (command, values = {}) => invoke({ command, characterId: data.character.id, itemId: selected.id, itemVersion: selected.version, ...values, requestId: crypto.randomUUID() });
  const collectLoot = () => invoke({ command: 'COLLECT_LOOT', characterId: data.character.id, requestId: crypto.randomUUID() });
  const toggleSelected = (id) => setSelectedIds((current) => current.includes(id) ? current.filter((itemId) => itemId !== id) : [...current, id]);
  const bulkMove = async (containerId) => { const moved = await invoke({ command: 'BULK_TRANSFER_ITEMS', characterId: data.character.id, containerId, items: data.items.filter((item) => selectedIds.includes(item.id)).map((item) => ({id: item.id, version: item.version})), requestId: crypto.randomUUID() }); if (moved) setSelectedIds([]); };
  return <div className="p-4 sm:p-6"><p className="text-xs uppercase tracking-[.22em] text-cyan-400">Character / Assets</p><h2 className="mt-1 text-2xl font-semibold">Inventory & equipment</h2><div className="mt-5"><InventorySummary summary={data.summary}/></div>
    {error && <div role="alert" className="mt-4 rounded-md border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</div>}
    <InventoryFilters categories={categories} category={category} onCategoryChange={setCategory} containers={data.containers} containerId={containerId} onContainerChange={setContainerId}/>
    <div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-500" size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search items" className="w-full rounded-md border border-white/10 bg-[#0a1728] py-2 pl-9 pr-3 text-sm"/></label><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-md border border-white/10 bg-[#0a1728] px-3 py-2 text-sm"><option value="name">Name</option><option value="newest">Newest</option><option value="weight">Weight</option></select><div className="flex rounded-md border border-white/10 bg-runtime-surface p-1"><button aria-label="List view" aria-pressed={view === 'list'} onClick={() => setView('list')} className={`rounded p-1.5 ${view === 'list' ? 'bg-cyan-400 text-slate-950' : 'text-slate-400'}`}><List size={16}/></button><button aria-label="Grid view" aria-pressed={view === 'grid'} onClick={() => setView('grid')} className={`rounded p-1.5 ${view === 'grid' ? 'bg-cyan-400 text-slate-950' : 'text-slate-400'}`}><LayoutGrid size={16}/></button></div>{data.summary.loot > 0 && <button disabled={busy || !data.summary.canCollectLoot} title={!data.summary.canCollectLoot ? 'Not enough carried capacity for all loot' : undefined} onClick={collectLoot} className="inline-flex items-center justify-center gap-2 rounded-md bg-cyan-400 px-3 py-2 text-sm font-medium text-slate-950 disabled:cursor-not-allowed disabled:opacity-50"><Download size={15}/>{data.summary.canCollectLoot ? 'Collect all loot' : 'Loot exceeds capacity'}</button>}</div>
    <div className="mt-3"><InventoryBulkActions count={selectedIds.length} containers={data.containers} busy={busy} onMove={bulkMove} onClear={() => setSelectedIds([])}/>{view === 'list' ? <InventoryTable items={filtered} selectedIds={selectedIds} onToggle={toggleSelected} onInspect={setSelected}/> : <InventoryGrid items={filtered} selectedIds={selectedIds} onToggle={toggleSelected} onInspect={setSelected}/>}</div><ItemDetailsDialog item={selected} items={data.items} containers={data.containers} busy={busy} onClose={() => setSelected(null)} onAction={action}/>
  </div>;
}