import { useEffect,useMemo,useState } from 'react';
import { Link } from 'react-router-dom';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import JournalControls from '@/components/journal/JournalControls';
import JournalEvent from '@/components/journal/JournalEvent';
import JournalQuestRecord from '@/components/journal/JournalQuestRecord';
import PageAlert from '@/components/runtime/PageAlert';
import PageLayout from '@/components/runtime/PageLayout';
import PageState from '@/components/runtime/PageState';
export default function Journal(){
 const [data,setData]=useState(null),[characters,setCharacters]=useState([]),[query,setQuery]=useState(''),[questState,setQuestState]=useState('all'),[eventCategory,setEventCategory]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[empty,setEmpty]=useState(false),[reload,setReload]=useState(0);
 const load=async characterId=>{setBusy(true);setError('');try{const {data:result}=await invokeRuntimeCommand({command:'GET_JOURNAL',characterId});setData(result)}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}};
 useEffect(()=>{setError('');invokeRuntimeCommand({command:'GET_STATE'}).then(({data:state})=>{setCharacters(state.characters||[]);if(!state.character){setEmpty(true);return}load(state.character.id)}).catch(caught=>setError(caught.response?.data?.error||caught.message))},[reload]);
 const categories=useMemo(()=>[...new Set((data?.events||[]).map(event=>event.event_type?.split('.')[0]).filter(Boolean))].sort(),[data]),needle=query.trim().toLowerCase(),quests=(data?.quests||[]).filter(quest=>(questState==='all'||quest.state===questState)&&(!needle||`${quest.definition?.name||''} ${quest.definition?.description||''} ${quest.state}`.toLowerCase().includes(needle))),events=(data?.events||[]).filter(event=>(eventCategory==='all'||event.event_type?.startsWith(`${eventCategory}.`))&&(!needle||`${event.event_type} ${JSON.stringify(event.payload||{})}`.toLowerCase().includes(needle)));
 if(empty)return <PageState kind="empty" title="Create a character first" description="The Journal records the history of an active character." action={<Link to="/" className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Open Command Center</Link>}/>;
 if(!data&&error)return <PageState kind="error" title="Unable to load journal" description={error} action={<button onClick={()=>setReload(value=>value+1)} className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Try again</button>}/>;
 if(!data)return <PageState title="Loading journal" description="Collecting mission history and recorded events."/>;
 return <PageLayout eyebrow="Character / History" title="Journal" description="Review mission outcomes and the character’s persistent event history.">{error&&<div className="mb-4"><PageAlert message={error}/></div>}<JournalControls characters={characters} characterId={data.character.id} onCharacterChange={load} query={query} onQueryChange={setQuery} questState={questState} onQuestStateChange={setQuestState} eventCategory={eventCategory} onEventCategoryChange={setEventCategory} categories={categories} onRefresh={()=>load(data.character.id)} busy={busy}/><div className="mt-4 grid gap-4 xl:grid-cols-[360px_1fr]"><section className="rounded-lg border border-white/10 bg-runtime-surface p-4"><h2 className="font-semibold">Mission record <span className="text-xs font-normal text-slate-500">({quests.length})</span></h2><div className="mt-3 space-y-2">{quests.map(quest=><JournalQuestRecord key={quest.id} quest={quest}/>)}{!quests.length&&<p className="text-sm text-slate-500">No missions match this view.</p>}</div></section><section className="rounded-lg border border-white/10 bg-runtime-surface p-4"><h2 className="font-semibold">Event history <span className="text-xs font-normal text-slate-500">({events.length})</span></h2><div className="mt-3 divide-y divide-white/5">{events.map(event=><JournalEvent key={event.id} event={event}/>)}{!events.length&&<p className="py-3 text-sm text-slate-500">No events match this view.</p>}</div></section></div></PageLayout>;
}