import { useEffect,useState } from 'react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import SettingsTabs from '@/components/settings/SettingsTabs';
import PreferencesPanel from '@/components/settings/PreferencesPanel';
import SoundPanel from '@/components/settings/SoundPanel';
import ShortcutTable from '@/components/settings/ShortcutTable';
import PageLayout from '@/components/runtime/PageLayout';
import PageAlert from '@/components/runtime/PageAlert';
import PageState from '@/components/runtime/PageState';

export default function Settings(){const [data,setData]=useState(null),[tab,setTab]=useState('preferences'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); const invoke=async payload=>{setBusy(true);setError('');try{const {data:next}=await invokeRuntimeCommand(payload);setData(next);window.dispatchEvent(new Event('runtime-settings-updated'));}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}}; useEffect(()=>{invoke({command:'GET_SETTINGS'})},[]); if(!data)return <PageState title="Loading settings" description="Preparing preferences, sound controls, and keyboard bindings."/>; const update=(scope,values)=>setData({...data,settings:{...data.settings,[scope]:values}}); return <PageLayout eyebrow="Account / Preferences" title="Settings & controls" description="Manage interface behavior, sound, accessibility preferences, and keyboard shortcuts."><div><SettingsTabs active={tab} onChange={setTab}/></div>{error&&<div className="mt-4"><PageAlert message={error}/></div>}<div className="mt-4">{tab==='preferences'&&<PreferencesPanel settings={data.settings} onChange={update} busy={busy} onSave={scope=>invoke({command:'SAVE_SETTINGS',scope,values:data.settings[scope]})}/>} {tab==='sound'&&<SoundPanel settings={data.settings.sound} onChange={values=>update('sound',values)} busy={busy} onSave={()=>invoke({command:'SAVE_SETTINGS',scope:'sound',values:data.settings.sound})}/>} {tab==='shortcuts'&&<ShortcutTable bindings={data.bindings} query={query} onQuery={setQuery} busy={busy} onChange={(commandId,binding)=>invoke({command:'SAVE_KEY_BINDING',commandId,binding})} onReset={()=>invoke({command:'RESET_KEY_BINDINGS'})}/>}</div></PageLayout>}