import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import SkillsPanel from '@/components/skills/SkillsPanel';
import SkillsToolbar from '@/components/skills/SkillsToolbar';
import LoadoutList from '@/components/skills/LoadoutList';
import LoadoutEditor from '@/components/skills/LoadoutEditor';
import PageLayout from '@/components/runtime/PageLayout';
import PageAlert from '@/components/runtime/PageAlert';
import PageState from '@/components/runtime/PageState';
export default function Skills(){
 const [data,setData]=useState(null),[characters,setCharacters]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[empty,setEmpty]=useState(false),[reload,setReload]=useState(0);
 const run=async payload=>{setBusy(true);setError('');try{const {data:next}=await invokeRuntimeCommand(payload);setData(next);return next}catch(caught){setError(caught.response?.data?.error||caught.message);return null}finally{setBusy(false)}};
 const load=characterId=>{setSelected(null);return run({command:'GET_CAPABILITIES',characterId})};
 useEffect(()=>{setError('');invokeRuntimeCommand({command:'GET_STATE'}).then(({data:state})=>{setCharacters(state.characters||[]);if(!state.character){setEmpty(true);return}load(state.character.id)}).catch(caught=>setError(caught.response?.data?.error||caught.message))},[reload]);
 const command=payload=>run({characterId:data.character.id,requestId:crypto.randomUUID(),...payload}),save=async(values,apply)=>{const before=new Set(data.loadouts.map(item=>item.id)),saved=await command({command:'SAVE_LOADOUT',loadoutId:selected.id,loadoutVersion:selected.version,values});if(!saved)return;const updated=selected.id?saved.loadouts.find(item=>item.id===selected.id):saved.loadouts.find(item=>!before.has(item.id));setSelected(updated||null);if(apply&&updated){const applied=await run({command:'ACTIVATE_LOADOUT',characterId:saved.character.id,loadoutId:updated.id,loadoutVersion:updated.version,requestId:crypto.randomUUID()});if(applied)setSelected(applied.loadouts.find(item=>item.id===updated.id)||null)}};
 if(empty)return <PageState kind="empty" title="Create a character first" description="Skills and loadouts belong to an active character." action={<Link to="/" className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Open Command Center</Link>}/>;
 if(!data&&error)return <PageState kind="error" title="Unable to load skills" description={error} action={<button onClick={()=>setReload(value=>value+1)} className="rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950">Try again</button>}/>;
 if(!data)return <PageState title="Loading capabilities" description="Resolving skills, abilities, equipment, and saved loadouts."/>;
 return <PageLayout eyebrow="Character / Capabilities" title="Skills & loadouts" description="Train classless skills and prepare equipment, abilities, and quick-slot items." actions={<SkillsToolbar characters={characters} characterId={data.character.id} onCharacterChange={load} onRefresh={()=>load(data.character.id)} busy={busy}/>}>{error&&<div className="mb-4"><PageAlert message={error}/></div>}<SkillsPanel skills={data.skills} currency={data.character.currency} busy={busy} onTrain={skillDefinitionId=>command({command:'TRAIN_SKILL',skillDefinitionId})}/><div className="mt-5 grid gap-4 lg:grid-cols-[260px_1fr]"><LoadoutList loadouts={data.loadouts} selected={selected} busy={busy} onSelect={setSelected} onAdd={()=>setSelected({})}/>{selected?<LoadoutEditor loadout={selected} abilities={data.abilities} unlockedAbilityIds={data.unlockedAbilityIds||[]} items={data.items} busy={busy} onCancel={()=>setSelected(null)} onSave={save} onActivate={()=>command({command:'ACTIVATE_LOADOUT',loadoutId:selected.id,loadoutVersion:selected.version}).then(next=>next&&setSelected(next.loadouts.find(item=>item.id===selected.id)||null))} onDelete={()=>window.confirm('Delete this loadout?')&&command({command:'DELETE_LOADOUT',loadoutId:selected.id,loadoutVersion:selected.version}).then(next=>next&&setSelected(null))}/>:<div className="grid min-h-64 place-items-center rounded-lg border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">Select a loadout or create a new one.</div>}</div></PageLayout>;
}