import { useEffect,useState } from 'react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import { Boxes,GitBranch,Map,PackageCheck } from 'lucide-react';
import ReleaseManager from '@/components/studio/ReleaseManager';
import MigrationPanel from '@/components/studio/MigrationPanel';
import OperationsPanel from '@/components/studio/OperationsPanel';
import ContentWorkspace from '@/components/studio/ContentWorkspace';
import GameConfiguration from '@/components/studio/GameConfiguration';
import GameWizard from '@/components/studio/GameWizard';
import StudioTabs from '@/components/studio/StudioTabs';
import SimulationConsole from '@/components/studio/SimulationConsole';
import ContentPackManager from '@/components/studio/ContentPackManager';
import PageLayout from '@/components/runtime/PageLayout';
import PageAlert from '@/components/runtime/PageAlert';
import PageState from '@/components/runtime/PageState';
const cards=[{key:'games',label:'Games',icon:Boxes},{key:'packs',label:'Content packs',icon:Boxes},{key:'releases',label:'Releases',icon:PackageCheck},{key:'locations',label:'Locations',icon:Map},{key:'quests',label:'Quests',icon:GitBranch}];
export default function Studio(){const [data,setData]=useState(null),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(null);const load=()=>invokeRuntimeCommand({command:'STUDIO_OVERVIEW'}).then(({data})=>setData(data));useEffect(()=>{load()},[]);const run=async(payload,reload=true)=>{setBusy(true);setError('');try{const {data:result}=await invokeRuntimeCommand(payload);if(result.preview)setPreview(result.preview);if(reload)await load()}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};if(!data)return <PageState title="Loading Game Studio" description="Preparing games, releases, authoring tools, and operational data."/>;return <PageLayout eyebrow="Administration / Content platform" title="Game Studio" description="Create games, author versioned content, validate releases, and migrate runtime data." actions={tab==='overview'?<GameWizard busy={busy} onCreate={values=>run({command:'CREATE_GAME',...values})}/>:null}>{error&&<div className="mt-4"><PageAlert message={error}/></div>}<div className="mt-5"><StudioTabs active={tab} onChange={setTab}/></div><div className="mt-5">{tab==='overview'&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({key,label,icon:Icon})=><div key={key} className="rounded-lg border border-white/10 bg-runtime-surface p-4"><Icon className="text-runtime-accent" size={18}/><p className="mt-5 text-3xl font-semibold">{data.counts[key]}</p><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p></div>)}</div><div className="mt-5"><ContentPackManager games={data.games} packs={data.packs||[]} busy={busy} onCreate={(gameId,values)=>run({command:'CREATE_CONTENT_PACK',gameId,values})}/></div><div className="mt-5"><ReleaseManager games={data.games} releases={data.releases} busy={busy} onCreate={(gameId,version)=>run({command:'CREATE_RELEASE',gameId,version})} onValidate={releaseId=>run({command:'VALIDATE_RELEASE',releaseId})} onPublish={releaseId=>run({command:'PUBLISH_RELEASE',releaseId})}/></div><div className="mt-5"><MigrationPanel characters={data.characters} releases={data.releases} busy={busy} preview={preview} onPreview={(characterId,releaseId)=>run({command:'PREVIEW_MIGRATION',characterId,releaseId},false)} onMigrate={(characterId,releaseId)=>run({command:'MIGRATE_CHARACTER',characterId,releaseId})}/></div></>}{tab==='content'&&<ContentWorkspace games={data.games} releases={data.releases}/>} {tab==='configuration'&&<GameConfiguration games={data.games} busy={busy} onSave={(gameId,values)=>run({command:'SAVE_GAME_CONFIG',gameId,values})}/>} {tab==='simulation'&&<SimulationConsole/>} {tab==='operations'&&<OperationsPanel/>}</div></PageLayout>}