import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Check, Circle, LoaderCircle, X } from 'lucide-react';

export default function QuestDialog({ quest, available, busy, onClose, onAction }) {
  if (!quest) return null;
  const definition = quest.definition || quest;
  const objectives = quest.objectives || definition.objective_graph?.objectives || [];
  const branches = definition.objective_graph?.branches || [], selectedBranch = quest.branch_state?.selected_branch;
  const rewardChoices = definition.reward_selection?.choices || [];
  const completedKeys = new Set(objectives.filter(item => item.state === 'COMPLETED').map(item => item.objective_key || item.key));
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="border-white/10 bg-runtime-surface text-slate-100 sm:max-w-xl"><DialogHeader><DialogTitle>{definition.name}</DialogTitle><DialogDescription className="text-slate-400">{definition.description||'No mission description is defined.'}</DialogDescription></DialogHeader>
    {(quest.expires_at || quest.failed_at) && <p className="text-xs text-slate-500">{quest.failed_at ? `Failed ${new Date(quest.failed_at).toLocaleString()}` : `Expires ${new Date(quest.expires_at).toLocaleString()}`}</p>}
    <div><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Objectives</p><div className="space-y-2">{objectives.map((objective) => { const complete = objective.state === 'COMPLETED', failed = objective.state === 'FAILED'; return <div key={objective.id || objective.key} className="flex items-center gap-2 text-sm">{complete ? <Check size={15} className="text-emerald-400"/> : failed ? <X size={15} className="text-red-400"/> : <Circle size={13} className="text-slate-600"/>}<span className={complete ? 'text-slate-500 line-through' : failed ? 'text-red-300' : ''}>{objective.label || objective.objective_key}</span>{objective.required_count > 1 && <span className="text-xs text-slate-500">{objective.current_count || 0}/{objective.required_count}</span>}{objective.state === 'PENDING' && <span className="text-xs text-amber-300">Locked</span>}{objective.state === 'SKIPPED' && <span className="text-xs text-slate-500">Other path</span>}{failed && <span className="text-xs text-red-400">Failed</span>}{objective.optional && <span className="text-xs text-slate-600">Optional</span>}</div>; })}{!objectives.length&&<p className="text-sm text-slate-500">No objectives are defined.</p>}</div></div>
    {!available && quest.state === 'ACTIVE' && branches.length > 0 && !selectedBranch && <div><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Choose a path</p><div className="space-y-2">{branches.map(branch => { const locked = (branch.dependsOn || []).some(key => !completedKeys.has(key)); return <button key={branch.key} disabled={busy || locked} onClick={() => onAction('SELECT_QUEST_BRANCH', {branchKey: branch.key})} className="w-full rounded border border-amber-300/20 bg-amber-300/5 p-3 text-left disabled:opacity-40"><span className="block text-sm font-medium text-amber-200">{branch.label || branch.key}</span>{branch.description && <span className="mt-1 block text-xs text-slate-400">{branch.description}</span>}{locked && <span className="mt-1 block text-xs text-slate-500">Complete earlier objectives to unlock</span>}</button>; })}</div></div>}
    {selectedBranch && <p className="text-xs text-amber-200">Selected path: {branches.find(branch => branch.key === selectedBranch)?.label || selectedBranch}</p>}
    {!!definition.rewards?.length && <div><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Guaranteed rewards</p>{definition.rewards.map((reward,index)=><p key={index} className="text-sm text-runtime-accent">{rewardText(reward,definition)}</p>)}</div>}
    {quest.state === 'COMPLETED' && quest.reward_state === 'pending' && rewardChoices.length > 0 && <div><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Choose your reward</p><div className="space-y-2">{rewardChoices.map(choice=><button key={choice.key} disabled={busy} onClick={()=>onAction('SELECT_QUEST_REWARD',{choiceKey:choice.key})} className="w-full rounded border border-runtime-accent/20 bg-runtime-accent/10 p-3 text-left text-sm text-runtime-accent disabled:opacity-50"><span className="font-medium">{choice.label||choice.key}</span>{!!choice.rewards?.length&&<span className="mt-1 block text-xs text-slate-400">{choice.rewards.map(reward=>rewardText(reward,definition)).join(' · ')}</span>}</button>)}</div></div>}
    <div className="flex justify-end">{available ? <Action busy={busy} onClick={() => onAction('ACCEPT_QUEST')}>Accept mission</Action> : quest.state === 'ACTIVE' ? <Action busy={busy} danger onClick={()=>window.confirm('Abandon this mission? Current progress will be lost.')&&onAction('ABANDON_QUEST')}>Abandon mission</Action> : <span className="text-sm capitalize text-slate-400">{quest.state.toLowerCase()}</span>}</div>
  </DialogContent></Dialog>;
}
function rewardText(reward,definition){const amount=reward.type==='item'?reward.quantity||1:reward.amount||0,key=reward.type==='item'?definition.reward_item_names?.[reward.itemDefinitionId]||'Item':reward.type==='currency'?reward.currencyId:reward.resourceId;return `${amount} ${key||reward.type}`}
function Action({children,onClick,busy,danger}) { return <button disabled={busy} onClick={onClick} className={`flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium ${danger ? 'border border-red-400/20 text-red-300' : 'bg-cyan-400 text-slate-950'}`}>{busy && <LoaderCircle size={14} className="animate-spin"/>}{children}</button>; }