import { useEffect,useMemo,useState } from 'react';
import { Download,LayoutGrid,List,LoaderCircle,Search } from 'lucide-react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import InventorySummary from '@/components/inventory/InventorySummary';
import InventoryTable from '@/components/inventory/InventoryTable';
import InventoryGrid from '@/components/inventory/InventoryGrid';
import ItemDetailsDialog from '@/components/inventory/ItemDetailsDialog';
import InventoryBulkActions from '@/components/inventory/InventoryBulkActions';
import InventoryFilters from '@/components/inventory/InventoryFilters';
import InventoryContextPanel from '@/components/inventory/InventoryContextPanel';
import PageAlert from '@/components/runtime/PageAlert';
export default function OperatorInventory({character}){
 const [data,setData]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[containerId,setContainerId]=useState('all'),[quality,setQuality]=useState('all'),[assignment,setAssignment]=useState('all'),[sort,setSort]=useState('name'),[view,setView]=useState('list'),[selected,setSelected]=useState(null),[selectedIds,setSelectedIds]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const invoke=async payload=>{setBusy(true);setError('');try{const {data:next}=await invokeRuntimeCommand(payload);setData(next);setSelected(current=>current?next.items.find(item=>item.id===current.id)||null:null);setSelectedIds(current=>current.filter(id=>next.items.some(item=>item.id===id)));return true}catch(caught){setError(caught.response?.data?.error||caught.message);return false}finally{setBusy(false)}};
 useEffect(()=>{setData(null);setSelected(null);setSelectedIds([]);invoke({command:'GET_INVENTORY',characterId:character.id})},[character.id]);
 const categories=[...new Set((data?.items||[]).map(item=>item.definition.category).filter(Boolean))],qualities=[...new Set((data?.items||[]).map(item=>item.quality).filter(Boolean))];
 const filtered=useMemo(()=>(data?.items||[]).filter(item=>(category==='all'||item.definition.category===category)&&(containerId==='all'||item.container_id===containerId)&&(quality==='all'||item.quality===quality)&&(assignment==='all'||(assignment==='equipped')===!!item.equipped_slot)&&item.definition.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='newest'?new Date(b.acquired_at)-new Date(a.acquired_at):sort==='weight'?(b.definition.weight||0)*b.quantity-(a.definition.weight||0)*a.quantity:a.definition.name.localeCompare(b.definition.name)),[data,query,category,containerId,quality,assignment,sort]);
 if(!data&&error)return <div className="rounded-lg border border-white/10 bg-runtime-surface p-4"><PageAlert message={error}/><button type="button" disabled={busy} onClick={()=>invoke({command:'GET_INVENTORY',characterId:character.id})} className="mt-3 rounded border border-white/10 px-3 py-2 text-sm disabled:opacity-50">Try again</button></div>;
 if(!data)return <div role="status" className="grid min-h-64 place-items-center rounded-lg border border-white/10 bg-runtime-surface text-sm text-slate-400"><span className="flex items-center gap-2"><LoaderCircle size={17} className="animate-spin text-runtime-accent"/>Loading {character.name}'s inventory</span></div>;
 const action=(command,values={},item=selected)=>invoke({command,characterId:character.id,itemId:item.id,itemVersion:item.version,...values,requestId:crypto.randomUUID()}),rowAction=(item,command,values={})=>action(command,values,item),collectLoot=()=>invoke({command:'COLLECT_LOOT',characterId:character.id,requestId:crypto.randomUUID()}),toggle=id=>setSelectedIds(current=>current.includes(id)?current.filter(itemId=>itemId!==id):[...current,id]);
 const bulkMove=async destination=>{const moved=await invoke({command:'BULK_TRANSFER_ITEMS',characterId:character.id,containerId:destination,items:data.items.filter(item=>selectedIds.includes(item.id)).map(item=>({id:item.id,version:item.version})),requestId:crypto.randomUUID()});if(moved)setSelectedIds([])};
 const activeContainer=data.containers.find(container=>container.id===containerId)?.name||'All containers',lootAction=data.summary.loot>0?<button disabled={busy||!data.summary.canCollectLoot} onClick={collectLoot} className="inline-flex items-center gap-2 rounded-md bg-runtime-accent px-3 py-2 text-sm font-medium text-slate-950 disabled:opacity-50"><Download size={15}/>Collect loot</button>:null;
 return <div><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-wider text-runtime-accent">Selected member</p><h2 className="mt-1 text-xl font-semibold">{character.name}'s inventory</h2><p className="mt-1 text-sm text-slate-400">Personal equipment and shared party storage.</p></div>{lootAction}</div><InventorySummary summary={data.summary}/>{error&&<div className="mt-4"><PageAlert message={error}/></div>}<div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]"><section className="min-w-0 rounded-lg border border-white/10 bg-runtime-surface p-3 sm:p-4"><InventoryFilters categories={categories} category={category} onCategoryChange={setCategory} containers={data.containers} containerId={containerId} onContainerChange={setContainerId} qualities={qualities} quality={quality} onQualityChange={setQuality} assignment={assignment} onAssignmentChange={setAssignment}/><div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-500" size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search items" className="w-full rounded-md border border-white/10 bg-runtime py-2 pl-9 pr-3 text-sm"/></label><select aria-label="Sort inventory" value={sort} onChange={event=>setSort(event.target.value)} className="rounded-md border border-white/10 bg-runtime px-3 py-2 text-sm"><option value="name">Name</option><option value="newest">Newest</option><option value="weight">Weight</option></select><div className="flex rounded-md border border-white/10 bg-runtime p-1"><button aria-label="List view" onClick={()=>setView('list')} className={`rounded p-1.5 ${view==='list'?'bg-runtime-accent text-slate-950':'text-slate-400'}`}><List size={16}/></button><button aria-label="Grid view" onClick={()=>setView('grid')} className={`rounded p-1.5 ${view==='grid'?'bg-runtime-accent text-slate-950':'text-slate-400'}`}><LayoutGrid size={16}/></button></div></div><div className="mt-3"><InventoryBulkActions count={selectedIds.length} containers={data.containers} busy={busy} onMove={bulkMove} onClear={()=>setSelectedIds([])}/>{view==='list'?<InventoryTable items={filtered} selectedIds={selectedIds} onToggle={toggle} onInspect={setSelected} onAction={rowAction} busy={busy}/>:<InventoryGrid items={filtered} selectedIds={selectedIds} onToggle={toggle} onInspect={setSelected} onAction={rowAction} busy={busy}/>}</div></section><InventoryContextPanel items={data.items} filteredCount={filtered.length} selectedCount={selectedIds.length} category={category} container={activeContainer}/></div><ItemDetailsDialog item={selected} items={data.items} containers={data.containers} character={data.character} busy={busy} onClose={()=>setSelected(null)} onAction={action} onContextualExecuted={()=>invoke({command:'GET_INVENTORY',characterId:character.id})}/></div>;
}