import { useEffect,useState } from 'react';
import { Bell } from 'lucide-react';
import { Link } from 'react-router-dom';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
export default function NotificationCenter(){
 const [data,setData]=useState({notifications:[],unread:0}),[open,setOpen]=useState(false),[busyId,setBusyId]=useState('');
 const load=()=>invokeRuntimeCommand({command:'GET_NOTIFICATIONS'}).then(({data:next})=>setData(next)).catch(()=>null);
 useEffect(()=>{load();const timer=setInterval(load,30000),refresh=()=>load();window.addEventListener('notifications:changed',refresh);return()=>{clearInterval(timer);window.removeEventListener('notifications:changed',refresh)}},[]);
 const read=async item=>{setOpen(false);if(item.read)return;setBusyId(item.id);try{const {data:next}=await invokeRuntimeCommand({command:'MARK_NOTIFICATION_READ',notificationId:item.id});setData(next);window.dispatchEvent(new Event('notifications:changed'))}catch{return}finally{setBusyId('')}};
 return <div className="relative"><button aria-label={`Notifications, ${data.unread} unread`} aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="relative rounded p-2 text-slate-400 hover:bg-white/5 hover:text-runtime-text"><Bell size={18}/>{data.unread>0&&<span className="absolute right-0 top-0 min-w-4 rounded-full bg-runtime-accent px-1 text-center text-[10px] font-bold text-slate-950">{data.unread}</span>}</button>{open&&<div className="absolute right-0 top-11 z-50 w-80 max-w-[calc(100vw-2rem)] overflow-hidden rounded-lg border border-white/10 bg-runtime-surface shadow-xl"><p className="border-b border-white/10 px-4 py-3 text-sm font-semibold">Notifications</p><div className="max-h-80 overflow-y-auto">{data.notifications.slice(0,8).map(item=><Link key={item.id} to={item.link?.startsWith('/')?item.link:'/messages'} onClick={()=>read(item)} aria-disabled={busyId===item.id} className={`block border-b border-white/5 px-4 py-3 text-sm hover:bg-white/5 ${item.read?'text-slate-500':'text-runtime-text'}`}><span className="flex items-center gap-2"><strong className="block flex-1">{item.title}</strong>{!item.read&&<span className="h-2 w-2 rounded-full bg-runtime-accent"/>}</span><span className="mt-1 block text-xs text-slate-500">{item.message}</span></Link>)}{!data.notifications.length&&<p className="p-4 text-sm text-slate-500">No notifications</p>}</div><Link to="/messages" onClick={()=>setOpen(false)} className="block border-t border-white/10 px-4 py-3 text-center text-xs font-semibold text-runtime-accent hover:bg-white/5">View all messages</Link></div>}</div>;
}