import { useEffect,useState } from 'react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import ContentForm from '@/components/studio/ContentForm';
import ContentJsonEditor from '@/components/studio/ContentJsonEditor';
import ContentList from '@/components/studio/ContentList';
import ContentAuthoringSummary from '@/components/studio/ContentAuthoringSummary';
import BulkContentUpload from '@/components/studio/BulkContentUpload';
import WorldGraphEditor from '@/components/studio/WorldGraphEditor';
import { contentConfigs } from '@/lib/studioContentConfig';
import useStudioDraft from '@/hooks/useStudioDraft';
import DraftHistoryToolbar from '@/components/studio/DraftHistoryToolbar';
import ContentLifecycleActions from '@/components/studio/ContentLifecycleActions';
const reserved=new Set(['id','created_date','updated_date','created_by_id','game_id','content_version','is_sample','revision','content_ref','pack_id']);
const editable=item=>Object.fromEntries(Object.entries(item||{}).filter(([key])=>!reserved.has(key)));
const prepareDraft=(item,fields)=>{const value=editable(item),arrays=new Set(['tags','dialogueGraph','npcInteractions','references','rewards','worldEventEffects','worldEventEmissions','effects','events']);for(const field of fields||[]){if(value[field.key]!==undefined)continue;if(field.type==='json')value[field.key]=JSON.parse(field.empty||'{}');else if(arrays.has(field.type))value[field.key]=[];else if(field.type==='worldEventTrigger')value[field.key]={type:'at_time',at_minute:0};else if(['worldEventConditions','conditions'].includes(field.type))value[field.key]={};else if(field.type==='formulaExpression')value[field.key]={constant:0};else if(field.type==='checkbox')value[field.key]=false;else value[field.key]=''}return value};
export default function ContentWorkspace({games,releases,packs=[]}){
  const params=new URLSearchParams(window.location.search),requestedType=params.get('type'),requestedItem=params.get('item');
  const drafts=releases.filter(x=>x.status==='draft'),[releaseId,setReleaseId]=useState(drafts[0]?.id||''),[packId,setPackId]=useState(drafts[0]?.content_pack_ids?.[0]||''),[type,setType]=useState(contentConfigs[requestedType]?requestedType:'LocationDefinition'),[targetItemId,setTargetItemId]=useState(requestedItem||''),[mode,setMode]=useState('structured'),[items,setItems]=useState([]),[search,setSearch]=useState(''),[hasMore,setHasMore]=useState(false),[references,setReferences]=useState({}),[selected,setSelected]=useState(null),[workspaceRelease,setWorkspaceRelease]=useState(null),[conflict,setConflict]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const draft=useStudioDraft(),config=contentConfigs[type],sourceRelease=releases.find(x=>x.id===releaseId),release=workspaceRelease?.id===releaseId?workspaceRelease:sourceRelease;
  const leaveDraft=action=>{if(draft.canLeave())action()};
  const selectItem=item=>leaveDraft(()=>{setSelected(item);draft.reset(prepareDraft(item,config?.fields))});
  const closeItem=()=>leaveDraft(()=>{setSelected(null);draft.reset({})});
  const load=async({append=false,skip=0,query=search,resetSelection=true}={})=>{if(!releaseId||type==='WorldGraph')return;setBusy(true);try{const {data}=await invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType:type,search:query,itemId:targetItemId||undefined,skip,limit:50});setItems(current=>append?[...current,...data.items]:data.items);setHasMore(!!data.page?.has_more);setWorkspaceRelease(data.release);if(targetItemId&&data.items[0]){setSelected(data.items[0]);draft.reset(prepareDraft(data.items[0],config?.fields));setTargetItemId('')}else if(resetSelection){setSelected(null);draft.reset({})}setConflict(null);setError('')}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};
  useEffect(()=>{setSearch('');setPackId((releases.find(item=>item.id===releaseId)?.content_pack_ids||[])[0]||'');load({query:'',resetSelection:true})},[releaseId,type]);
  useEffect(()=>{const timer=setTimeout(()=>load({query:search,resetSelection:false}),250);return()=>clearTimeout(timer)},[search]);
  useEffect(()=>{const types=[...new Set((config?.fields||[]).flatMap(field=>[field.referenceType,...(field.referenceTypes||[])]).filter(Boolean))];if(!releaseId||!types.length){setReferences({});return}Promise.all(types.map(contentType=>invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType}))).then(results=>setReferences(Object.fromEntries(types.map((contentType,index)=>[contentType,results[index].data.items])))).catch(e=>setError(e.response?.data?.error||e.message))},[releaseId,type]);
  const referenceSearch=async(contentType,query)=>{const {data}=await invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType,search:query,limit:50,skip:0});return data.items};
  const mutate=async payload=>{setBusy(true);setConflict(null);try{await invokeRuntimeCommand({...payload,releaseId,contentType:type,expectedReleaseRevision:release?.revision||1,...(payload.itemId?{expectedRevision:selected?.revision}: {})});await load()}catch(e){const data=e.response?.data;setError(data?.error||e.message);setConflict(data?.conflict||null);setBusy(false)}};
  if(!drafts.length)return <div className="rounded-lg border border-amber-300/20 bg-amber-300/5 p-5 text-sm text-amber-200">Create a draft release before authoring content.</div>;
  return <div className="space-y-4">
    <section className="rounded-xl border border-white/10 bg-[#0d1729] p-4 shadow-lg shadow-black/10">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(200px,0.8fr)_minmax(180px,0.7fr)_minmax(240px,1.2fr)_auto]">
        <label className="text-sm text-slate-300">Draft release<select value={releaseId} onChange={e=>leaveDraft(()=>setReleaseId(e.target.value))} className="mt-2 w-full rounded-lg border border-slate-700 bg-[#111d31] px-3 py-2.5 text-sm">{drafts.map(x=><option key={x.id} value={x.id}>{games.find(g=>g.id===x.game_id)?.title} · v{x.version}</option>)}</select></label>
        <label className="text-sm text-slate-300">Content pack<select value={packId} onChange={e=>leaveDraft(()=>setPackId(e.target.value))} className="mt-2 w-full rounded-lg border border-slate-700 bg-[#111d31] px-3 py-2.5 text-sm">{(release?.content_pack_ids||[]).map(id=><option key={id} value={id}>{packs.find(pack=>pack.id===id)?.name||id}</option>)}</select></label>
        <label className="text-sm text-slate-300">Content type<select value={type} onChange={e=>leaveDraft(()=>setType(e.target.value))} className="mt-2 w-full rounded-lg border border-cyan-400 bg-[#111d31] px-3 py-2.5 text-sm"><option value="WorldGraph">World connection graph</option>{Object.entries(contentConfigs).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label>
        <div><p className="text-sm text-slate-300">Mode</p><div className="mt-2 flex rounded-lg border border-slate-700 bg-[#111d31] p-0.5"><button type="button" onClick={()=>setMode('structured')} className={`rounded-md px-3 py-2 text-xs ${mode==='structured'?'bg-cyan-400 font-semibold text-slate-950':'text-slate-300'}`}>Structured</button><button type="button" onClick={()=>setMode('json')} className={`rounded-md px-3 py-2 text-xs ${mode==='json'?'bg-cyan-400 font-semibold text-slate-950':'text-slate-300'}`}>Full JSON</button></div></div>
      </div><p className="mt-4 border-t border-white/10 pt-4 text-sm text-slate-400">Draft content is editable until publication.</p>
    </section>
    {error&&<div className="rounded-lg border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200"><p>{error}</p>{conflict&&<button type="button" onClick={load} className="mt-2 rounded border border-red-300/30 px-3 py-1.5 text-xs font-semibold">Reload latest content</button>}</div>}
    {type==='WorldGraph'?<WorldGraphEditor releaseId={releaseId}/>:<div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_260px]">
      <main className="space-y-4"><ContentList label={config.label} items={items} selected={selected} onSelect={selectItem} onAdd={()=>selectItem({})} locked={!release||release.status!=='draft'} search={search} onSearch={setSearch} hasMore={hasMore} onLoadMore={()=>!busy&&load({append:true,skip:items.length,query:search,resetSelection:false})}/>{selected?<><DraftHistoryToolbar dirty={draft.dirty} canUndo={draft.canUndo} canRedo={draft.canRedo} onUndo={draft.undo} onRedo={draft.redo}/><ContentLifecycleActions key={selected.id} item={selected} items={items} packs={packs.filter(pack=>(release?.content_pack_ids||[]).includes(pack.id))} packId={selected.pack_id||packId} busy={busy} onAction={mutate}/>{mode==='json'?<ContentJsonEditor item={selected} values={draft.value} busy={busy} onCancel={closeItem} onChangeValues={draft.update} onSave={values=>mutate({command:'SAVE_STUDIO_CONTENT',itemId:selected.id,packId,values})} onDelete={selected.id?()=>window.confirm('Delete this draft content?')&&mutate({command:'DELETE_STUDIO_CONTENT',itemId:selected.id}):null}/>:<ContentForm item={selected} fields={config.fields} references={references} referenceSearch={referenceSearch} values={draft.value} busy={busy} onCancel={closeItem} onChangeValues={draft.update} onSave={values=>mutate({command:'SAVE_STUDIO_CONTENT',itemId:selected.id,packId,values})} onDelete={selected.id?()=>window.confirm('Delete this draft content?')&&mutate({command:'DELETE_STUDIO_CONTENT',itemId:selected.id}):null}/>}</>:<div className="overflow-hidden rounded-xl border border-white/10 bg-[#0d1729]"><h3 className="border-b border-white/10 p-4 font-semibold text-slate-100">Empty state</h3><div className="grid min-h-40 place-items-center p-6 text-sm text-slate-500">Select a record or create one.</div></div>}</main>
      <div className="space-y-4"><ContentAuthoringSummary release={release} config={config} item={selected} values={draft.value} mode={mode} count={items.length}/><BulkContentUpload releaseId={releaseId} releaseRevision={release?.revision||1} contentType={type} packId={packId} busy={busy} onImported={load} onError={setError}/></div>
    </div>}
  </div>;
}