import { useState } from 'react';
import { Download,Upload } from 'lucide-react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import PageAlert from '@/components/runtime/PageAlert';
export default function ContentPackTransfer({games,onImported}){
  const [gameId,setGameId]=useState(games[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[summary,setSummary]=useState('');
  const exportAll=async()=>{setBusy(true);setError('');try{const {data}=await invokeRuntimeCommand({command:'EXPORT_CONTENT_PACKS',gameId});const blob=new Blob([JSON.stringify(data.bundle,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${data.bundle.manifest.source_game.key}-content-bundle.json`;link.click();URL.revokeObjectURL(url);setSummary(`Exported ${data.bundle.manifest.pack_count} packs.`)}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}};
  const importAll=async file=>{if(!file)return;setBusy(true);setError('');try{const bundle=JSON.parse(await file.text()),{data}=await invokeRuntimeCommand({command:'IMPORT_CONTENT_PACKS',gameId,bundle});setSummary(`Imported ${data.summary.packs} packs, ${data.summary.releases} releases, and ${data.summary.records} records as drafts.`);await onImported()}catch(caught){setError(caught.response?.data?.error||caught.message)}finally{setBusy(false)}};
  return <section className="rounded-lg border border-white/10 bg-runtime-surface p-4"><h2 className="font-semibold">Pack portability</h2><p className="mt-1 text-xs text-slate-500">Export every pack status with release manifests and versioned content. Imports always create draft copies.</p><div className="mt-4 flex flex-wrap gap-2"><select value={gameId} onChange={event=>setGameId(event.target.value)} className="min-w-56 rounded border border-white/10 bg-runtime px-3 py-2 text-sm">{games.map(game=><option key={game.id} value={game.id}>{game.title}</option>)}</select><button type="button" disabled={busy||!gameId} onClick={exportAll} className="flex items-center gap-2 rounded border border-white/10 px-3 py-2 text-sm"><Download size={16}/>Export all packs</button><label className="flex cursor-pointer items-center gap-2 rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950"><Upload size={16}/>Import bundle<input type="file" accept="application/json,.json" disabled={busy||!gameId} onChange={event=>importAll(event.target.files?.[0])} className="sr-only"/></label></div>{summary&&<p className="mt-3 text-sm text-emerald-300">{summary}</p>}{error&&<div className="mt-3"><PageAlert message={error}/></div>}</section>;
}