import { useEffect,useState } from 'react';
import ContentField from '@/components/studio/ContentField';
const prepare=(item,fields)=>Object.fromEntries(fields.map(field=>{const value=item?.[field.key];if(field.type==='json')return [field.key,JSON.stringify(value??JSON.parse(field.empty||'{}'),null,2)];if(field.type==='tags')return [field.key,(value||[]).join(', ')];if(['dialogueGraph','npcInteractions','references','rewards','worldEventEffects','worldEventEmissions'].includes(field.type))return [field.key,value??[]];if(field.type==='worldEventTrigger')return [field.key,value??{type:'at_time',at_minute:0}];if(field.type==='worldEventConditions')return [field.key,value??{}];if(['interactionTargeting','interactionSource','interactionSkillCheck'].includes(field.type))return [field.key,value];return [field.key,value??(field.type==='checkbox'?false:'')]}));
export default function ContentForm({item,fields,references,busy,onSave,onDelete,onCancel,onChangeValues,saveLabel='Save content'}){
  const [values,setValues]=useState(()=>prepare(item,fields)),[error,setError]=useState('');
  useEffect(()=>{const prepared=prepare(item,fields);setValues(prepared);setError('');onChangeValues?.(prepared)},[item,fields]);
  const changeField=(field,value)=>setValues(current=>{const next={...current,[field.key]:value};if(field.key==='interaction_actions'){const linked=(Array.isArray(value)?value:[]).filter(action=>action.type==='talk'&&action.dialogue_graph_id).map(action=>action.dialogue_graph_id);next.dialogue_graph_ids=[...new Set([...(current.dialogue_graph_ids||[]),...linked])]}onChangeValues?.(next);return next});
  const submit=e=>{e.preventDefault();try{const result={};for(const field of fields){let value=values[field.key];if(field.type==='json')value=JSON.parse(value||field.empty||'{}');if(field.type==='tags')value=String(value||'').split(',').map(x=>x.trim()).filter(Boolean);if(field.type==='number')value=value===''?undefined:Number(value);result[field.key]=value}onSave(result)}catch(caught){setError(`Invalid JSON: ${caught.message}`)}};
  return <form onSubmit={submit} className="overflow-hidden rounded-xl border border-white/10 bg-[#0d1729]"><div className="border-b border-white/10 p-5"><div className="flex items-center gap-2"><span className="rounded bg-cyan-400 px-3 py-1.5 text-sm font-semibold text-slate-950">{item?.id?'Edit content':'New content'}</span><span className="rounded border border-cyan-400/20 px-3 py-1.5 text-sm text-cyan-300">Structured</span></div><h3 className="mt-4 text-lg font-semibold text-slate-100">Structure</h3><p className="text-sm text-slate-400">Structured fields and declarative JSON are validated before this content is saved.</p></div>{error&&<p className="mx-5 mt-4 text-sm text-red-300">{error}</p>}<div className="grid gap-5 p-5 xl:grid-cols-2">{fields.map(field=><ContentField key={field.key} field={field} value={values[field.key]} references={references} allValues={values} onChange={value=>changeField(field,value)}/>)}</div><div className="flex flex-wrap justify-end gap-2 border-t border-white/10 p-4">{item?.id&&onDelete&&<button type="button" disabled={busy} onClick={onDelete} className="mr-auto rounded border border-red-400/20 px-3 py-2 text-sm text-red-300">Delete</button>}{onCancel&&<button type="button" onClick={onCancel} className="rounded border border-white/10 px-3 py-2 text-sm">Cancel</button>}<button disabled={busy} className="rounded bg-runtime-accent px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{saveLabel}</button></div></form>;
}