import { useEffect,useState } from 'react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import ContentForm from '@/components/studio/ContentForm';
import ContentJsonEditor from '@/components/studio/ContentJsonEditor';
import ContentList from '@/components/studio/ContentList';
import ContentAuthoringSummary from '@/components/studio/ContentAuthoringSummary';
import BulkContentUpload from '@/components/studio/BulkContentUpload';
import WorldGraphEditor from '@/components/studio/WorldGraphEditor';
import { contentConfigs } from '@/lib/studioContentConfig';
export default function ContentWorkspace({games,releases}){
  const drafts=releases.filter(x=>x.status==='draft'),[releaseId,setReleaseId]=useState(drafts[0]?.id||''),[type,setType]=useState('LocationDefinition'),[mode,setMode]=useState('structured'),[items,setItems]=useState([]),[references,setReferences]=useState({}),[selected,setSelected]=useState(null),[draftValues,setDraftValues]=useState({}),[workspaceRelease,setWorkspaceRelease]=useState(null),[conflict,setConflict]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const config=contentConfigs[type],sourceRelease=releases.find(x=>x.id===releaseId),release=workspaceRelease?.id===releaseId?workspaceRelease:sourceRelease;
  const load=async()=>{if(!releaseId||type==='WorldGraph')return;setBusy(true);try{const {data}=await invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType:type});setItems(data.items);setWorkspaceRelease(data.release);setSelected(null);setDraftValues({});setConflict(null);setError('')}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[releaseId,type]);
  useEffect(()=>{const types=[...new Set((config?.fields||[]).flatMap(field=>[field.referenceType,...(field.referenceTypes||[])]).filter(Boolean))];if(!releaseId||!types.length){setReferences({});return}Promise.all(types.map(contentType=>invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType}))).then(results=>setReferences(Object.fromEntries(types.map((contentType,index)=>[contentType,results[index].data.items])))).catch(e=>setError(e.response?.data?.error||e.message))},[releaseId,type]);
  const mutate=async payload=>{setBusy(true);setConflict(null);try{await invokeRuntimeCommand({...payload,releaseId,contentType:type,expectedReleaseRevision:release?.revision||1,...(payload.itemId?{expectedRevision:selected?.revision}: {})});await load()}catch(e){const data=e.response?.data;setError(data?.error||e.message);setConflict(data?.conflict||null);setBusy(false)}};
  if(!drafts.length)return <div className="rounded-lg border border-amber-300/20 bg-amber-300/5 p-5 text-sm text-amber-200">Create a draft release before authoring content.</div>;
  return <div className="space-y-4">
    <section className="rounded-xl border border-white/10 bg-[#0d1729] p-4 shadow-lg shadow-black/10">
      <div className="grid gap-4 md:grid-cols-[minmax(220px,0.8fr)_minmax(280px,1.4fr)_auto]">
        <label className="text-sm text-slate-300">Draft release<select value={releaseId} onChange={e=>setReleaseId(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-[#111d31] px-3 py-2.5 text-sm">{drafts.map(x=><option key={x.id} value={x.id}>{games.find(g=>g.id===x.game_id)?.title} · v{x.version}</option>)}</select></label>
        <label className="text-sm text-slate-300">Content type<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full rounded-lg border border-cyan-400 bg-[#111d31] px-3 py-2.5 text-sm"><option value="WorldGraph">World connection graph</option>{Object.entries(contentConfigs).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label>
        <div><p className="text-sm text-slate-300">Mode</p><div className="mt-2 flex rounded-lg border border-slate-700 bg-[#111d31] p-0.5"><button type="button" onClick={()=>setMode('structured')} className={`rounded-md px-3 py-2 text-xs ${mode==='structured'?'bg-cyan-400 font-semibold text-slate-950':'text-slate-300'}`}>Structured</button><button type="button" onClick={()=>setMode('json')} className={`rounded-md px-3 py-2 text-xs ${mode==='json'?'bg-cyan-400 font-semibold text-slate-950':'text-slate-300'}`}>Full JSON</button></div></div>
      </div><p className="mt-4 border-t border-white/10 pt-4 text-sm text-slate-400">Draft content is editable until publication.</p>
    </section>
    {error&&<div className="rounded-lg border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200"><p>{error}</p>{conflict&&<button type="button" onClick={load} className="mt-2 rounded border border-red-300/30 px-3 py-1.5 text-xs font-semibold">Reload latest content</button>}</div>}
    {type==='WorldGraph'?<WorldGraphEditor releaseId={releaseId}/>:<div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_260px]">
      <main className="space-y-4"><ContentList label={config.label} items={items} selected={selected} onSelect={item=>{setSelected(item);setDraftValues({})}} onAdd={()=>{setSelected({});setDraftValues({})}} locked={!release||release.status!=='draft'}/>{selected?(mode==='json'?<ContentJsonEditor item={selected} busy={busy} onCancel={()=>setSelected(null)} onChangeValues={setDraftValues} onSave={values=>mutate({command:'SAVE_STUDIO_CONTENT',itemId:selected.id,values})} onDelete={selected.id?()=>window.confirm('Delete this draft content?')&&mutate({command:'DELETE_STUDIO_CONTENT',itemId:selected.id}):null}/>:<ContentForm item={selected} fields={config.fields} references={references} busy={busy} onCancel={()=>setSelected(null)} onChangeValues={setDraftValues} onSave={values=>mutate({command:'SAVE_STUDIO_CONTENT',itemId:selected.id,values})} onDelete={selected.id?()=>window.confirm('Delete this draft content?')&&mutate({command:'DELETE_STUDIO_CONTENT',itemId:selected.id}):null}/>):<div className="overflow-hidden rounded-xl border border-white/10 bg-[#0d1729]"><h3 className="border-b border-white/10 p-4 font-semibold text-slate-100">Empty state</h3><div className="grid min-h-40 place-items-center p-6 text-sm text-slate-500">Select a record or create one.</div></div>}</main>
      <div className="space-y-4"><ContentAuthoringSummary release={release} config={config} item={selected} values={draftValues} mode={mode} count={items.length}/><BulkContentUpload releaseId={releaseId} releaseRevision={release?.revision||1} contentType={type} busy={busy} onImported={load} onError={setError}/></div>
    </div>}
  </div>;
}