import { useEffect,useState } from 'react';
import { base44 } from '@/api/base44Client';
import ContentForm from '@/components/studio/ContentForm';
import ContentList from '@/components/studio/ContentList';
import WorldGraphEditor from '@/components/studio/WorldGraphEditor';
import { contentConfigs } from '@/lib/studioContentConfig';
export default function ContentWorkspace({games,releases}){
  const drafts=releases.filter(x=>x.status==='draft'),[releaseId,setReleaseId]=useState(drafts[0]?.id||''),[type,setType]=useState('LocationDefinition'),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const config=contentConfigs[type],release=releases.find(x=>x.id===releaseId);
  const load=async()=>{if(!releaseId||type==='WorldGraph')return;setBusy(true);try{const {data}=await base44.functions.invoke('runtimeCommand',{command:'GET_STUDIO_CONTENT',releaseId,contentType:type});setItems(data.items);setSelected(null);setError('')}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[releaseId,type]);
  const mutate=async payload=>{setBusy(true);try{await base44.functions.invoke('runtimeCommand',{...payload,releaseId,contentType:type});await load()}catch(e){setError(e.response?.data?.error||e.message);setBusy(false)}};
  if(!drafts.length)return <div className="rounded-lg border border-amber-300/20 bg-amber-300/5 p-5 text-sm text-amber-200">Create a draft release before authoring content.</div>;
  return <div><div className="mb-4 flex flex-col gap-3 sm:flex-row"><select value={releaseId} onChange={e=>setReleaseId(e.target.value)} className="rounded border border-white/10 bg-runtime-surface px-3 py-2 text-sm">{drafts.map(x=><option key={x.id} value={x.id}>{games.find(g=>g.id===x.game_id)?.title} · v{x.version}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded border border-white/10 bg-runtime-surface px-3 py-2 text-sm"><option value="WorldGraph">World connection graph</option>{Object.entries(contentConfigs).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select><span className="self-center text-xs text-slate-500">Draft content is editable until publication.</span></div>{error&&<p className="mb-4 rounded border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{type==='WorldGraph'?<WorldGraphEditor releaseId={releaseId}/>:<div className="grid gap-4 lg:grid-cols-[260px_1fr]"><ContentList label={config.label} items={items} selected={selected} onSelect={setSelected} onAdd={()=>setSelected({})} locked={!release||release.status!=='draft'}/>{selected?<ContentForm item={selected} fields={config.fields} busy={busy} onCancel={()=>setSelected(null)} onSave={values=>mutate({command:'SAVE_STUDIO_CONTENT',itemId:selected.id,values})} onDelete={selected.id?()=>window.confirm('Delete this draft content?')&&mutate({command:'DELETE_STUDIO_CONTENT',itemId:selected.id}):null}/>:<div className="grid min-h-64 place-items-center rounded-lg border border-dashed border-white/10 text-sm text-slate-500">Select a record or create one.</div>}</div>}</div>;
}