import { Trash2 } from 'lucide-react';
import JsonValueField from '@/components/studio/JsonValueField';
import DialogueSkillCheckEditor from '@/components/studio/DialogueSkillCheckEditor';
import DialogueRandomBranchEditor from '@/components/studio/DialogueRandomBranchEditor';
import DialogueVariableRulesEditor from '@/components/studio/DialogueVariableRulesEditor';

export default function DialogueOptionEditor({ option, nodeKeys, onChange, onRemove }) {
  const set = (key, value) => onChange({ ...option, [key]: value });
  const eventTypes = (option.events || []).map(event => event.event_type).filter(Boolean);
  return <div className="rounded border border-white/10 bg-runtime-surface p-3"><div className="grid gap-2 sm:grid-cols-2"><input value={option.key || ''} onChange={event => set('key', event.target.value)} placeholder="Stable choice key" className="rounded border border-white/10 bg-runtime px-3 py-2 text-sm"/><input value={option.label || ''} onChange={event => set('label', event.target.value)} placeholder="Player-facing choice" className="rounded border border-white/10 bg-runtime px-3 py-2 text-sm"/>{!option.skill_check&&!option.random_branch&&<select value={option.nextNodeKey || ''} onChange={event => set('nextNodeKey', event.target.value)} className="rounded border border-white/10 bg-runtime px-3 py-2 text-sm"><option value="">End conversation</option>{nodeKeys.map(key => <option key={key} value={key}>Continue to: {key}</option>)}</select>}<input value={eventTypes.join(', ')} onChange={event => set('events', event.target.value.split(',').map(value => value.trim()).filter(Boolean).map(event_type => ({ event_type })))} placeholder="Quest events, comma-separated" className="rounded border border-white/10 bg-runtime px-3 py-2 text-sm"/></div>{option.skill_check?<DialogueSkillCheckEditor value={option.skill_check} nodeKeys={nodeKeys} onChange={value => set('skill_check', value)}/>:option.random_branch?<DialogueRandomBranchEditor value={option.random_branch} nodeKeys={nodeKeys} onChange={value => set('random_branch', value)}/>:<div className="mt-2 flex gap-3"><button type="button" onClick={() => onChange({ ...option, nextNodeKey: '', skill_check: { attribute_id: '', difficulty: 10, die_sides: 20, success_node_key: '', failure_node_key: '', success_effects: [], failure_effects: [], success_events: [], failure_events: [] } })} className="text-xs text-runtime-accent">Add skill check</button><button type="button" onClick={() => onChange({ ...option, nextNodeKey: '', random_branch: { outcomes: [] } })} className="text-xs text-violet-300">Add random branch</button></div>}<div className="mt-2 grid gap-2 sm:grid-cols-2"><JsonValueField label="Availability condition" value={option.conditions} emptyValue={{}} onChange={value => set('conditions', value)}/><JsonValueField label="Character and relationship effects" value={option.effects} emptyValue={[]} onChange={value => set('effects', value)}/></div><DialogueVariableRulesEditor conditions={option.variable_conditions || []} updates={option.variable_updates || []} onConditionsChange={value => set('variable_conditions', value)} onUpdatesChange={value => set('variable_updates', value)}/><div className="mt-2 flex justify-end"><button type="button" onClick={onRemove} aria-label="Remove dialogue choice" className="text-red-300"><Trash2 size={15}/></button></div></div>;
}