import { Plus, Trash2 } from 'lucide-react';

const operators = ['equals', 'not_equals', 'gte', 'lte', 'exists', 'not_exists'];
const parseValue = value => value === 'true' ? true : value === 'false' ? false : value === 'null' ? null : value.trim() !== '' && Number.isFinite(Number(value)) ? Number(value) : value;
const showValue = value => value === undefined ? '' : String(value);

export default function DialogueVariableRulesEditor({ conditions = [], updates = [], onConditionsChange, onUpdatesChange }) {
  const changeCondition = (index, patch) => onConditionsChange(conditions.map((item, current) => current === index ? { ...item, ...patch } : item));
  const changeUpdate = (index, patch) => onUpdatesChange(updates.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <div className="mt-2 grid gap-3 rounded border border-amber-400/20 bg-amber-400/5 p-3 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Session conditions</p><div className="mt-2 space-y-2">{conditions.map((condition, index) => <div key={index} className="grid grid-cols-[1fr_110px_1fr_auto] gap-1"><input value={condition.key || ''} onChange={event => changeCondition(index, { key: event.target.value })} placeholder="Variable key" className="rounded border border-white/10 bg-runtime px-2 py-1 text-xs"/><select value={condition.operator || 'equals'} onChange={event => changeCondition(index, { operator: event.target.value })} className="rounded border border-white/10 bg-runtime px-2 py-1 text-xs">{operators.map(operator => <option key={operator}>{operator}</option>)}</select><input disabled={['exists', 'not_exists'].includes(condition.operator)} value={showValue(condition.value)} onChange={event => changeCondition(index, { value: parseValue(event.target.value) })} placeholder="Value" className="rounded border border-white/10 bg-runtime px-2 py-1 text-xs disabled:opacity-40"/><button type="button" onClick={() => onConditionsChange(conditions.filter((_, current) => current !== index))} aria-label="Remove variable condition" className="text-red-300"><Trash2 size={13}/></button></div>)}</div><button type="button" onClick={() => onConditionsChange([...conditions, { key: '', operator: 'equals', value: true }])} className="mt-2 flex items-center gap-1 text-xs text-amber-300"><Plus size={12}/>Add condition</button></div><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Set after choice</p><div className="mt-2 space-y-2">{updates.map((update, index) => <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-1"><input value={update.key || ''} onChange={event => changeUpdate(index, { key: event.target.value })} placeholder="Variable key" className="rounded border border-white/10 bg-runtime px-2 py-1 text-xs"/><input value={showValue(update.value)} onChange={event => changeUpdate(index, { value: parseValue(event.target.value) })} placeholder="Value" className="rounded border border-white/10 bg-runtime px-2 py-1 text-xs"/><button type="button" onClick={() => onUpdatesChange(updates.filter((_, current) => current !== index))} aria-label="Remove variable update" className="text-red-300"><Trash2 size={13}/></button></div>)}</div><button type="button" onClick={() => onUpdatesChange([...updates, { key: '', value: true }])} className="mt-2 flex items-center gap-1 text-xs text-amber-300"><Plus size={12}/>Add update</button></div></div>;
}