import { useState as useLocal } from 'react';
import { LoaderCircle } from 'lucide-react';
export default function SimulationPanels({data,character,busy,name,setName,onGame,onCharacter,onCreate,onCommand}){return <div className="grid gap-4 p-4 lg:grid-cols-2"><Panel title="Test context"><Select value={data.game?.id||''} onChange={onGame} rows={data.games} label="Game"/><Select value={character?.id||''} onChange={onCharacter} rows={data.characters} label="Test character"/><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="min-w-0 flex-1 rounded border border-white/10 bg-runtime px-3 py-2 text-sm"/><Action busy={busy} disabled={!data.release} onClick={onCreate}>Create</Action></div></Panel><BasicPanels data={data} character={character} busy={busy} onCommand={onCommand}/><QuestPanel data={data} character={character} busy={busy} onCommand={onCommand}/><CombatPanel data={data} character={character} busy={busy} onCommand={onCommand}/></div>}
function BasicPanels({data,character,busy,onCommand}){return <><PickerPanel title="Move character" label="Destination" rows={data.locations} action="Relocate" busy={busy} disabled={!character} onRun={id=>onCommand('SIM_MOVE_CHARACTER',{locationId:id})}/><PickerPanel title="Grant item" label="Item definition" rows={data.items} action="Grant item" busy={busy} disabled={!character} onRun={id=>onCommand('SIM_GIVE_ITEM',{itemDefinitionId:id,quantity:1})}/><PickerPanel title="Apply status" label="Status definition" rows={data.statuses} action="Apply status" busy={busy} disabled={!character} onRun={id=>onCommand('SIM_APPLY_STATUS',{statusDefinitionId:id,stacks:1})}/></>}
function QuestPanel({data,character,busy,onCommand}){const [quest,setQuest]=useLocal(''),[state,setState]=useLocal('ACTIVE');return <Panel title="Set quest state"><Select value={quest} onChange={setQuest} rows={data.quests} label="Quest"/><Select value={state} onChange={setState} rows={['AVAILABLE','ACTIVE','COMPLETED','FAILED','ABANDONED'].map(id=>({id,name:id}))} label="State"/><Action busy={busy} disabled={!character||!quest} onClick={()=>onCommand('SIM_SET_QUEST_STATE',{questDefinitionId:quest,questState:state})}>Set state</Action></Panel>}
function CombatPanel({data,character,busy,onCommand}){const [encounter,setEncounter]=useLocal(''),[seed,setSeed]=useLocal('1'),[combat,setCombat]=useLocal('');return <Panel title="Deterministic combat"><Select value={encounter} onChange={setEncounter} rows={data.encounters} label="Encounter"/><label className="block text-xs text-slate-500">Seed<input type="number" min="0" value={seed} onChange={e=>setSeed(e.target.value)} className="mt-1 w-full rounded border border-white/10 bg-runtime px-3 py-2 text-sm text-slate-100"/></label><Action busy={busy} disabled={!character||!encounter} onClick={()=>onCommand('SIM_START_ENCOUNTER',{encounterDefinitionId:encounter,seed:Number(seed)})}>Start encounter</Action><Select value={combat} onChange={setCombat} rows={data.combats.map(row=>({id:row.id,name:`Seed ${row.seed} · ${row.state}`}))} label="Recorded combat"/><Action busy={busy} disabled={!character||!combat} onClick={()=>onCommand('SIM_REPLAY_COMBAT',{combatId:combat})}>Verify replay</Action>{data.replay&&<p className={`rounded p-2 text-xs ${data.replay.matched?'bg-emerald-400/10 text-emerald-300':'bg-red-400/10 text-red-300'}`}>{data.replay.matched?`Replay matched ${data.replay.rolls_checked} recorded rolls for seed ${data.replay.seed}.`:`Replay found ${data.replay.mismatches.length} deterministic mismatches.`}</p>}</Panel>}
function PickerPanel({title,label,rows,action,busy,disabled,onRun}){const [value,setValue]=useLocal('');return <Panel title={title}><Select value={value} onChange={setValue} rows={rows} label={label}/><Action busy={busy} disabled={disabled||!value} onClick={()=>onRun(value)}>{action}</Action></Panel>}
function Panel({title,children}){return <div className="space-y-3 rounded border border-white/10 p-4"><h4 className="text-sm font-medium">{title}</h4>{children}</div>}
function Select({value,onChange,rows,label}){return <label className="block text-xs text-slate-500">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border border-white/10 bg-runtime px-3 py-2 text-sm text-slate-100"><option value="">Select…</option>{rows.map(row=><option key={row.id} value={row.id}>{row.title||row.name}</option>)}</select></label>}
function Action({children,onClick,busy,disabled}){return <button disabled={busy||disabled} onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded bg-runtime-accent px-3 py-2 text-sm font-medium text-slate-950 disabled:opacity-40">{busy&&<LoaderCircle className="animate-spin" size={14}/>} {children}</button>}