import { useEffect, useState } from 'react';
import { ArrowLeftRight, ArrowRight, MapPin, Plus } from 'lucide-react';
import { invokeRuntimeCommand } from '@/lib/runtimeCommandClient';
import WorldRouteForm from '@/components/studio/WorldRouteForm';

export default function WorldGraphEditor({ releaseId }) {
  const [locations,setLocations]=useState([]),[routes,setRoutes]=useState([]),[selected,setSelected]=useState(null),[release,setRelease]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{setBusy(true);try{const [locationResult,routeResult]=await Promise.all(['LocationDefinition','Connection'].map(contentType=>invokeRuntimeCommand({command:'GET_STUDIO_CONTENT',releaseId,contentType})));setLocations(locationResult.data.items);setRoutes(routeResult.data.items);setRelease(locationResult.data.release);setError('')}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[releaseId]);
  const mutate=async(command,payload)=>{setBusy(true);try{await invokeRuntimeCommand({command,releaseId,contentType:'Connection',expectedReleaseRevision:release?.revision||1,...payload,...(payload.itemId?{expectedRevision:selected?.revision}: {})});setSelected(null);await load()}catch(e){setError(e.response?.data?.error||e.message);setBusy(false)}};
  const name=id=>locations.find(x=>x.id===id)?.name||'Missing location';
  if(selected)return <WorldRouteForm route={selected} locations={locations} busy={busy} onCancel={()=>setSelected(null)} onSave={values=>mutate('SAVE_STUDIO_CONTENT',{itemId:selected.id,values})} onDelete={()=>window.confirm('Delete this route?')&&mutate('DELETE_STUDIO_CONTENT',{itemId:selected.id})}/>;
  return <div className="space-y-4">{error&&<p className="rounded border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<div className="flex items-center justify-between"><div><h3 className="font-semibold">World connection graph</h3><p className="text-xs text-slate-500">{locations.length} locations · {routes.length} authored routes</p></div><button onClick={()=>setSelected({})} disabled={busy||locations.length<2} className="flex items-center gap-2 rounded bg-runtime-accent px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40"><Plus size={15}/>Add route</button></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{locations.map(location=><section key={location.id} className="rounded-lg border border-white/10 bg-runtime-surface p-4"><div className="flex items-start gap-2"><MapPin size={17} className="mt-0.5 text-runtime-accent"/><div><h4 className="font-medium">{location.name}</h4><p className="text-xs text-slate-500">{location.location_type||'Location'}{location.tags?.includes('start')?' · Start':''}</p></div></div><div className="mt-4 space-y-2">{routes.filter(route=>route.from_location_id===location.id||(!route.one_way&&route.to_location_id===location.id)).map(route=>{const reverse=route.to_location_id===location.id,Icon=route.one_way?ArrowRight:ArrowLeftRight;return <button key={route.id} onClick={()=>setSelected(route)} className="flex w-full items-center gap-2 rounded border border-white/5 bg-runtime px-3 py-2 text-left text-xs hover:border-runtime-accent/30"><Icon size={14} className="text-runtime-accent"/><span className="min-w-0 flex-1 truncate">{route.label} · {name(reverse?route.from_location_id:route.to_location_id)}</span>{route.enabled===false&&<span className="text-amber-300">Disabled</span>}</button>})}{!routes.some(route=>route.from_location_id===location.id||(!route.one_way&&route.to_location_id===location.id))&&<p className="text-xs text-slate-600">No connected routes</p>}</div><button onClick={()=>setSelected({from_location_id:location.id})} className="mt-3 text-xs text-runtime-accent">Connect from here</button></section>)}</div>
    {!locations.length&&!busy&&<div className="rounded-lg border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">Create locations before connecting the world.</div>}
  </div>;
}