import { Plus,Trash2 } from 'lucide-react';
const types=['hasTag','attributeAtLeast','resourceAtLeast','locationIs','questState','hasItem','hasStatus','timePhaseIs','weatherIs'];
const keyFor={hasTag:'tag',attributeAtLeast:'attributeId',resourceAtLeast:'resourceId',locationIs:'locationId',questState:'questKey',hasItem:'itemKey',hasStatus:'statusKey',timePhaseIs:'phase',weatherIs:'weatherKey'};
const numeric=new Set(['attributeAtLeast','resourceAtLeast','hasItem']),inputClass='rounded border border-white/10 bg-runtime px-2 py-2 text-xs';
export default function WorldEventConditionsEditor({value={},onChange}){
 const advanced=value?.any||value?.not||(value?.all||[]).some(condition=>condition?.all||condition?.any||condition?.not);
 if(advanced)return <div className="rounded border border-runtime-accent/20 bg-runtime-accent/5 p-4 text-sm text-slate-300">This event uses nested condition logic. Edit it in the synchronized JSON panel.</div>;
 const conditions=Array.isArray(value?.all)?value.all:Object.keys(value||{}).length?[value]:[],commit=next=>onChange(next.length?{all:next}:{}),update=(index,patch)=>commit(conditions.map((condition,row)=>row===index?{...condition,...patch}:condition));
 return <div className="space-y-2"><div><p className="text-sm text-slate-300">Required conditions</p><p className="text-xs text-slate-600">All listed conditions must pass.</p></div>{conditions.map((condition,index)=>{const key=keyFor[condition.type]||'tag';return <div key={index} className="grid gap-2 rounded border border-white/10 bg-runtime-surface p-3 sm:grid-cols-[1fr_1fr_110px_auto]"><select value={condition.type||'hasTag'} onChange={event=>update(index,{type:event.target.value,[keyFor[event.target.value]]:''})} className={inputClass}>{types.map(type=><option key={type}>{type}</option>)}</select><input value={condition[key]||''} onChange={event=>update(index,{[key]:event.target.value})} placeholder={key} className={inputClass}/>{numeric.has(condition.type)?<input type="number" value={condition.value??condition.quantity??0} onChange={event=>update(index,condition.type==='hasItem'?{quantity:Number(event.target.value)}:{value:Number(event.target.value)})} className={inputClass}/>:<span/>}<button type="button" onClick={()=>commit(conditions.filter((_,row)=>row!==index))} aria-label="Remove condition" className="text-red-300"><Trash2 size={15}/></button></div>})}<button type="button" onClick={()=>commit([...conditions,{type:'hasTag',subject:'character',tag:''}])} className="flex items-center gap-1 text-xs text-runtime-accent"><Plus size={13}/>Add condition</button></div>;
}